const companyInfo = {
  name: "Hirola Media Ltd",
  number: "16312592",
  address: "137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ"
};

export const legalContent = {
  title: "Mentions légales",
  lastUpdate: "25/09/2024",
  content: [
    {
      title: "Éditeur du site",
      text: `Le site AdInsightAI est édité par Hirola Media Ltd, société enregistrée en Angleterre sous le numéro 16312592, dont le siège social est situé au 137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ. Email de contact : support@adinisghtai.com, Téléphone : (971) 315-8948. AdInsightAI est un service d'analyse de publicités Facebook Ads propulsé par l'intelligence artificielle.`
    },
    {
      title: "2. Directeur de la publication",
      text: "Le Directeur de la publication du Site est le représentant légal de Hirola Media Ltd.\n\nContact : support@adinisghtai.com\nTéléphone : (971) 315-8948"
    },
    {
      title: "3. Hébergement",
      text: "Le Site est hébergé par Vercel Inc., société enregistrée au Delaware, États-Unis, dont le siège social est situé au 340 S Lemon Ave #4133, Walnut, CA 91789, USA.\n\nVercel est un fournisseur de services d'hébergement conforme au UK GDPR et offre les garanties appropriées pour le transfert de données entre le Royaume-Uni et les États-Unis.\n\nSite web : https://vercel.com\nEmail : privacy@vercel.com"
    },
    {
      title: "4. Propriété intellectuelle",
      text: "4.1 Titularité des droits : L'ensemble des éléments constituant le Site et le Service Hirola Media (notamment les textes, graphismes, logiciels, photographies, images, vidéos, sons, plans, logos, marques, noms de domaine, et tout autre élément distinctif) sont protégés par les lois et règlements français et internationaux relatifs à la propriété intellectuelle. Ces éléments demeurent la propriété exclusive de Hirola Media et/ou de ses concédants de licence.\n\n4.2 Interdiction de reproduction non autorisée : Toute reproduction, représentation, modification, publication, adaptation, exploitation de tout ou partie des éléments du Site, quel que soit le moyen ou le procédé utilisé, est strictement interdite sans l'autorisation écrite préalable de Hirola Media. Toute exploitation non autorisée du Site ou de l'un quelconque des éléments qu'il contient sera considérée comme constitutive d'une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de la Propriété Intellectuelle.\n\n4.3 Marques et noms commerciaux : Les marques et noms commerciaux « Hirola Media » figurant sur le Site sont des marques déposées auprès de l'Institut National de la Propriété Industrielle (INPI). Toute reproduction ou utilisation de ces marques sans autorisation préalable et écrite de Hirola Media est prohibée.\n\n4.4 Liens vers le Site : La mise en place d'un lien hypertexte vers le Site ne nécessite pas d'autorisation préalable et écrite de Hirola Media. Néanmoins, Hirola Media se réserve le droit de demander la suppression d'un lien si elle estime que le site source ne respecte pas ses valeurs ou porte atteinte à son image."
    },
    {
      title: "5. Protection des données personnelles",
      text: "5.1 Responsable de traitement : Hirola Media, en sa qualité de responsable de traitement au sens du Règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016 relatif à la protection des personnes physiques à l'égard du traitement des données à caractère personnel et à la libre circulation de ces données (« RGPD »), s'engage à protéger la vie privée des utilisateurs du Site et à assurer la confidentialité des informations personnelles fournies.\n\n5.2 Délégué à la Protection des Données : Conformément à l'article 37 du RGPD, Hirola Media a désigné un Délégué à la Protection des Données (DPO) que vous pouvez contacter pour toute question relative au traitement de vos données personnelles :\n\nPar email : support@adinisghtai.com\nPar courrier : Hirola Media Ltd - Délégué à la Protection des Données, 137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ\n\n5.3 Droits des personnes concernées : Conformément au RGPD et à la loi n° 78-17 du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés modifiée (dite « Loi Informatique et Libertés »), vous disposez des droits suivants concernant vos données personnelles : droit d'accès, droit de rectification, droit à l'effacement, droit à la limitation du traitement, droit à la portabilité des données, droit d'opposition, droit de définir des directives relatives au sort de vos données après votre décès, et droit d'introduire une réclamation auprès de la Commission Nationale de l'Informatique et des Libertés (CNIL).\n\n5.4 Politique de confidentialité : Pour obtenir des informations détaillées sur la collecte, l'utilisation et la protection de vos données personnelles, veuillez consulter notre Politique de confidentialité."
    },
    {
      title: "6. Cookies et technologies similaires",
      text: "6.1 Définition : Un cookie est un petit fichier texte déposé sur votre terminal (ordinateur, tablette, smartphone) lorsque vous visitez notre Site ou utilisez notre Service. Les cookies nous permettent de reconnaître votre navigateur et de recueillir certaines informations sur votre navigation.\n\n6.2 Types de cookies utilisés : Notre Site utilise différents types de cookies :\n- Cookies strictement nécessaires au fonctionnement du Site\n- Cookies de fonctionnalité permettant de mémoriser vos préférences\n- Cookies analytiques permettant de comprendre comment vous utilisez notre Site\n- Cookies de ciblage/publicitaires permettant de vous proposer des contenus personnalisés\n\n6.3 Base juridique : Conformément à l'article 82 de la loi Informatique et Libertés, les cookies strictement nécessaires au fonctionnement du Site sont déposés sur le fondement de notre intérêt légitime. Les autres types de cookies ne sont déposés qu'après avoir recueilli votre consentement préalable, que vous pouvez retirer à tout moment.\n\n6.4 Gestion des cookies : Vous pouvez à tout moment configurer votre navigateur pour accepter, refuser ou supprimer tout ou partie des cookies. Vous pouvez également utiliser notre panneau de gestion des cookies accessible via le lien « Paramètres des cookies » présent en bas de chaque page de notre Site.\n\n6.5 Informations sur les cookies : Pour obtenir des informations détaillées sur les cookies que nous utilisons, leurs finalités, durées de conservation et les tiers y ayant accès, veuillez consulter la section dédiée aux cookies dans notre Politique de confidentialité."
    },
    {
      title: "7. Limitation de responsabilité",
      text: "7.1 Exactitude des informations : Hirola Media s'efforce d'assurer au mieux de ses possibilités l'exactitude et la mise à jour des informations diffusées sur le Site. Toutefois, Hirola Media ne peut garantir l'exactitude, la précision, l'exhaustivité ou l'adéquation des informations mises à disposition sur le Site à des fins particulières. En conséquence, Hirola Media décline toute responsabilité pour toute imprécision, inexactitude ou omission portant sur des informations disponibles sur le Site.\n\n7.2 Disponibilité du Site : Hirola Media s'efforce de maintenir le Site accessible 24 heures sur 24 et 7 jours sur 7. Néanmoins, Hirola Media ne saurait être tenue responsable en cas d'indisponibilité du Site, pour quelque cause que ce soit, y compris en cas de maintenance nécessaire au bon fonctionnement du Site ou en cas de force majeure.\n\n7.3 Sécurité informatique : L'utilisateur du Site reconnaît avoir connaissance des caractéristiques et des limites de l'Internet, en particulier de ses performances techniques, des temps de réponse pour consulter, interroger ou transférer des données, et des risques liés à la sécurité des communications. Hirola Media ne saurait être tenue responsable des dommages directs ou indirects, matériels ou immatériels, résultant notamment de l'utilisation du Site ou de l'impossibilité d'y accéder, de l'utilisation, du dysfonctionnement, d'une interruption ou d'un virus informatique.\n\n7.4 Limitation générale : Dans toute la mesure permise par la loi applicable, la responsabilité de Hirola Media est limitée aux dommages directs, à l'exclusion de tout dommage indirect, de quelque nature que ce soit."
    },
    {
      title: "8. Liens hypertextes vers des sites tiers",
      text: "8.1 Présence de liens externes : Le Site peut contenir des liens hypertextes redirigeant vers des sites internet édités et/ou gérés par des tiers. Dans la mesure où Hirola Media ne peut exercer aucun contrôle sur ces sites tiers, Hirola Media ne peut être tenue responsable de l'accès à ces sites et sources externes, de leur contenu, publicités, produits, services ou tout autre élément disponible sur ou à partir de ces sites ou sources externes.\n\n8.2 Absence de responsabilité : Hirola Media décline toute responsabilité quant aux contenus, légalité, exactitude ou disponibilité des informations, produits, services ou tout autre élément présent sur ces sites tiers. L'insertion de ces liens ne signifie pas que Hirola Media approuve les éléments contenus sur ces sites. Il appartient à l'utilisateur de prendre toutes les précautions nécessaires pour s'assurer que le site tiers sélectionné ne contient ni virus informatique ni élément susceptible d'endommager son équipement informatique ou ses données.\n\n8.3 Signalement de contenu illicite : Si vous constatez qu'un site vers lequel Hirola Media a créé un lien permet d'accéder à des contenus illicites, vous êtes invité à le signaler immédiatement à Hirola Media à l'adresse suivante : support@adinisghtai.com. Hirola Media s'engage à supprimer promptement tout lien vers un contenu manifestement illicite dès qu'elle en aura connaissance."
    },
    {
      title: "9. Droit applicable et juridiction compétente",
      text: "9.1 Droit applicable : Les présentes mentions légales sont régies par le droit britannique (UK). Elles sont rédigées en langue française. Dans le cas où elles seraient traduites en une ou plusieurs langues, seul le texte français ferait foi en cas de litige.\n\n9.2 Règlement amiable des litiges : En cas de litige relatif à l'interprétation ou à l'exécution des présentes mentions légales, les parties s'efforceront de trouver une solution amiable avant toute action judiciaire.\n\n9.3 Juridiction compétente : À défaut de résolution amiable, tout litige relatif aux présentes mentions légales sera soumis à la compétence exclusive des tribunaux britanniques, sauf disposition légale impérative contraire. Pour les utilisateurs agissant en qualité de commerçants, tout litige sera soumis à la compétence exclusive des tribunaux de Londres."
    },
    {
      title: "10. Médiation de la consommation",
      text: "10.1 Dispositif de médiation : Conformément aux articles L. 611-1 et suivants du Code de la consommation, Hirola Media propose à ses clients consommateurs un dispositif de médiation pour la résolution amiable des litiges. Hirola Media a désigné comme médiateur de la consommation Médiation-Net, dont les coordonnées sont les suivantes :\n\nMédiation-Net\n34 rue des Épinettes, 75017 Paris, France\nSite internet : www.mediation-net.com\nEmail : contact@mediation-net.com\n\n10.2 Conditions de recevabilité : Pour être recevable, la demande de médiation doit être introduite dans un délai d'un an à compter de la réclamation écrite adressée à Hirola Media. Le litige ne doit pas avoir été précédemment examiné ou être en cours d'examen par un autre médiateur ou par un tribunal.\n\n10.3 Gratuité : La médiation de la consommation est gratuite pour le consommateur, à l'exception des frais d'avocat ou d'expertise dont il pourrait solliciter l'assistance, ou des frais de déplacement s'il est convoqué en dehors de son lieu d'habitation.\n\n10.4 Plateforme européenne de règlement en ligne des litiges : Pour les litiges transfrontaliers, les consommateurs résidant dans l'Union européenne peuvent également recourir à la plateforme européenne de règlement en ligne des litiges accessible à l'adresse suivante : https://ec.europa.eu/consumers/odr/"
    },
    {
      title: "11. Modifications des mentions légales",
      text: "11.1 Droit de modification : Hirola Media se réserve le droit de modifier, compléter ou remplacer les présentes mentions légales à tout moment. Les utilisateurs du Site sont donc invités à les consulter régulièrement.\n\n11.2 Date d'effet : Les modifications apportées aux mentions légales prennent effet dès leur publication sur le Site. L'utilisation continue du Site après publication des mentions légales modifiées vaut acceptation de ces modifications.\n\nDernière mise à jour des mentions légales : 25/09/2024"
    },
    {
      title: "13. Contact et service client",
      text: "Pour toute question concernant les présentes CGU ou le Service, l'Utilisateur peut contacter Hirola Media Ltd aux coordonnées suivantes :\n\nHirola Media Ltd\n137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ\nEmail : support@adinisghtai.com\nTéléphone : (971) 315-8948\n\nLe service client est disponible du lundi au vendredi, de 9h à 18h (heure de Londres), hors jours fériés.\n\nDernière mise à jour des CGU : 25/09/2024"
    }
  ]
}; 