const companyInfo = {
  name: "Hirola Media Ltd",
  number: "16312592",
  address: "137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ"
};

export const refundContent = {
  title: "Politique de Remboursement",
  lastUpdate: "25/09/2024",
  content: [
    {
      title: "1. Achat de tokens",
      text: "1.1 Caractère définitif des achats : Les tokens acquis sur la plateforme AdInsight AI, notre plateforme d'analyse de données publicitaires, que ce soit via un abonnement ou à l'unité (« à la carte »), ne sont pas remboursables. Conformément aux dispositions de la Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013, Regulation 28(1)(b), tout achat de tokens est considéré comme l'achat d'un contenu numérique non fourni sur un support matériel, pour lequel le droit de rétractation légal ne s'applique pas dès lors que vous avez donné votre consentement préalable à l'exécution du service et renoncé expressément à votre droit de rétractation.\n\n1.2 Engagement de qualité : Nous nous efforçons de fournir un service de haute qualité et nous vous remercions de votre confiance. Toutefois, en raison de la nature même des tokens et de leur utilisation pour l'accès à des fonctionnalités numériques, aucun remboursement ne sera accordé pour les tokens achetés, qu'ils aient été utilisés ou non.\n\n1.3 Absence de garantie de résultat : AdInsight AI ne garantit aucun résultat spécifique quant à l'utilisation des tokens pour l'accès aux analyses. La qualité, la pertinence ou l'adéquation des analyses à vos besoins particuliers ne peut constituer un motif de remboursement."
    },
    {
      title: "2. Abonnements",
      text: "2.1 Facturation récurrente : Les abonnements souscrits sur la plateforme AdInsight AI font l'objet d'une facturation récurrente selon la périodicité choisie lors de la souscription (mensuelle, trimestrielle ou annuelle). Le montant correspondant est automatiquement prélevé sur le moyen de paiement enregistré.\n\n2.2 Annulation d'abonnement : Vous pouvez annuler votre abonnement à tout moment depuis votre espace client ou en contactant notre service client. L'annulation prendra effet à la fin de la période d'abonnement en cours. Aucun remboursement prorata temporis ne sera effectué pour la période restante jusqu'à l'échéance.\n\n2.3 Renouvellement automatique : Les abonnements sont automatiquement renouvelés à l'échéance, sauf résiliation préalable de votre part. Il est de votre responsabilité de résilier votre abonnement avant la date de renouvellement si vous ne souhaitez pas le poursuivre.\n\n2.4 Modification de formule : La modification de votre formule d'abonnement pour une formule supérieure (upgrade) ou inférieure (downgrade) est possible à tout moment, mais n'ouvre droit à aucun remboursement. En cas d'upgrade, la différence de prix sera calculée au prorata de la période restante."
    },
    {
      title: "3. Gestion des tokens non utilisés",
      text: "3.1 Expiration des tokens : Les tokens non utilisés à l'échéance de votre période d'abonnement peuvent être soumis à expiration ou faire l'objet d'un report sur la période suivante, selon les conditions spécifiques du forfait souscrit. Ces conditions sont expressément mentionnées dans la description de l'offre au moment de la souscription.\n\n3.2 Absence de remboursement : En aucun cas les tokens non utilisés ne pourront faire l'objet d'un remboursement en numéraire, quelle que soit la cause de leur non-utilisation (résiliation volontaire d'abonnement, suspension ou fermeture de compte, force majeure, etc.).\n\n3.3 Non-transférabilité : Les tokens sont strictement personnels et rattachés au compte utilisateur pour lequel ils ont été acquis. Ils ne peuvent être cédés, transférés ou revendus à un tiers, sous peine de suspension immédiate du compte sans compensation."
    },
    {
      title: "4. Réclamations liées à la facturation",
      text: "4.1 Procédure de réclamation : En cas d'erreur de facturation constatée (double facturation, montant erroné, etc.), vous pouvez soumettre une réclamation détaillée et circonstanciée, par email à l'adresse contact@adinsight-ai.com ou via le formulaire de contact dédié accessible dans votre espace client.\n\n4.2 Justificatifs requis : Toute réclamation relative à une erreur de facturation devra être accompagnée des justificatifs nécessaires (relevé bancaire, confirmation de paiement, etc.) et soumise dans un délai maximum de trente (30) jours à compter de la date de la transaction contestée.\n\n4.3 Traitement des réclamations : Nous nous engageons à examiner votre réclamation dans un délai de quinze (15) jours ouvrés à compter de sa réception complète (incluant tous les justificatifs requis). Après confirmation de l'erreur de facturation, AdInsight AI procédera, à sa discrétion, soit au remboursement du montant indûment facturé sur le moyen de paiement initialement utilisé, soit à l'octroi d'un crédit de tokens équivalent sur votre compte.\n\n4.4 Limites : Les réclamations portant sur des transactions datant de plus de trois (3) mois ne pourront être prises en compte, sauf circonstances exceptionnelles dûment justifiées."
    },
    {
      title: "5. Cas exceptionnels",
      text: "5.1 Interruption significative du service : En cas de dysfonctionnement technique majeur imputable à AdInsight AI et rendant impossible l'utilisation du service pendant une durée continue supérieure à vingt-quatre (24) heures, une compensation pourra être accordée sous forme de tokens supplémentaires.\n\n5.2 Mise à jour majeure : Dans l'hypothèse où une mise à jour substantielle de notre plateforme entraînerait une modification significative des fonctionnalités ayant motivé votre souscription, nous pourrons, à notre seule discrétion et sans y être tenus, proposer une solution commerciale adaptée à la situation.\n\n5.3 Clôture de compte : La clôture définitive de votre compte, quelle qu'en soit la raison (y compris à votre initiative), entraîne la perte définitive des tokens restants sans possibilité de conversion en valeur monétaire ou de transfert à un autre compte."
    },
    {
      title: "6. Tokens non utilisés",
      text: "6.1 Non-remboursement : Les tokens non utilisés, quelle que soit leur origine (abonnement ou achat à l'unité), ne sont pas remboursables en espèces ou autres moyens de paiement.\n\n6.2 Expiration : En cas de violation des Conditions Générales d'Utilisation, AdInsight AI se réserve le droit de supprimer l'intégralité des tokens restants sans compensation d'aucune sorte.\n\n6.3 Délai de grâce : Avant toute fermeture volontaire de compte, un message d'avertissement vous sera envoyé pour vous informer des tokens restants sur votre compte et vous rappeler leur caractère non remboursable. Un délai de grâce de quatorze (14) jours vous sera accordé pour utiliser vos tokens restants avant la fermeture définitive du compte.\n\n6.4 Compte inactif : En cas d'inactivité de votre compte pendant une période de douze (12) mois consécutifs, les tokens restants pourront être supprimés après un préavis de trente (30) jours envoyé à l'adresse email associée à votre compte. Si vous réactivez votre compte dans les trente (30) jours suivant la fermeture, AdInsight AI pourra, à sa seule discrétion et sans y être tenue, restaurer tout ou partie des tokens perdus."
    },
    {
      title: "7. Exceptions pour les nouveaux utilisateurs",
      text: "7.1 Délai de réflexion : Bien que les achats de Tokens soient généralement non remboursables en vertu des dispositions de la Consumer Rights Act 2015 relative aux contenus numériques, AdInsight AI accorde contractuellement un délai de réflexion de vingt-quatre (24) heures à compter de l'achat pour les nouveaux utilisateurs effectuant leur premier achat de tokens.\n\n7.2 Conditions : Pour bénéficier de ce délai de réflexion, les conditions suivantes doivent être cumulativement remplies :\n- Il doit s'agir du premier achat de Tokens effectué par l'utilisateur sur la plateforme AdInsight AI ;\n- La demande de remboursement doit être formulée dans les vingt-quatre (24) heures suivant l'achat initial ;\n- Aucun Token du pack concerné ne doit avoir été utilisé.\n\n7.3 Modalités de remboursement : La demande de remboursement doit être adressée par email à l'adresse contact@adinsight-ai.com en précisant le numéro de commande et la date d'achat. Le remboursement sera effectué par le même moyen de paiement que celui utilisé lors de l'achat initial, dans un délai de quatorze (14) jours à compter de la réception de la demande conforme aux conditions ci-dessus."
    },
    {
      title: "8. Circonstances exceptionnelles",
      text: "8.1 Pouvoir discrétionnaire : Dans des circonstances exceptionnelles dûment justifiées et documentées, AdInsight AI se réserve le droit, à sa seule et entière discrétion, d'examiner des demandes de remboursement particulières ne relevant pas des cas précédemment énumérés.\n\n8.2 Non-création de précédent : Tout remboursement exceptionnel accordé dans ce cadre ne saurait constituer un précédent invocable par d'autres utilisateurs ou dans d'autres circonstances.\n\n8.3 Modalités : Dans l'hypothèse où un remboursement exceptionnel serait accordé, il s'effectuerait par le même moyen de paiement que celui utilisé pour la transaction initiale, sauf impossibilité technique ou accord mutuel sur un autre moyen de remboursement n'entraînant pas de frais supplémentaires pour vous."
    },
    {
      title: "9. Procédure de réclamation",
      text: "9.1 Canaux de communication : Toute réclamation relative à la présente politique de remboursement doit être adressée par écrit via notre formulaire de contact en ligne, par courrier postal ou par email à l'adresse contact@adinsight-ai.com.\n\n9.2 Délai de forclusion : Toute réclamation doit être formulée dans un délai de trente (30) jours calendaires à compter de la date de la transaction contestée ou du fait générateur du litige. Au-delà de ce délai, la réclamation pourra être déclarée irrecevable, sauf circonstance exceptionnelle justifiée.\n\n9.3 Informations requises : Votre réclamation doit contenir une description précise et détaillée de l'objet de votre demande, accompagnée de tout élément probant susceptible d'étayer votre demande (captures d'écran, relevés bancaires, communications antérieures avec nos services, etc.).\n\n9.4 Délai de traitement : Nous nous engageons à accuser réception de votre réclamation dans un délai de deux (2) jours ouvrés et à y apporter une réponse circonstanciée dans un délai maximum de quinze (15) jours ouvrés, sauf circonstances particulières nécessitant des investigations complémentaires, auquel cas vous serez informé du délai prévisible de traitement.\n\n9.5 Médiation : En cas de désaccord persistant après épuisement de nos procédures internes de réclamation, vous avez la possibilité, si vous êtes un consommateur, de recourir gratuitement au service de médiation proposé par AdInsight AI. Le médiateur de la consommation ainsi désigné est Médiation-Net, que vous pouvez contacter à l'adresse suivante : 34 rue des Épinettes, 75017 Paris, France. Site web : www.mediation-net.com, email : contact@mediation-net.com.\n\n9.6 Conditions de recevabilité en médiation : Pour être recevable, votre demande de médiation doit être introduite dans un délai d'un an à compter de votre réclamation écrite auprès de nos services, et le litige ne doit pas avoir été précédemment examiné ou être en cours d'examen par un autre médiateur ou par un tribunal."
    },
    {
      title: "10. Dispositions finales",
      text: "10.1 Droit de modification : AdInsight AI se réserve le droit de modifier, compléter ou remplacer tout ou partie de la présente politique de remboursement à tout moment, notamment pour l'adapter aux évolutions législatives et réglementaires ou à nos pratiques commerciales.\n\n10.2 Notification des modifications : Toute modification substantielle de la présente politique fera l'objet d'une notification préalable par email et/ou par affichage visible sur notre plateforme.\n\n10.3 Date d'effet : Les modifications apportées à la présente politique prendront effet à la date indiquée dans la notification ou, à défaut, trente (30) jours après leur publication.\n\n10.4 Droit applicable : La présente politique de remboursement est régie par le droit britannique (UK).\n\n10.5 Indépendance des clauses : Si une ou plusieurs dispositions de la présente politique étaient jugées nulles, illégales ou inapplicables en vertu du droit applicable, ces dispositions seraient réputées non écrites sans que cela n'affecte la validité et l'applicabilité des autres dispositions."
    }
  ]
}; 