export const termsContent = {
  title: "Conditions Générales d'Utilisation",
  content: [
    {
      title: "1. Préambule",
      text: "Les présentes Conditions Générales d'Utilisation (ci-après dénommées « CGU ») constituent un contrat juridiquement contraignant entre vous, utilisateur (ci-après dénommé « l'Utilisateur » ou « vous ») et la société Addax Media Ltd, société immatriculée en Angleterre sous le numéro 16314045, dont le siège social est situé à Flat 5, 9 Langley Road, Watford, England, WD17 4PS (ci-après dénommée « Addax Media », « nous » ou « notre »). En accédant à notre plateforme, en l'utilisant ou en vous y inscrivant, vous reconnaissez avoir lu, compris et accepté sans réserve l'intégralité des présentes CGU.\n\n1.2 Définitions : Dans les présentes CGU, les termes suivants, lorsqu'ils sont écrits avec une majuscule, ont la signification ci-après : « Service » désigne la plateforme OneirICrafts, ses fonctionnalités et tous les services associés ; « Contenu » désigne tout texte, image, vidéo, audio ou autre matériel généré ou téléchargé sur la plateforme ; « Token » désigne l'unité de valeur virtuelle permettant d'accéder aux fonctionnalités de génération de contenu."
    },
    {
      title: "2. Description du Service",
      text: "SEOForgeAI est une plateforme de génération de contenu SEO et de descriptions de produits alimentée par l'intelligence artificielle, accessible via le site internet seoforgeai.com. Le Service permet aux Utilisateurs de générer automatiquement du contenu optimisé pour le référencement naturel moyennant l'utilisation de Tokens. SEOForgeAI se réserve le droit, à sa seule discrétion et sans notification préalable, de modifier, suspendre, restreindre ou interrompre, temporairement ou définitivement, tout ou partie du Service, pour des raisons de maintenance, de mise à jour, de sécurité ou tout autre motif jugé pertinent par SEOForgeAI. L'Utilisateur reconnaît que SEOForgeAI n'encourra aucune responsabilité envers lui ou tout tiers pour toute modification, suspension ou interruption du Service."
    },
    {
      title: "3. Compte Utilisateur",
      text: "3.1 Création de compte : Pour accéder aux fonctionnalités complètes du Service, vous devez créer un compte utilisateur en fournissant des informations exactes, complètes et à jour. Vous devez avoir au moins 18 ans ou la majorité légale dans votre juridiction, selon laquelle est la plus élevée, pour créer un compte.\n\n3.2 Informations personnelles : Vous êtes responsable de la mise à jour de vos informations personnelles afin qu'elles restent exactes et complètes. Vous vous engagez à informer SEOForgeAI de tout changement concernant ces informations en cas de modification. SEOForgeAI se réserve le droit de vérifier l'exactitude des informations fournies et de suspendre ou supprimer tout compte contenant des informations inexactes, incomplètes ou frauduleuses.\n\n3.3 Sécurité du compte : Vous êtes seul responsable de la confidentialité de vos identifiants de connexion (adresse e-mail et mot de passe) et de toutes les activités qui se déroulent sur votre compte. Vous vous engagez à choisir un mot de passe suffisamment robuste, à ne pas le divulguer à des tiers et à vous déconnecter à la fin de chaque session. L'Utilisateur s'engage à notifier immédiatement SEOForgeAI de toute utilisation non autorisée de son compte ou de toute autre violation de sécurité. SEOForgeAI ne pourra être tenue responsable des pertes ou dommages résultant du non-respect par l'Utilisateur de ces obligations de sécurité."
    },
    {
      title: "4. Utilisation du Service",
      text: "4.1 Utilisation autorisée : En utilisant le Service, vous vous engagez à respecter toutes les lois et réglementations applicables. Il est notamment interdit d'utiliser le Service pour créer, publier, transmettre ou stocker du contenu : illégal, frauduleux, trompeur ou mensonger ; diffamatoire, obscène, pornographique ou contraire aux bonnes mœurs ; violant les droits de propriété intellectuelle de tiers ; constituant du harcèlement, des menaces ou de l'intimidation ; encourageant la discrimination, le racisme, la haine ou la violence contre un individu ou un groupe ; contenant des virus, des chevaux de Troie ou tout autre code malveillant.\n\n4.2 Responsabilité du Contenu : L'Utilisateur est pleinement responsable du fait du Contenu généré via le Service. SEOForgeAI ne garantit pas l'exactitude, la pertinence, la qualité ou la légalité du Contenu généré. L'Utilisateur s'engage à vérifier et, si nécessaire, à modifier le Contenu généré avant toute utilisation ou publication. SEOForgeAI décline expressément toute responsabilité quant aux conséquences directes ou indirectes de l'utilisation du Contenu généré par l'Utilisateur.\n\n4.3 Restrictions techniques : L'Utilisateur s'engage à ne pas : tenter de contourner, désactiver ou interférer avec les fonctionnalités de sécurité du Service ; utiliser des robots, des scrapers ou d'autres moyens automatisés pour accéder au Service ; interférer avec ou perturber l'intégrité ou les performances du Service ; créer plusieurs comptes pour contourner les limitations d'utilisation ; revendre, louer, prêter ou transférer son accès au Service à des tiers ; utiliser le Service à des fins non autorisées par SEOForgeAI."
    },
    {
      title: "5. Tokens et Paiements",
      text: "5.1 Système de Tokens : L'accès aux fonctionnalités de génération de contenu du Service nécessite l'utilisation de Tokens. Les Tokens peuvent être acquis via un abonnement récurrent ou à l'unité (« à la carte »). Le nombre de Tokens requis pour générer du contenu varie en fonction du type et de la longueur du contenu demandé.\n\n5.2 Tarifs : Les tarifs applicables aux différentes formules d'abonnement et aux achats à l'unité sont ceux en vigueur au moment de l'achat, tels qu'indiqués sur le site. SEOForgeAI se réserve le droit de modifier ses tarifs à tout moment, moyennant un préavis de trente (30) jours pour les abonnements en cours.\n\n5.3 Validité des Tokens : Les Tokens acquis via un abonnement sont valables pendant la durée de l'abonnement. Les Tokens non utilisés à la fin de la période d'abonnement peuvent être perdus ou reportés sur la période suivante, selon les conditions spécifiques de l'offre souscrite. Les Tokens achetés à l'unité sont valables pour une durée de douze (12) mois à compter de leur date d'achat, sauf indication contraire.\n\n5.4 Non-remboursement : Les Tokens achetés ne sont pas remboursables, même s'ils n'ont pas été utilisés. Pour plus de détails, veuillez consulter notre Politique de Remboursement.\n\n5.5 Modalités de paiement : Nous acceptons différents modes de paiement, notamment les cartes de crédit, les virements bancaires et certains portefeuilles électroniques, selon les pays. En fournissant vos informations de paiement, vous garantissez que vous êtes autorisé à utiliser le mode de paiement choisi et vous autorisez SEOForgeAI à vous facturer via ce mode de paiement. SEOForgeAI n'est pas responsable des erreurs ou des frais imposés par votre établissement financier ou votre émetteur de carte."
    },
    {
      title: "6. Abonnements",
      text: "6.1 Souscription : La souscription à un abonnement s'effectue en ligne via le site seoforgeai.com. L'abonnement prend effet à compter de la confirmation du paiement et reste valable pour la durée souscrite (mensuelle, trimestrielle ou annuelle).\n\n6.2 Renouvellement automatique : Sauf indication contraire lors de la souscription, les abonnements se renouvellent automatiquement à la fin de chaque période de facturation. L'Utilisateur peut désactiver le renouvellement automatique à tout moment depuis son espace client. La désactivation prendra effet à la fin de la période en cours.\n\n6.3 Résiliation par l'Utilisateur : L'Utilisateur peut résilier son abonnement à tout moment depuis son espace client. La résiliation prendra effet à la fin de la période de facturation en cours.\n\n6.4 Résiliation par SEOForgeAI : SEOForgeAI se réserve le droit de résilier unilatéralement tout abonnement en cas de violation des présentes CGU, de non-paiement, ou pour tout autre motif légitime. Dans ce cas, la résiliation prendra effet immédiatement et sans remboursement de la période en cours."
    },
    {
      title: "7. Propriété intellectuelle",
      text: "7.1 Propriété de SEOForgeAI : SEOForgeAI et/ou ses concédants de licence sont et demeurent propriétaires de tous les droits, titres et intérêts relatifs au Service, y compris mais sans s'y limiter, les logiciels, les algorithmes, l'interface utilisateur, les marques, les logos, les éléments graphiques et autres éléments distinctifs. Aucune disposition des présentes CGU ne saurait être interprétée comme conférant à l'Utilisateur un quelconque droit de propriété sur ces composants.\n\n7.2 Licence limitée : SEOForgeAI accorde à l'Utilisateur, pendant la durée de son abonnement ou dans la limite des Tokens disponibles, une licence non exclusive, non transférable, non sous-licenciable et révocable d'accès et d'utilisation du Service conformément aux présentes CGU.\n\n7.3 Propriété du Contenu généré : Sous réserve du paiement des Tokens correspondants, l'Utilisateur devient propriétaire du Contenu généré via le Service et peut l'utiliser sans restriction de temps ni de territoire, sous réserve du respect des droits des tiers. L'Utilisateur est libre de le modifier, de le distribuer, de le publier et de l'exploiter commercialement sans nécessiter d'autorisation supplémentaire d'adaptation et d'exploitation. Toutefois, SEOForgeAI conserve le droit d'utiliser de manière anonymisée les données relatives aux requêtes et aux Contenus générés afin d'améliorer ses algorithmes et la qualité du Service.\n\n7.4 Feedback et suggestions : Si l'Utilisateur soumet des commentaires, suggestions ou autres retours concernant le Service (« Feedback »), il accorde à SEOForgeAI une licence mondiale, perpétuelle, irrévocable, transférable, sous-licenciable, libre de redevance et non exclusive pour utiliser, reproduire, modifier, créer des œuvres dérivées, distribuer et exploiter ce Feedback de quelque manière que ce soit et à toute fin, sans contrepartie ni restriction d'aucune sorte."
    },
    {
      title: "8. Garanties et responsabilité",
      text: "8.1 Absence de garantie : Le Service est fourni « tel quel » et « selon disponibilité », sans garantie d'aucune sorte, expresse ou implicite. SEOForgeAI ne garantit pas que le Service sera ininterrompu, sécurisé, exempt d'erreurs ou de virus, ni que les défauts seront corrigés. SEOForgeAI ne garantit pas non plus que le Contenu généré répondra aux attentes ou aux besoins spécifiques de l'Utilisateur, ni qu'il sera exact, complet, à jour, légal ou de qualité satisfaisante.\n\n8.2 Limitation de responsabilité : Dans toute la mesure permise par la loi applicable, SEOForgeAI décline toute responsabilité pour tout dommage direct, indirect, accessoire, spécial, consécutif ou punitif, y compris mais sans s'y limiter, les pertes de profits, de données, d'opportunités commerciales, de réputation ou autres pertes intangibles, résultant de : (a) l'utilisation ou l'impossibilité d'utiliser le Service ; (b) tout Contenu généré via le Service ; (c) toute conduite ou tout contenu d'un tiers sur le Service ; (d) tout accès non autorisé, utilisation ou altération de vos transmissions ou contenus.\n\n8.3 Plafond de responsabilité : Nonobstant toute disposition contraire dans les présentes CGU et quelle que soit la cause de l'action ou la théorie de cause, la responsabilité globale de SEOForgeAI envers l'Utilisateur pour toutes réclamations liées au Service est limitée au montant effectivement payé par l'Utilisateur à SEOForgeAI au cours des douze (12) mois précédant l'événement donnant lieu à responsabilité.\n\n8.4 Indemnisation par l'Utilisateur : L'Utilisateur accepte de défendre, indemniser et dégager de toute responsabilité SEOForgeAI, ses dirigeants, administrateurs, employés et agents contre toute réclamation, dommage, obligation, perte, responsabilité, coût ou dette, et dépense (y compris, mais sans s'y limiter, les honoraires d'avocat) résultant de : (a) son utilisation du Service ; (b) sa violation des présentes CGU ; (c) sa violation des droits d'un tiers, y compris, mais sans s'y limiter, les droits de propriété intellectuelle ; ou (d) tout Contenu généré ou publié par lui."
    },
    {
      title: "9. Protection des données",
      text: "9.1 Traitement des données personnelles : SEOForgeAI collecte et traite les données personnelles des Utilisateurs conformément à sa Politique de Confidentialité. Cette politique détaille les catégories de données collectées, les finalités du traitement, les destinataires des données, les mesures de sécurité mises en œuvre, ainsi que les droits dont disposent les Utilisateurs et les modalités d'exercice de ces droits.\n\n9.2 Sous-traitants : SEOForgeAI peut faire appel à des sous-traitants pour l'exécution de certaines prestations nécessaires au fonctionnement du Service. Ces sous-traitants sont soumis à des obligations strictes de confidentialité et de sécurité concernant les données personnelles qu'ils pourraient être amenés à traiter.\n\n9.3 Transferts internationaux : Certaines données personnelles peuvent être transférées vers des serveurs ou des sous-traitants situés hors de l'Union Européenne. Dans ce cas, SEOForgeAI s'assure que ces transferts sont effectués vers des pays offrant un niveau de protection adéquat ou sont encadrés par des garanties appropriées conformément au Règlement Général sur la Protection des Données (RGPD).\n\n9.4 Confidentialité des contenus : SEOForgeAI s'engage à préserver la confidentialité des Contenus générés par les Utilisateurs et à ne pas les divulguer à des tiers sans autorisation, sauf obligation légale ou judiciaire. Toutefois, l'Utilisateur reconnaît que SEOForgeAI peut utiliser de manière anonymisée les données relatives aux requêtes et aux Contenus générés afin d'améliorer ses algorithmes et la qualité du Service."
    },
    {
      title: "10. Modification des CGU",
      text: "10.1 Droit de modification : SEOForgeAI se réserve le droit, à sa seule discrétion, de modifier, compléter ou remplacer tout ou partie des présentes CGU à tout moment. Les modifications peuvent être effectuées pour des raisons légales, pour refléter des changements dans le Service ou pour toute autre raison jugée nécessaire par SEOForgeAI.\n\n10.2 Notification des modifications : SEOForgeAI notifiera les Utilisateurs des modifications substantielles apportées aux CGU par email et/ou par un avis visible sur le Service. Pour les modifications mineures, SEOForgeAI pourra se contenter de mettre à jour la date de « dernière mise à jour » figurant en tête des CGU.\n\n10.3 Entrée en vigueur : Les modifications des CGU entrent en vigueur dès leur publication sur le Service, sauf indication contraire. En continuant à utiliser le Service après la publication des modifications, l'Utilisateur accepte d'être lié par les CGU modifiées.\n\n10.4 Droit d'opposition : Si l'Utilisateur n'accepte pas les CGU modifiées, il doit cesser d'utiliser le Service et supprimer son compte. L'utilisation continue du Service après l'entrée en vigueur des modifications vaut acceptation de ces modifications."
    },
    {
      title: "11. Dispositions diverses",
      text: "11.1 Intégralité de l'accord : Les présentes CGU, ainsi que la Politique de Confidentialité et la Politique de Remboursement, constituent l'intégralité de l'accord entre l'Utilisateur et SEOForgeAI concernant l'utilisation du Service et remplacent tous les accords antérieurs ou contemporains, écrits ou oraux, relatifs à l'objet des présentes.\n\n11.2 Divisibilité : Si une disposition des présentes CGU est jugée illégale, nulle ou inapplicable pour quelque raison que ce soit, cette disposition sera limitée ou éliminée des présentes CGU dans la mesure minimale nécessaire, et les autres dispositions resteront pleinement en vigueur.\n\n11.3 Renonciation : Le fait pour SEOForgeAI de ne pas exercer ou faire valoir un droit ou une disposition des présentes CGU ne constitue pas une renonciation à ce droit ou à cette disposition. Aucune renonciation par SEOForgeAI à une quelconque obligation de l'Utilisateur en vertu des présentes CGU ne sera considérée comme une renonciation continue ou une renonciation à toute autre obligation.\n\n11.4 Cession : L'Utilisateur ne peut céder ou transférer les présentes CGU, en tout ou en partie, sans le consentement écrit préalable de SEOForgeAI. SEOForgeAI peut céder ou transférer les présentes CGU, en tout ou en partie, sans restriction et sans notification préalable à l'Utilisateur.\n\n11.5 Notifications : Toutes les notifications requises ou autorisées en vertu des présentes CGU seront adressées par email à l'adresse électronique fournie par l'Utilisateur lors de son inscription ou à l'adresse contact@seoforgeai.com pour les notifications destinées à SEOForgeAI.\n\n11.6 Survie : Les dispositions des présentes CGU qui, par leur nature, devraient survivre à la résiliation ou à l'expiration des CGU, survivront à une telle résiliation ou expiration, y compris, mais sans s'y limiter, les dispositions relatives à la propriété intellectuelle, aux garanties, à la limitation de responsabilité et à l'indemnisation."
    },
    {
      title: "12. Droit applicable et juridiction compétente",
      text: "12.1 Droit applicable : Les présentes CGU sont régies par le droit français.\n\n12.2 Règlement amiable des litiges : En cas de litige, l'Utilisateur s'adressera en priorité au service client de SEOForgeAI à l'adresse contact@seoforgeai.com afin de rechercher une solution amiable.\n\n12.3 Médiation : Conformément aux articles L. 611-1 et suivants du Code de la consommation, l'Utilisateur consommateur a le droit de recourir gratuitement à un médiateur de la consommation en vue de la résolution amiable d'un litige l'opposant à SEOForgeAI. SEOForgeAI propose le médiateur suivant :\n\nSARL DEVIGNY MEDIATION\nMédiateur de la consommation\n93/95 Rue du Général de Gaulle\n95320 SAINT-LEU-LA-FORÊT\nhttps://www.medicys.fr\n\n12.4 Juridiction compétente : À défaut de résolution amiable, le litige sera porté devant les tribunaux français compétents conformément aux règles de droit commun."
    },
    {
      title: "13. Contact",
      text: "Pour toute question concernant les présentes CGU ou le Service, l'Utilisateur peut contacter Addax Media aux coordonnées suivantes :\n\nAddax Media Ltd\nCompany Number: 16314045\nFlat 5, 9 Langley Road\nWatford, England, WD17 4PS\nEmail : contact@oneiricrafts.com\n\nLe service client est disponible du lundi au vendredi, de 9h à 18h (heure de Londres), hors jours fériés britanniques.\n\nDernière mise à jour des CGU : 25/09/2024"
    }
  ]
}; 