export const refundContent = {
  title: "Politique de Remboursement",
  lastUpdated: "25 mars 2024",
  content: [
    {
      title: "1. Tokens et achats à l'unité",
      text: "1.1 Caractère définitif des achats : Les tokens acquis sur la plateforme SeducIA, que ce soit via un abonnement ou à l'unité (« à la carte »), ne sont pas remboursables. Conformément au Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013, tout achat de tokens est considéré comme un contenu numérique dématérialisé dont l'exécution a commencé après accord préalable exprès du consommateur et pour lequel le droit de rétractation ne peut être exercé.\n\n1.2 Confirmation de l'utilisateur : En procédant à l'achat de tokens, l'utilisateur reconnaît expressément qu'il renonce à son droit de rétractation dès la mise à disposition des tokens sur son compte.\n\n1.3 Absence de garantie de résultat : SeducIA ne garantit aucun résultat spécifique quant à l'utilisation des tokens pour la génération de contenu. La qualité, la pertinence ou l'adéquation du contenu généré à vos besoins particuliers ne pourront justifier une demande de remboursement."
    },
    {
      title: "2. Abonnements",
      text: "2.1 Facturation récurrente : Les abonnements souscrits sur la plateforme SeducIA font l'objet d'une facturation récurrente selon la périodicité choisie lors de la souscription (mensuelle, trimestrielle ou annuelle). Le montant correspondant est automatiquement prélevé sur le moyen de paiement enregistré.\n\n2.2 Absence de remboursement prorata temporis : En cas de résiliation d'un abonnement en cours de période, aucun remboursement prorata temporis ne sera effectué pour la période restante. L'utilisateur conservera l'accès au service jusqu'à la fin de la période en cours.\n\n2.3 Non-renouvellement : La simple annulation de l'abonnement via l'interface utilisateur, au moins 24 heures avant la date de renouvellement, permet d'éviter toute facturation ultérieure sans qu'il soit nécessaire de contacter le service client."
    },
    {
      title: "3. Tokens inclus dans les abonnements",
      text: "3.1 Non-reportabilité : Les tokens inclus dans les abonnements sont alloués pour une période spécifique (mensuelle, trimestrielle ou annuelle). Les tokens non utilisés durant cette période ne sont pas reportés sur la période suivante.\n\n3.2 Non-remboursabilité : Les tokens inclus dans les abonnements et non utilisés à la fin de la période concernée ne peuvent faire l'objet d'un remboursement, d'un avoir ou d'une compensation d'aucune sorte.\n\n3.3 Résiliation : En cas de résiliation de l'abonnement, les tokens non utilisés restent disponibles jusqu'à la fin de la période en cours, puis expirent automatiquement."
    },
    {
      title: "4. Erreurs de facturation",
      text: "4.1 Procédure de réclamation : En cas d'erreur de facturation (double facturation, montant incorrect), l'utilisateur doit signaler cette erreur dans les plus brefs délais et au plus tard dans les 30 jours suivant la date de la transaction litigieuse, par email à l'adresse support@seduc-ia.com ou via le formulaire de contact dédié accessible dans votre espace client.\n\n4.2 Justificatifs requis : Toute réclamation relative à une erreur de facturation devra être accompagnée des justificatifs nécessaires (facture, relevé bancaire, etc.) permettant de démontrer l'erreur ou l'anomalie alléguée.\n\n4.3 Délai de traitement : SeducIA s'engage à traiter les réclamations dans un délai maximal de 14 jours ouvrés à compter de la réception de la réclamation complète.\n\n4.4 Modalités de remboursement : Après confirmation de l'erreur de facturation, SeducIA procédera, à sa discrétion, soit au remboursement du montant indûment facturé sur le moyen de paiement initialement utilisé, soit à l'octroi d'un crédit de tokens équivalent sur votre compte."
    },
    {
      title: "5. Dysfonctionnements techniques",
      text: "5.1 Interruption significative du service : En cas de dysfonctionnement technique majeur imputable à SeducIA et rendant impossible l'utilisation du service pendant une durée continue supérieure à vingt-quatre (24) heures, une compensation pourra être accordée sous forme de tokens supplémentaires.\n\n5.2 Perte de tokens : En cas de perte avérée de tokens résultant d'un dysfonctionnement technique de la plateforme, SeducIA s'engage à restaurer les tokens perdus après vérification et confirmation de l'incident.\n\n5.3 Exclusions : Aucune compensation ne sera due en cas d'interruption du service résultant d'opérations de maintenance programmées et annoncées à l'avance, d'un cas de force majeure, de l'action d'un tiers, ou d'un problème lié à la connexion internet ou à l'équipement de l'utilisateur."
    },
    {
      title: "6. Fermeture de compte",
      text: "6.1 Fermeture volontaire : En cas de fermeture volontaire du compte par l'utilisateur, aucun remboursement ne sera effectué pour les tokens non utilisés ou les périodes d'abonnement restantes.\n\n6.2 Fermeture pour violation des conditions : En cas de fermeture du compte par SeducIA suite à une violation des Conditions Générales d'Utilisation, SeducIA se réserve le droit de supprimer l'intégralité des tokens restants sans compensation d'aucune sorte.\n\n6.3 Délai de grâce : Avant toute fermeture volontaire de compte, un message d'avertissement rappellera à l'utilisateur qu'il perdra définitivement l'accès à ses tokens non utilisés. Un délai de réflexion de sept (7) jours sera accordé avant la fermeture définitive.\n\n6.4 Réactivation de compte : En cas de réactivation du compte dans les trente (30) jours suivant la fermeture, SeducIA pourra, à sa seule discrétion et sans y être tenue, restaurer tout ou partie des tokens perdus."
    },
    {
      title: "7. Exceptions au principe de non-remboursement",
      text: "7.1 Droit de rétractation légal pour les résidents du Royaume-Uni et de l'UE : Si vous êtes un consommateur résidant au Royaume-Uni ou dans l'Union européenne et que vous n'avez pas encore utilisé de tokens ni accédé au service, vous bénéficiez d'un droit de rétractation légal de 14 jours à compter de la date d'achat. Ce droit ne s'applique pas dès lors que vous avez commencé à utiliser le service, conformément au Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 au Royaume-Uni ou à la législation équivalente dans l'UE.\n\n7.2 Exercice du droit de rétractation : Le droit de rétractation doit être exercé dans un délai de 14 jours suivant la conclusion du contrat, par le biais d'une déclaration claire et sans équivoque par email à l'adresse support@seduc-ia.com en précisant votre identifiant utilisateur et la référence de la transaction concernée.\n\n7.3 Délai de remboursement : En cas d'exercice valable du droit de rétractation, le remboursement sera effectué dans un délai de 14 jours à compter de la notification de votre décision de vous rétracter, en utilisant le même moyen de paiement que celui utilisé pour la transaction initiale.\n\n7.4 Délai de réflexion contractuel : Nonobstant ce qui précède, SeducIA accorde contractuellement un délai de réflexion de vingt-quatre (24) heures à compter de l'achat pour les nouveaux utilisateurs effectuant leur premier achat de tokens, à condition qu'aucun token n'ait été utilisé. Pour bénéficier de ce délai de réflexion, vous devez en faire la demande sans équivoque par email à l'adresse support@seduc-ia.com en précisant votre identifiant utilisateur et la référence de la transaction concernée."
    },
    {
      title: "8. Pouvoir discrétionnaire",
      text: "8.1 Pouvoir discrétionnaire : Dans des circonstances exceptionnelles dûment justifiées et documentées, SeducIA se réserve le droit, à sa seule et entière discrétion, d'examiner des demandes de remboursement particulières ne relevant pas des cas précédemment énumérés.\n\n8.2 Non-création de précédent : L'acceptation par SeducIA d'effectuer un remboursement dans une situation spécifique ne saurait créer un précédent ni constituer une renonciation à l'application stricte de la présente politique de remboursement pour d'autres situations similaires à l'avenir."
    },
    {
      title: "9. Procédure de réclamation",
      text: "9.1 Contact : Pour toute question concernant les remboursements et votre abonnement, veuillez contacter notre service client via le formulaire de contact disponible sur le Site, par téléphone au (850) 783-4170 ou par email à l'adresse support@seduc-ia.com.\n\n9.2 Délai de forclusion : Toute réclamation doit être formulée dans un délai de trente (30) jours calendaires à compter de la date de la transaction contestée ou du fait générateur de la réclamation. Passé ce délai, aucune réclamation ne sera recevable.\n\n9.3 Informations requises : Toute réclamation doit inclure les informations suivantes pour être traitée : votre identifiant utilisateur, la date et le montant de la transaction concernée, la nature précise de votre réclamation et les justificatifs pertinents.\n\n9.4 Délai de réponse : SeducIA s'engage à accuser réception de toute réclamation dans un délai de 2 jours ouvrés et à y apporter une réponse circonstanciée dans un délai maximal de 30 jours calendaires.\n\n9.5 Médiation : En cas d'échec de la réclamation auprès de notre service client ou en l'absence de réponse dans un délai de deux mois, vous pouvez recourir gratuitement au service de médiation proposé par SeducIA. Le médiateur de la consommation ainsi désigné est Médiation-Net.\n\n9.6 Conditions de recevabilité en médiation : Pour être recevable, votre demande de médiation doit être introduite dans un délai d'un an à compter de votre réclamation écrite auprès de nos services, et le litige ne doit pas avoir été précédemment examiné ou être en cours d'examen par un autre médiateur ou par un tribunal."
    },
    {
      title: "10. Modifications de la politique de remboursement",
      text: "10.1 Droit de modification : SeducIA se réserve le droit de modifier, compléter ou remplacer tout ou partie de la présente politique de remboursement à tout moment, notamment pour l'adapter aux évolutions législatives et réglementaires.\n\n10.2 Notification : Les modifications substantielles de la politique de remboursement seront notifiées aux utilisateurs par email et/ou par un avis visible sur le Site au moins 30 jours avant leur entrée en vigueur.\n\n10.3 Application : La politique de remboursement applicable est celle en vigueur à la date de la transaction concernée.\n\nDernière mise à jour : 25/03/2024"
    }
  ]
}; 