'use client';

import { Metadata } from 'next';
import { LegalShell } from '@/app/components/legal/legal-shell';

export const metadata: Metadata = {
  title: 'Conditions générales d\'utilisation',
  description: 'Conditions générales d\'utilisation de SeducIA',
};

export const termsContent = {
  title: "Conditions Générales d'Utilisation",
  lastUpdated: "1er mars 2024",
  content: [
    {
      title: "1. Introduction",
      text: "Bienvenue sur SeducIA, accessible via le site internet seduc-ia.com (ci-après dénommé « le Site »). Le Site et les services associés (ci-après dénommés collectivement « le Service ») sont édités par la société Jastro LIMITED (ci-après dénommée « Jastro LIMITED »), société à responsabilité limitée, enregistrée au Royaume-Uni sous le numéro d'entreprise 836841.\n\nLes présentes Conditions Générales d'Utilisation (ci-après dénommées « CGU ») régissent l'utilisation du Service. Elles constituent un contrat juridiquement contraignant entre vous (ci-après dénommé « l'Utilisateur » ou « vous ») et Jastro LIMITED.\n\nEn accédant au Site et/ou en utilisant le Service, vous reconnaissez avoir lu, compris et accepté sans réserve les présentes CGU. Si vous n'acceptez pas ces CGU, vous ne devez pas utiliser le Service."
    },
    {
      title: "2. Description du Service",
      text: "2.1 Nature du Service : SeducIA est un service de coach virtuel de séduction qui utilise l'intelligence artificielle pour fournir des conseils personnalisés et des simulations de conversations dans le contexte des relations interpersonnelles et de la séduction. Le Service permet notamment :\n- D'obtenir des conseils personnalisés en matière de séduction\n- De simuler des conversations pour pratiquer les approches\n- D'accéder à des ressources et stratégies pour améliorer ses compétences relationnelles\n\n2.2 Évolution du Service : Jastro LIMITED se réserve le droit de faire évoluer, de modifier ou d'interrompre, temporairement ou définitivement, tout ou partie du Service, avec ou sans préavis. Jastro LIMITED ne pourra être tenue responsable des conséquences de telles modifications pour l'Utilisateur."
    },
    {
      title: "3. Accès au Service",
      text: "3.1 Conditions d'accès : Pour accéder au Service, vous devez :\n- Être âgé d'au moins 18 ans\n- Créer un compte utilisateur en fournissant les informations requises\n- Disposer d'un appareil compatible avec une connexion internet fonctionnelle\n- Accepter les présentes CGU\n\n3.2 Compte utilisateur : La création d'un compte utilisateur est nécessaire pour accéder à l'ensemble des fonctionnalités du Service. Vous êtes responsable de la confidentialité de vos identifiants de connexion et de toutes les activités effectuées depuis votre compte. Vous vous engagez à :\n- Fournir des informations exactes, complètes et à jour lors de la création de votre compte\n- Mettre à jour ces informations si nécessaire\n- Ne pas partager vos identifiants de connexion avec des tiers\n- Notifier immédiatement Jastro LIMITED de toute utilisation non autorisée de votre compte ou de toute autre violation de sécurité\n\n3.3 Suspension ou résiliation d'accès : Jastro LIMITED se réserve le droit, à sa seule discrétion, de suspendre ou de résilier votre accès au Service, en tout ou partie, temporairement ou définitivement, notamment en cas de :\n- Violation des présentes CGU\n- Utilisation frauduleuse ou abusive du Service\n- Non-paiement des sommes dues\n- Demandes des autorités judiciaires ou administratives\n- Maintenance technique ou mise à jour du Service"
    },
    {
      title: "4. Utilisation du Service",
      text: "4.1 Utilisation conforme : Vous vous engagez à utiliser le Service conformément aux présentes CGU, aux lois applicables et aux bonnes mœurs. Il vous est notamment interdit de :\n- Utiliser le Service à des fins illégales, frauduleuses, malveillantes ou discriminatoires\n- Tenter d'obtenir un accès non autorisé au Service, aux systèmes ou réseaux connectés\n- Introduire des virus, chevaux de Troie, vers, bombes logiques ou autre matériel malveillant ou technologiquement nuisible\n- Perturber, désactiver, surcharger ou détériorer le fonctionnement du Service\n- Collecter ou récupérer des données personnelles concernant d'autres utilisateurs\n- Utiliser le Service pour harceler, intimider, ou promouvoir la violence à l'égard d'autrui\n- Solliciter des conseils ou créer des simulations contraires aux lois en vigueur ou encourageant des comportements illégaux, dangereux ou contraires à l'éthique\n\n4.2 Contenus générés par l'Utilisateur : Dans le cadre de l'utilisation du Service, vous pouvez être amené à soumettre des textes, questions ou autres contenus (ci-après dénommés « Contenus Utilisateur »). En soumettant des Contenus Utilisateur via le Service, vous :\n- Garantissez que vous êtes propriétaire de ces contenus ou que vous disposez des droits nécessaires pour les soumettre\n- Accordez à Jastro LIMITED une licence mondiale, non exclusive, gratuite, transférable et pouvant faire l'objet d'une sous-licence, pour utiliser, reproduire, distribuer, modifier, adapter, créer des œuvres dérivées, afficher publiquement et exécuter ces Contenus Utilisateur dans le cadre de la fourniture et de l'amélioration du Service\n- Comprenez que vos Contenus Utilisateur pourront être utilisés pour entraîner les modèles d'intelligence artificielle sous-jacents au Service, de manière anonymisée\n\n4.3 Modération : Jastro LIMITED se réserve le droit, sans y être obligée, de surveiller, filtrer, modifier ou supprimer tout Contenu Utilisateur qui serait contraire aux présentes CGU ou aux lois applicables. Jastro LIMITED peut signaler aux autorités compétentes toute activité qui lui semblerait illégale."
    },
    {
      title: "5. Propriété intellectuelle",
      text: "5.1 Droits de Jastro LIMITED : Le Service, incluant sans limitation les textes, graphiques, images, logos, icônes de boutons, logiciels, noms commerciaux, marques, et tout autre élément, est protégé par les droits de propriété intellectuelle détenus par Jastro LIMITED ou ses concédants de licence. Ces éléments ne peuvent être copiés, imités ou utilisés, en tout ou partie, sans l'autorisation écrite préalable de Jastro LIMITED.\n\n5.2 Licence d'utilisation : Jastro LIMITED vous accorde, sous réserve du respect des présentes CGU, une licence limitée, non exclusive, non transférable et révocable pour accéder au Service et l'utiliser à des fins personnelles et non commerciales.\n\n5.3 Limitations : Il vous est interdit de :\n- Copier, modifier, créer des œuvres dérivées, désassembler, décompiler ou tenter de découvrir le code source du Service\n- Vendre, céder, concéder en sous-licence, transférer, distribuer ou louer l'accès au Service\n- Utiliser le Service pour développer un produit ou service concurrent\n- Utiliser des robots, spiders, ou autres moyens automatisés pour accéder au Service à quelque fin que ce soit\n- Contourner les mesures technologiques de protection mises en place par Jastro LIMITED"
    },
    {
      title: "6. Paiement et abonnements",
      text: "6.1 Services payants : Certaines fonctionnalités du Service sont payantes et nécessitent la souscription d'un abonnement ou l'achat de crédits/tokens. Les prix, modalités de paiement et conditions spécifiques sont indiqués sur le Site au moment de la souscription ou de l'achat.\n\n6.2 Abonnements : Si vous souscrivez un abonnement, celui-ci sera automatiquement renouvelé à la fin de chaque période, sauf résiliation de votre part avant la date de renouvellement. Vous pouvez annuler votre abonnement à tout moment depuis votre compte utilisateur ou en contactant le service client.\n\n6.3 Modification des tarifs : Jastro LIMITED se réserve le droit de modifier ses tarifs à tout moment. Toute modification de tarif sera notifiée aux Utilisateurs avant son entrée en vigueur et s'appliquera lors du prochain renouvellement d'abonnement.\n\n6.4 Facturation et remboursement : Les paiements sont dus en totalité à l'avance, dans la devise spécifiée lors de l'achat. Sauf disposition légale contraire ou indication spécifique dans les présentes CGU, tous les paiements sont non remboursables. Pour toute question concernant la facturation ou pour contester un prélèvement, veuillez contacter notre service client dans les 30 jours suivant la date de facturation concernée."
    },
    {
      title: "7. Limitations de responsabilité",
      text: "7.1 Fonctionnement du Service : Bien que Jastro LIMITED s'efforce de fournir un Service de qualité, le Service est fourni « tel quel » et « selon disponibilité », sans garantie d'aucune sorte, expresse ou implicite. Jastro LIMITED ne garantit pas que :\n- Le Service répondra parfaitement à vos besoins spécifiques\n- Le Service sera ininterrompu, opportun, sûr ou sans erreur\n- Les résultats obtenus en utilisant le Service seront exacts ou fiables\n- Les défauts éventuels seront corrigés\n\n7.2 Conseils et informations : Les conseils, recommandations et simulations fournis par le Service :\n- Sont générés par des systèmes d'intelligence artificielle et peuvent ne pas être adaptés à toutes les situations\n- Ne constituent pas un avis professionnel (notamment médical, psychologique, juridique ou financier)\n- Ne garantissent pas des résultats dans vos interactions sociales ou amoureuses\n\nVous êtes seul responsable de vos actions et décisions basées sur les informations fournies par le Service.\n\n7.3 Limitation de responsabilité : Dans toute la mesure permise par la loi applicable, Jastro LIMITED ne pourra être tenue responsable envers vous ou envers des tiers pour :\n- Les dommages directs, indirects, accessoires, spéciaux, consécutifs ou exemplaires\n- La perte de profits, de revenus, de données, d'opportunités commerciales ou d'économies anticipées\n- Les dommages à la réputation ou à l'image\n- Les dommages résultant d'une interruption de service, d'un virus ou d'un autre problème technologique\n- Toute autre perte résultant de l'utilisation ou de l'impossibilité d'utiliser le Service\n\nCette limitation s'applique que la responsabilité soit fondée sur un contrat, un délit (y compris la négligence), ou toute autre base légale, même si Jastro LIMITED a été informée de la possibilité de tels dommages.\n\n7.4 Plafond de responsabilité : Dans tous les cas, la responsabilité totale de Jastro LIMITED envers vous pour toutes les réclamations liées au Service ne dépassera pas le montant que vous avez payé à Jastro LIMITED pour le Service au cours des douze (12) derniers mois, ou 100 € si vous n'avez rien payé.\n\n7.5 Exceptions : Certaines juridictions n'autorisant pas l'exclusion de certaines garanties ou la limitation de responsabilité pour certains types de dommages, certaines des limitations ci-dessus peuvent ne pas s'appliquer à vous. Dans ces juridictions, la responsabilité de Jastro LIMITED sera limitée dans toute la mesure permise par la loi applicable."
    },
    {
      title: "8. Protection des données personnelles",
      text: "8.1 Politique de confidentialité : Le traitement de vos données personnelles est soumis à notre Politique de confidentialité, accessible à l'adresse suivante : https://seduc-ia.com/privacy. Cette politique fait partie intégrante des présentes CGU. En acceptant ces CGU, vous reconnaissez avoir pris connaissance de notre Politique de confidentialité et consentez aux traitements de données qui y sont décrits.\n\n8.2 Données traitées : Dans le cadre du Service, Jastro LIMITED est amenée à collecter et traiter différentes catégories de données personnelles vous concernant, notamment :\n- Données d'identification (nom, prénom, adresse email, etc.)\n- Données de connexion et d'utilisation du Service\n- Informations de paiement\n- Contenus soumis lors de l'utilisation du Service\n- Préférences et centres d'intérêt communiqués pour personnaliser l'expérience\n\n8.3 Sécurité : Jastro LIMITED met en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos données personnelles contre la perte, l'accès non autorisé, la divulgation, l'altération ou la destruction. Toutefois, aucune méthode de transmission sur Internet ou de stockage électronique n'est totalement sécurisée, et Jastro LIMITED ne peut garantir une sécurité absolue.\n\n8.4 Droits des personnes concernées : Conformément aux réglementations applicables en matière de protection des données personnelles, vous disposez de droits sur vos données, incluant notamment les droits d'accès, de rectification, d'effacement, d'opposition, de limitation du traitement et, le cas échéant, de portabilité. Pour exercer ces droits, veuillez contacter notre Délégué à la Protection des Données à l'adresse suivante : support@seduc-ia.com."
    },
    {
      title: "9. Résiliation",
      text: "9.1 Résiliation par l'Utilisateur : Vous pouvez cesser d'utiliser le Service à tout moment et résilier votre compte en suivant la procédure indiquée dans les paramètres de votre compte ou en contactant notre service client. La résiliation de votre compte n'entraînera pas le remboursement des sommes déjà payées.\n\n9.2 Résiliation par Jastro LIMITED : Jastro LIMITED se réserve le droit de suspendre ou de résilier votre accès au Service, à tout moment et pour quelque raison que ce soit, notamment en cas de violation des présentes CGU. Jastro LIMITED fera des efforts raisonnables pour vous informer de cette résiliation.\n\n9.3 Effets de la résiliation : En cas de résiliation, pour quelque raison que ce soit :\n- Votre accès au Service sera immédiatement désactivé\n- Vous n'aurez plus accès aux Contenus Utilisateur que vous avez soumis via le Service\n- Les sections des présentes CGU qui, par leur nature, devraient survivre à la résiliation, resteront en vigueur, y compris, sans limitation, les dispositions relatives à la propriété intellectuelle, aux limitations de responsabilité et au règlement des différends\n\n9.4 Conservation des données : Après la résiliation de votre compte, Jastro LIMITED pourra conserver certaines de vos données pendant une période limitée, conformément à ses obligations légales et à sa Politique de confidentialité."
    },
    {
      title: "10. Dispositions diverses",
      text: "10.1 Modification des CGU : Jastro LIMITED se réserve le droit de modifier les présentes CGU à tout moment. Les modifications prendront effet dès leur publication sur le Site. Jastro LIMITED s'efforcera de vous informer de toute modification substantielle par email ou via une notification sur le Site. Votre utilisation continue du Service après la publication des CGU modifiées signifie que vous acceptez ces modifications.\n\n10.2 Cession : Jastro LIMITED peut céder ou transférer tout ou partie de ses droits et obligations au titre des présentes CGU sans votre consentement préalable. Vous ne pouvez pas céder ou transférer vos droits ou obligations au titre des présentes CGU sans le consentement écrit préalable de Jastro LIMITED.\n\n10.3 Intégralité de l'accord : Les présentes CGU, ainsi que la Politique de confidentialité et les éventuelles conditions particulières référencées, constituent l'intégralité de l'accord entre vous et Jastro LIMITED concernant votre utilisation du Service, et remplacent tous les accords antérieurs entre vous et Jastro LIMITED relatifs au Service.\n\n10.4 Renonciation et divisibilité : Le fait pour Jastro LIMITED de ne pas exercer ou de tarder à exercer un droit ou un recours prévu par les présentes CGU ne constitue pas une renonciation à ce droit ou recours. Si une disposition des présentes CGU est jugée invalide, illégale ou inapplicable, les autres dispositions resteront pleinement en vigueur.\n\n10.5 Force majeure : Jastro LIMITED ne sera pas responsable de tout manquement ou retard dans l'exécution de ses obligations résultant de causes indépendantes de sa volonté raisonnable, y compris, mais sans s'y limiter, les catastrophes naturelles, les pandémies, les guerres, le terrorisme, les émeutes, les embargos, les actes des autorités civiles ou militaires, les incendies, les inondations, les accidents, les grèves, ou les pénuries de moyens de transport, de carburant, d'énergie, de main-d'œuvre ou de matériaux.\n\n10.6 Loi applicable et juridiction : Les présentes CGU sont régies par le droit britannique. Tout litige relatif à l'interprétation, l'exécution ou la validité des présentes CGU sera soumis à la compétence exclusive des tribunaux britanniques, sauf disposition légale contraire.\n\n10.7 Contact : Pour toute question concernant les présentes CGU ou le Service, l'Utilisateur peut contacter Jastro Limited aux coordonnées suivantes :\n\nJastro Limited\nSuite 10 12 Durie Street\nLeven, Fife\nUnited Kingdom, KY8 4HE\nEmail : support@seduc-ia.com\nTéléphone : (850) 783-4170\n\nLe service client est disponible du lundi au vendredi, de 9h à 18h (heure de Londres), hors jours fériés.\n\nDernière mise à jour des CGU : 25/03/2024"
    }
  ]
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Conditions Générales d'Utilisation"
      lastUpdated="Dernière mise à jour: 1 Juin 2023"
    >
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4">1. Introduction</h2>
        <p className="mb-4">
          Les présentes Conditions Générales d'Utilisation (ci-après "CGU") régissent l'utilisation du service SeducIA (ci-après le "Service") accessible via le site web seduc-ia.com (ci-après le "Site"), édité par Jastro LIMITED, société enregistrée au Royaume-Uni sous le numéro 836841, dont le siège social est situé Suite 10 12 Durie Street, Leven, Fife, United Kingdom, KY8 4HE.
        </p>
        <p className="mb-4">
          En utilisant le Service, vous acceptez d'être lié par les présentes CGU. Si vous n'acceptez pas ces CGU, vous ne devez pas utiliser le Service.
        </p>
      </section>

      {/* ... existing code ... */}
    </LegalShell>
  );
} 