export const privacyContent = {
  title: "Politique de confidentialité",
  content: [
    {
      title: "Introduction",
      text: "La présente Politique de confidentialité décrit comment Hirola Media Ltd (ci-après « nous », « notre », « nos ») collecte, utilise et partage vos informations personnelles lorsque vous utilisez notre service ContentForge AI (« le Service »), un générateur d'articles SEO et de descriptions produits utilisant l'intelligence artificielle pour créer du contenu optimisé pour les moteurs de recherche.\n\nEn utilisant le Service, vous consentez à la collecte et à l'utilisation d'informations conformément à la présente politique. Cette Politique de confidentialité a été rédigée en conformité avec le UK GDPR, le Data Protection Act 2018 et les autres lois applicables en matière de protection des données."
    },
    {
      title: "1. Introduction et responsable de traitement",
      text: `La présente Politique de confidentialité décrit comment Hirola Media Ltd, société enregistrée en Angleterre sous le numéro 16312592, dont le siège social est situé au 137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ (ci-après "Hirola Media", "nous" ou "notre"), en sa qualité de responsable de traitement, collecte, utilise et protège vos données à caractère personnel lorsque vous utilisez le site ContentForge AI et ses services (ci-après le "Service").\n\nNous nous engageons à protéger votre vie privée et à traiter vos données personnelles conformément au UK General Data Protection Regulation (UK GDPR), au Data Protection Act 2018 (DPA) et aux autres lois applicables en matière de protection des données.\n\nEn utilisant notre Service, vous consentez à la collecte et au traitement de vos données personnelles conformément à la présente Politique de confidentialité. Si vous n'acceptez pas cette politique, nous vous prions de ne pas utiliser notre Service.`
    },
    {
      title: "2. Catégories de données à caractère personnel collectées",
      text: "2.1 Données d'identification : Nous collectons les informations nécessaires à la création et à la gestion de votre compte utilisateur, notamment vos nom, prénom, adresse email, et le cas échéant, votre fonction et le nom de votre entreprise si vous agissez pour le compte d'une personne morale.\n\n2.2 Données de facturation et de paiement : Pour traiter vos paiements et gérer la facturation, nous collectons votre adresse postale, vos coordonnées bancaires (limitées aux informations transmises par nos prestataires de paiement), votre historique d'achat et vos préférences de facturation.\n\n2.3 Données d'utilisation du Service : Nous recueillons des informations relatives à votre utilisation du Service, notamment l'historique des contenus générés, les requêtes effectuées, la consommation de tokens, les fonctionnalités utilisées, la fréquence et la durée d'utilisation.\n\n2.4 Données de connexion et techniques : Nous collectons automatiquement certaines informations techniques lors de votre utilisation du Service, telles que votre adresse IP, l'identifiant de votre appareil, le type et la version de votre navigateur, votre système d'exploitation, les données de journalisation, les horodatages de connexion, et les pages consultées.\n\n2.5 Contenus soumis : Les informations que vous nous soumettez volontairement pour générer du contenu, telles que les mots-clés, les descriptions de produits, les instructions spécifiques ou tout autre contenu que vous importez ou saisissez sur notre plateforme.\n\n2.6 Données de communication : Les informations échangées lorsque vous communiquez avec notre service client, y compris l'historique des conversations, les emails et les demandes d'assistance."
    },
    {
      title: "3. Finalités et bases juridiques du traitement",
      text: "Nous traitons vos données à caractère personnel pour les finalités suivantes, chacune étant associée à une base juridique spécifique :\n\n3.1 Fourniture et gestion du Service (base juridique : exécution du contrat) :\n- Création et gestion de votre compte utilisateur\n- Fourniture des fonctionnalités de génération de contenu\n- Gestion de votre abonnement et de vos tokens\n- Traitement de vos paiements et facturation\n- Réponse à vos demandes d'assistance et support technique\n\n3.2 Amélioration et personnalisation du Service (base juridique : intérêt légitime) :\n- Analyse de l'utilisation du Service pour en améliorer les fonctionnalités\n- Personnalisation de votre expérience utilisateur\n- Développement et test de nouvelles fonctionnalités\n- Résolution des problèmes techniques et optimisation des performances\n\n3.3 Communication et marketing (base juridique : intérêt légitime et, le cas échéant, consentement) :\n- Envoi d'informations relatives au Service (mises à jour, modifications, alertes de sécurité)\n- Envoi de communications commerciales concernant nos offres et promotions (sous réserve de votre consentement lorsque la loi l'exige)\n- Réalisation d'enquêtes de satisfaction\n\n3.4 Sécurité et prévention de la fraude (base juridique : intérêt légitime et obligation légale) :\n- Protection contre les activités frauduleuses ou illégales\n- Sécurisation de notre Service et de nos systèmes d'information\n- Vérification de l'identité des utilisateurs\n\n3.5 Respect des obligations légales et réglementaires (base juridique : obligation légale) :\n- Conformité avec les obligations comptables et fiscales\n- Réponse aux demandes des autorités compétentes\n- Conservation des données requises par la loi\n\nLorsque nous nous fondons sur notre intérêt légitime, nous nous assurons que le traitement est nécessaire et que vos intérêts, droits et libertés fondamentaux ne prévalent pas sur nos intérêts commerciaux légitimes."
    },
    {
      title: "4. Durée de conservation des données",
      text: "Nous conservons vos données à caractère personnel pendant une durée n'excédant pas celle nécessaire au regard des finalités pour lesquelles elles sont traitées, conformément aux exigences légales et réglementaires applicables :\n\n4.1 Données relatives au compte utilisateur : Ces données sont conservées pendant toute la durée de votre relation contractuelle avec Hirola Media, puis archivées pendant une durée de trois (3) ans à compter de votre dernière activité ou de la résiliation de votre compte, à des fins de prospection commerciale.\n\n4.2 Données de facturation et documents comptables : Conformément aux obligations légales en matière comptable et fiscale, ces données sont conservées pendant une durée de dix (10) ans à compter de la clôture de l'exercice comptable concerné.\n\n4.3 Données d'utilisation et contenus générés : Ces données sont conservées pendant la durée de votre abonnement actif, puis pendant une période maximale de six (6) mois après la résiliation de votre compte, afin de vous permettre de récupérer vos contenus en cas de réactivation.\n\n4.4 Données de connexion et logs techniques : Ces données sont conservées pendant une durée maximale de douze (12) mois à compter de leur collecte, conformément aux dispositions légales applicables.\n\n4.5 Données relatives aux demandes d'exercice de droits : Les informations permettant de prouver l'exercice de vos droits (demandes et réponses) sont conservées pendant une durée de cinq (5) ans à compter de la réponse à votre demande.\n\nÀ l'issue de ces périodes, vos données à caractère personnel sont soit supprimées définitivement, soit anonymisées de manière irréversible à des fins statistiques."
    },
    {
      title: "5. Destinataires des données et transferts",
      text: "5.1 Destinataires internes : Au sein de notre organisation, l'accès à vos données à caractère personnel est strictement limité aux personnes ayant besoin d'y accéder dans le cadre de leurs fonctions, notamment les équipes chargées de la gestion des comptes clients, du support technique, de la facturation, du marketing (sous réserve de votre consentement lorsque la loi l'exige) et de la conformité légale.\n\n5.2 Sous-traitants et prestataires de services : Nous pouvons partager vos données avec des prestataires de services tiers agissant en qualité de sous-traitants au sens du UK GDPR, qui nous fournissent des services nécessaires au fonctionnement de notre plateforme, notamment :\n- Hébergement et infrastructure cloud (Amazon Web Services, Google Cloud Platform)\n- Traitement des paiements (Stripe, PayPal)\n- Service client et support technique (Zendesk, Intercom)\n- Analyse de l'utilisation du Service (Google Analytics, Mixpanel)\n- Communication par email (Sendgrid, Mailchimp)\nCes prestataires sont liés par des obligations contractuelles strictes de confidentialité et de sécurité, et ne peuvent utiliser vos données que conformément à nos instructions et pour les finalités spécifiées.\n\n5.3 Partenaires commerciaux : Dans le cadre de partenariats commerciaux spécifiques et avec votre consentement préalable lorsque la loi l'exige, nous pouvons partager certaines de vos données avec des partenaires sélectionnés.\n\n5.4 Autorités publiques et judiciaires : Nous pouvons être amenés à divulguer vos données aux autorités compétentes lorsque la loi l'exige, notamment en cas de réquisition judiciaire, d'ordonnance d'un tribunal ou de toute autre procédure légale.\n\n5.5 Transferts dans le cadre d'opérations commerciales : En cas de fusion, acquisition, restructuration, cession d'actifs ou procédure de faillite impliquant tout ou partie de notre activité, vos données peuvent être transférées comme faisant partie des actifs commerciaux. Vous serez informé par email et/ou par un avis bien visible sur notre Service de tout changement de propriétaire ou d'utilisation de vos données, ainsi que des choix dont vous disposez concernant vos données.\n\n5.6 Transferts internationaux : Certains de nos prestataires de services peuvent être situés en dehors du Royaume-Uni. Dans ce cas, nous nous assurons que ces transferts sont effectués vers des pays bénéficiant d'une décision d'adéquation du gouvernement britannique ou sont encadrés par des garanties appropriées telles que les clauses contractuelles types approuvées par le Secrétaire d'État britannique, ou tout autre mécanisme juridiquement valide conformément aux exigences du UK GDPR."
    },
    {
      title: "6. Mesures de sécurité",
      text: "Nous mettons en œuvre des mesures de sécurité techniques et organisationnelles appropriées afin de garantir un niveau de protection adéquat de vos données à caractère personnel et de prévenir tout accès non autorisé, altération, divulgation, perte ou destruction de celles-ci. Ces mesures comprennent notamment :\n\n6.1 Sécurité technique :\n- Chiffrement des données en transit (protocole HTTPS/TLS) et au repos (AES-256)\n- Authentification à deux facteurs (2FA) pour l'accès aux comptes administrateurs\n- Pare-feu et systèmes de détection d'intrusion\n- Surveillance continue des systèmes et journalisation des accès\n- Tests de pénétration et audits de sécurité réguliers\n- Mises à jour régulières des systèmes et correction des vulnérabilités\n\n6.2 Mesures organisationnelles :\n- Politique d'accès restrictif basée sur le principe du moindre privilège\n- Formation et sensibilisation régulières du personnel à la sécurité des données\n- Procédures formalisées en cas de violation de données\n- Engagement de confidentialité du personnel ayant accès aux données\n- Politique de gestion des incidents de sécurité\n\nEn cas de violation de données à caractère personnel susceptible d'engendrer un risque élevé pour vos droits et libertés, nous nous engageons à vous en informer dans les meilleurs délais, conformément aux obligations légales applicables."
    },
    {
      title: "7. Vos droits et leur exercice",
      text: `Conformément au UK GDPR et au Data Protection Act 2018, vous disposez des droits suivants concernant vos données personnelles :\n\n- Droit d'accès : Vous avez le droit d'obtenir confirmation que des données personnelles vous concernant sont traitées et d'en obtenir une copie.\n\n- Droit de rectification : Vous pouvez demander la correction de vos données personnelles si elles sont inexactes ou incomplètes.\n\n- Droit à l'effacement (« droit à l'oubli ») : Vous pouvez demander l'effacement de vos données personnelles dans certaines circonstances.\n\n- Droit à la limitation du traitement : Vous pouvez demander la limitation du traitement de vos données personnelles dans certaines circonstances.\n\n- Droit à la portabilité des données : Vous avez le droit de recevoir vos données personnelles dans un format structuré, couramment utilisé et lisible par machine, et de les transmettre à un autre responsable du traitement.\n\n- Droit d'opposition : Vous avez le droit de vous opposer au traitement de vos données personnelles dans certaines circonstances, notamment lorsqu'elles sont utilisées à des fins de marketing direct.\n\n- Droit de retirer votre consentement : Lorsque le traitement est fondé sur votre consentement, vous avez le droit de le retirer à tout moment.\n\n- Droit de ne pas faire l'objet d'une décision fondée exclusivement sur un traitement automatisé, y compris le profilage, produisant des effets juridiques vous concernant ou vous affectant de manière significative.\n\nPour exercer l'un de ces droits, veuillez nous contacter à l'adresse email suivante : contact@contentforge-ai.com. Nous nous efforcerons de répondre à votre demande dans un délai d'un mois à compter de sa réception.\n\nSi vous estimez, après nous avoir contactés, que vos droits en matière de protection des données n'ont pas été respectés, vous pouvez adresser une réclamation auprès de l'Information Commissioner's Office (ICO) au Royaume-Uni.`
    },
    {
      title: "8. Cookies et technologies similaires",
      text: "8.1 Définition et types de cookies : Un cookie est un petit fichier texte déposé sur votre terminal (ordinateur, tablette, smartphone) lorsque vous visitez notre site ou utilisez notre Service. Nous utilisons différents types de cookies et technologies similaires :\n- Cookies strictement nécessaires : essentiels au fonctionnement du Service\n- Cookies de fonctionnalité : permettent de mémoriser vos préférences\n- Cookies analytiques : nous aident à comprendre comment vous utilisez notre Service\n- Cookies de ciblage/publicitaires : permettent de vous proposer des contenus personnalisés\n\n8.2 Finalités des cookies : Ces technologies nous permettent de :\n- Assurer le bon fonctionnement et la sécurité du Service\n- Mémoriser vos préférences et paramètres\n- Analyser l'utilisation du Service pour l'améliorer\n- Personnaliser votre expérience utilisateur\n- Mesurer l'efficacité de nos communications\n\n8.3 Base juridique : Selon leur finalité, les cookies sont déposés sur la base de :\n- Notre intérêt légitime pour les cookies strictement nécessaires au fonctionnement du Service\n- Votre consentement pour les autres types de cookies, conformément aux exigences du Privacy and Electronic Communications Regulations (PECR)\n\n8.4 Durée de conservation : Les cookies que nous déposons ont une durée de vie variable :\n- Cookies de session : supprimés automatiquement à la fermeture du navigateur\n- Cookies persistants : conservés sur votre terminal pour une durée déterminée (généralement 12 mois maximum conformément aux bonnes pratiques de l'industrie et aux recommandations de l'ICO)\n\n8.5 Gestion des cookies : Vous pouvez à tout moment configurer votre navigateur pour accepter, refuser ou supprimer tout ou partie des cookies. Vous pouvez également utiliser notre panneau de gestion des cookies accessible via le lien « Paramètres des cookies » présent en bas de chaque page de notre site. Veuillez noter que le refus de certains cookies peut affecter votre expérience utilisateur et l'accès à certaines fonctionnalités du Service.\n\n8.6 Liste des cookies utilisés : Les informations détaillées sur les cookies que nous utilisons, leurs finalités, durées de conservation et les tiers y ayant accès sont incluses dans la présente Politique de confidentialité."
    },
    {
      title: "9. Protection des mineurs",
      text: "Notre Service n'est pas destiné aux personnes âgées de moins de 18 ans, et nous ne collectons pas sciemment de données à caractère personnel concernant des mineurs. Si vous êtes parent ou tuteur et que vous pensez que votre enfant nous a fourni des données à caractère personnel sans votre consentement, veuillez nous contacter immédiatement à l'adresse contact@contentforge-ai.com. Si nous apprenons que nous avons collecté des données à caractère personnel d'un mineur sans vérification du consentement parental, nous prendrons des mesures pour supprimer ces informations de nos serveurs dans les plus brefs délais."
    },
    {
      title: "10. Modifications de la politique de confidentialité",
      text: "10.1 Évolution de la Politique : Nous nous réservons le droit de modifier la présente Politique à tout moment, notamment pour l'adapter aux évolutions législatives et réglementaires, aux changements de nos pratiques en matière de traitement des données ou aux mises à jour de notre Service.\n\n10.2 Notification des modifications : En cas de modification substantielle de la Politique, nous vous en informerons par email à l'adresse associée à votre compte et/ou par un avis visible sur notre Service, au moins trente (30) jours avant l'entrée en vigueur des modifications. Pour les modifications mineures, nous mettrons simplement à jour la date de « dernière mise à jour » figurant en haut de la Politique.\n\n10.3 Version applicable : La version en vigueur de la Politique est celle publiée sur notre site au moment où vous utilisez notre Service. Nous vous encourageons à consulter régulièrement cette page pour prendre connaissance des éventuelles modifications.\n\n10.4 Opposition aux modifications : Si vous n'acceptez pas les modifications apportées à la Politique, vous pouvez fermer votre compte conformément aux modalités prévues dans nos Conditions Générales d'Utilisation. Le fait de continuer à utiliser notre Service après la publication des modifications constitue votre acceptation de ces modifications."
    },
    {
      title: "11. Délégué à la Protection des Données",
      text: `Conformément aux exigences du UK GDPR, Hirola Media a désigné un Data Protection Officer (DPO) que vous pouvez contacter pour toute question relative au traitement de vos données personnelles ou à l'exercice de vos droits :\n\nEmail : contact@contentforge-ai.com\nAdresse postale : Hirola Media Ltd - Data Protection Officer, 137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ`
    },
    {
      title: "12. Droit applicable et juridiction compétente",
      text: "12.1 Droit applicable : La présente Politique est régie par le droit britannique (UK). Elle est rédigée en langue française. Dans le cas où elle serait traduite en une ou plusieurs langues, seul le texte français ferait foi en cas de litige.\n\n12.2 Juridiction compétente : À défaut de résolution amiable, tout litige relatif à la présente Politique sera soumis à la compétence exclusive des tribunaux britanniques, sauf disposition légale impérative contraire. Pour les utilisateurs agissant en qualité de commerçants, tout litige sera soumis à la compétence exclusive des tribunaux de Londres.\n\nDernière mise à jour : 25/09/2024"
    }
  ]
}; 