export const termsContent = {
  title: "Conditions Générales d'Utilisation",
  updated: "25/09/2024",
  content: [
    {
      title: "1. Introduction",
      text: "Bienvenue sur ContentGenieAI.com, une plateforme détenue et exploitée par Jastro Limited (« nous », « notre », « nos »). En accédant à notre site web et en utilisant nos services, vous acceptez d'être lié par les présentes Conditions Générales d'Utilisation (« CGU »). Si vous n'acceptez pas ces CGU, veuillez ne pas utiliser notre site ou nos services.\n\nNotre plateforme est un service d'abonnement qui donne accès à des outils d'intelligence artificielle pour générer du contenu optimisé pour le référencement (SEO), notamment des articles de blog, descriptions de produits, et autres contenus textuels."
    },
    {
      title: "2. Description du service",
      text: "ContentGenieAI est une plateforme de génération de contenu SEO et de descriptions de produits alimentée par l'intelligence artificielle, accessible via le site internet contentgenieai.com. Le Service permet aux Utilisateurs de générer automatiquement du contenu optimisé pour le référencement naturel moyennant l'utilisation de Tokens. ContentGenieAI se réserve le droit, à sa seule discrétion et sans notification préalable, de modifier, suspendre, restreindre ou interrompre, temporairement ou définitivement, tout ou partie du Service, notamment à des fins de maintenance, de mise à jour, pour des raisons de sécurité ou tout autre motif jugé pertinent par ContentGenieAI. L'Utilisateur reconnaît que ContentGenieAI n'encourra aucune responsabilité envers lui ou tout tiers pour toute modification, suspension ou interruption du Service."
    },
    {
      title: "3. Inscription et compte d'utilisateur",
      text: "3.1 Conditions d'inscription : Pour utiliser le Service, vous devez créer un compte utilisateur. Vous déclarez et garantissez que : (a) vous êtes majeur et juridiquement capable de conclure un contrat contraignant ; (b) toutes les informations fournies lors de l'inscription sont véridiques, exactes, à jour et complètes ; et (c) vous créez ce compte pour votre usage personnel ou pour celui d'une entité que vous êtes légalement autorisé à représenter.\n\n3.2 Informations personnelles : Lors de l'inscription, certaines informations personnelles vous seront demandées, telles que votre nom, adresse email, et coordonnées complètes. Vous vous engagez à informer ContentGenieAI de tout changement concernant ces informations en cas de modification. ContentGenieAI se réserve le droit de vérifier l'exactitude des informations fournies et de suspendre ou supprimer tout compte contenant des informations inexactes, incomplètes ou frauduleuses.\n\n3.3 Sécurité du compte : Vous êtes responsable du maintien de la confidentialité de vos identifiants de connexion (identifiant et mot de passe) et de toutes les activités effectuées sous votre compte. Vous vous engagez à utiliser un mot de passe sécurisé et à ne pas partager vos identifiants avec des tiers. L'Utilisateur s'engage à notifier immédiatement ContentGenieAI de toute utilisation non autorisée de son compte ou de toute autre violation de sécurité. ContentGenieAI ne pourra être tenue responsable des pertes ou dommages résultant du non-respect par l'Utilisateur de ces obligations de sécurité."
    },
    {
      title: "4. Utilisation du service",
      text: "4.1 Utilisation autorisée : Le Service est destiné à vous permettre de générer du contenu optimisé pour le référencement naturel. Vous vous engagez à n'utiliser le Service que pour des finalités licites et conformes aux présentes CGU. Vous vous interdisez notamment de : (a) générer ou publier du contenu illégal, diffamatoire, obscène, offensant, abusif, pornographique, haineux, discriminatoire, menaçant, harcelant ou préjudiciable ; (b) violer les droits de propriété intellectuelle ou tout autre droit de tiers ; (c) distribuer des virus, des logiciels malveillants ou tout autre code informatique conçu pour nuire ; (d) tenter d'accéder sans autorisation à des parties du Service auxquelles vous n'avez pas accès ; (e) entraver ou perturber le Service ou les serveurs ou réseaux connectés au Service ; (f) contourner les limitations techniques du Service ou altérer des identifiants pour suggérer une fausse association avec ContentGenieAI ; ou (g) utiliser le Service d'une manière qui pourrait, selon l'appréciation raisonnable de ContentGenieAI, entraîner des plaintes, litiges, réclamations, amendes, pénalités ou autres responsabilités pour ContentGenieAI ou ses affiliés.\n\n4.2 Responsabilité du Contenu : Vous assumez l'entière responsabilité du Contenu que vous générez et de l'usage que vous en faites, y compris de l'adéquation de ce Contenu à vos besoins et des conséquences juridiques, commerciales ou autres résultant du fait du Contenu généré via le Service. ContentGenieAI ne garantit pas l'exactitude, la pertinence, la qualité ou la légalité du Contenu généré. L'Utilisateur s'engage à vérifier et, si nécessaire, à modifier le Contenu généré avant toute utilisation ou publication. ContentGenieAI décline expressément toute responsabilité quant aux conséquences directes ou indirectes de l'utilisation du Contenu généré par l'Utilisateur.\n\n4.3 Restrictions techniques : L'Utilisateur s'engage à ne pas surcharger intentionnellement le Service en effectuant un nombre excessif de requêtes dans un court laps de temps. ContentGenieAI se réserve le droit de limiter ou suspendre l'accès au Service à tout Utilisateur dont les activités seraient jugées abusives ou préjudiciables au bon fonctionnement du Service. L'Utilisateur s'engage également à ne pas recourir à des robots, des scripts automatisés ou toute autre technologie similaire pour accéder au Service ou extraire des données, sauf autorisation écrite préalable de ContentGenieAI. L'Utilisateur s'engage à ne pas décompiler, désassembler ou procéder à une ingénierie inverse du Service ou tenter d'en découvrir les codes source, ou à utiliser le Service à des fins non autorisées par ContentGenieAI."
    },
    {
      title: "5. Tarification et paiement",
      text: "5.1 Modèle de tarification : Le Service utilise un modèle de tarification basé sur des Tokens. Un certain nombre de Tokens est nécessaire pour générer du contenu, selon le type et la longueur du contenu demandé. Le nombre de Tokens requis pour chaque type de génération de contenu est indiqué sur le site. Les Tokens peuvent être acquis via un abonnement mensuel, trimestriel ou annuel, ou à l'unité (achat « à la carte »).\n\n5.2 Prix et modifications : Les prix des Tokens et des abonnements sont indiqués en euros, toutes taxes comprises, et sont susceptibles d'être modifiés à tout moment. Les prix applicables sont ceux en vigueur au moment de l'achat, tels qu'indiqués sur le site. ContentGenieAI se réserve le droit de modifier ses tarifs à tout moment, moyennant un préavis de trente (30) jours pour les abonnements en cours.\n\n5.3 Validité des Tokens : Les Tokens acquis via un abonnement sont crédités mensuellement et doivent être utilisés pendant la période de facturation correspondante. Les Tokens non utilisés durant cette période sont perdus et ne peuvent être reportés sur la période suivante, sauf mention contraire dans l'offre souscrite ou décision commerciale exceptionnelle de ContentGenieAI. Les Tokens achetés à l'unité (hors abonnement) sont valables pendant douze (12) mois à compter de leur date d'achat.\n\n5.4 Modalités de paiement : Le paiement des Tokens ou des abonnements s'effectue en ligne par carte bancaire, PayPal ou tout autre moyen de paiement proposé sur le site. Les paiements sont sécurisés par des protocoles de cryptage standard. En souscrivant à un abonnement, vous acceptez le prélèvement automatique du montant de l'abonnement à chaque période de facturation (mensuelle, trimestrielle ou annuelle). Il est de votre responsabilité de vous assurer que votre mode de paiement est valide et dispose de fonds suffisants. Vous êtes responsable de la mise à jour de vos informations de paiement. En fournissant vos informations de paiement, vous certifiez que vous êtes autorisé à utiliser le mode de paiement choisi et vous autorisez ContentGenieAI à vous facturer via ce mode de paiement. ContentGenieAI n'est pas responsable des erreurs ou des frais imposés par votre établissement financier ou votre émetteur de carte."
    },
    {
      title: "6. Abonnements et renouvellement",
      text: "6.1 Souscription : La souscription à un abonnement s'effectue en ligne via le site contentgenieai.com. L'abonnement prend effet à compter de la confirmation du paiement et reste valable pour la durée souscrite (mensuelle, trimestrielle ou annuelle).\n\n6.2 Renouvellement automatique : Sauf mention contraire dans l'offre souscrite, les abonnements sont automatiquement renouvelés à la fin de chaque période, pour une période identique à la période initiale. L'Utilisateur sera débité automatiquement sur le même moyen de paiement que celui utilisé lors de la souscription initiale.\n\n6.3 Résiliation par l'Utilisateur : L'Utilisateur peut résilier son abonnement à tout moment depuis son compte utilisateur. La résiliation prendra effet à la fin de la période en cours, qui continuera jusqu'à son terme. Aucun remboursement ne sera accordé pour la période en cours.\n\n6.4 Résiliation par ContentGenieAI : ContentGenieAI se réserve le droit de résilier unilatéralement tout abonnement en cas de violation des présentes CGU, de non-paiement, ou pour tout autre motif légitime. Dans ce cas, la résiliation prendra effet immédiatement sans préavis ni remboursement."
    },
    {
      title: "7. Propriété intellectuelle",
      text: "7.1 Propriété de ContentGenieAI : ContentGenieAI et/ou ses concédants de licence sont et demeurent propriétaires de tous les droits, titres et intérêts relatifs au Service, y compris mais sans s'y limiter, les logiciels, les algorithmes, les interfaces utilisateur, les marques, les logos, les éléments graphiques, et toutes les améliorations, modifications ou œuvres dérivées de ces composants.\n\n7.2 Licence limitée : ContentGenieAI accorde à l'Utilisateur, pendant la durée de son abonnement ou dans la limite des Tokens disponibles, une licence non exclusive, non transférable, non sous-licenciable et révocable d'accès et d'utilisation du Service pour ses besoins propres. Cette licence ne confère aucun droit de propriété sur le Service ou ses composants.\n\n7.3 Droits sur le Contenu généré : Sous réserve du paiement des Tokens correspondants et du respect des CGU, ContentGenieAI accorde à l'Utilisateur tous les droits de propriété intellectuelle sur le Contenu généré par le Service à sa demande, sans restriction d'utilisation, de reproduction, de modification, d'adaptation et d'exploitation. Toutefois, ContentGenieAI conserve le droit d'utiliser de manière anonymisée les données relatives aux requêtes et aux Contenus générés afin d'améliorer ses algorithmes et la qualité du Service.\n\n7.4 Feedback et suggestions : Si vous soumettez des commentaires, suggestions, ou autres retours concernant le Service (« Feedback »), il accorde à ContentGenieAI une licence mondiale, perpétuelle, irrévocable, transférable, sous-licenciable, libre de redevance et non exclusive pour utiliser, reproduire, modifier, créer des œuvres dérivées, distribuer et exploiter ce Feedback de quelque manière que ce soit et à quelque fin que ce soit, sans aucune restriction."
    },
    {
      title: "8. Garanties et responsabilité",
      text: "8.1 Service fourni « en l'état » : Le Service est fourni « en l'état » et « tel que disponible », sans garantie d'aucune sorte, expresse ou implicite. ContentGenieAI ne garantit pas que le Service sera ininterrompu, sécurisé, exempt d'erreurs ou de virus, ni que les défauts seront corrigés. ContentGenieAI ne garantit pas non plus que le Contenu généré répondra aux attentes ou aux besoins spécifiques de l'Utilisateur, ni qu'il sera exact, complet, à jour, légal ou de qualité satisfaisante.\n\n8.2 Limitation de responsabilité : Dans toute la mesure permise par la loi applicable, ContentGenieAI décline toute responsabilité pour tout dommage direct, indirect, accessoire, spécial, consécutif ou punitif, y compris mais sans s'y limiter, les pertes de profits, de données, d'opportunités commerciales, de réputation ou les coûts d'acquisition de biens ou services de substitution, résultant de l'utilisation ou de l'impossibilité d'utiliser le Service, même si ContentGenieAI a été informée de la possibilité de tels dommages.\n\n8.3 Plafond de responsabilité : Nonobstant toute disposition contraire dans les présentes CGU, et quelle que soit la nature, le fondement et les modalités d'une action engagée contre ContentGenieAI, la responsabilité globale de ContentGenieAI envers l'Utilisateur pour toutes réclamations liées au Service est limitée au montant effectivement payé par l'Utilisateur à ContentGenieAI au cours des douze (12) mois précédant l'événement donnant lieu à responsabilité.\n\n8.4 Indemnisation par l'Utilisateur : L'Utilisateur accepte de défendre, indemniser et dégager de toute responsabilité ContentGenieAI, ses dirigeants, administrateurs, employés et agents contre toute réclamation, dommage, obligation, perte, responsabilité, coût ou dette, et dépense (y compris, mais sans s'y limiter, les honoraires d'avocat) découlant de : (a) l'utilisation du Service par l'Utilisateur ; (b) la violation par l'Utilisateur des présentes CGU ; (c) la violation par l'Utilisateur des droits d'un tiers, incluant mais sans s'y limiter, tout droit d'auteur, de propriété ou de confidentialité ; ou (d) toute réclamation selon laquelle le Contenu généré par l'Utilisateur a causé un dommage à un tiers."
    },
    {
      title: "9. Protection des données personnelles",
      text: "9.1 Traitement des données personnelles : ContentGenieAI collecte et traite les données personnelles des Utilisateurs conformément à sa Politique de Confidentialité. Cette politique détaille les catégories de données collectées, les finalités du traitement, les destinataires éventuels, la durée de conservation, ainsi que les droits dont disposent les Utilisateurs et les modalités d'exercice de ces droits.\n\n9.2 Sous-traitants : ContentGenieAI peut faire appel à des sous-traitants pour l'exécution de certaines prestations nécessaires au fonctionnement du Service. Ces sous-traitants sont soumis à des obligations strictes de confidentialité et de sécurité des données, conformément à la législation applicable en matière de protection des données personnelles.\n\n9.3 Transferts internationaux de données : ContentGenieAI peut être amenée à transférer certaines données à caractère personnel vers des pays situés en dehors de l'Union Européenne. Dans ce cas, ContentGenieAI s'assure que ces transferts sont effectués vers des pays offrant un niveau de protection adéquat ou sont encadrés par des garanties appropriées conformément au Règlement Général sur la Protection des Données (RGPD).\n\n9.4 Confidentialité des contenus : ContentGenieAI s'engage à préserver la confidentialité des Contenus générés par les Utilisateurs et à ne pas les divulguer à des tiers sans autorisation, sauf obligation légale ou judiciaire. Toutefois, l'Utilisateur reconnaît que ContentGenieAI peut utiliser de manière anonymisée les données relatives aux requêtes et aux Contenus générés afin d'améliorer ses algorithmes et la qualité du Service."
    },
    {
      title: "10. Modifications des CGU",
      text: "10.1 Droit de modification : ContentGenieAI se réserve le droit, à sa seule discrétion, de modifier, compléter ou remplacer tout ou partie des présentes CGU à tout moment. Les modifications peuvent être effectuées pour des raisons légales, pour refléter des changements dans le Service ou pour toute autre raison jugée nécessaire par ContentGenieAI.\n\n10.2 Notification des modifications : ContentGenieAI notifiera les Utilisateurs des modifications substantielles apportées aux CGU par email et/ou par un avis visible sur le Service. Pour les modifications mineures, ContentGenieAI pourra se contenter de mettre à jour la date de « dernière mise à jour » figurant en tête des CGU.\n\n10.3 Entrée en vigueur : Les modifications des CGU entrent en vigueur dès leur publication sur le Service, sauf indication contraire. La poursuite de l'utilisation du Service après publication des CGU modifiées constitue une acceptation de ces modifications. Si vous n'acceptez pas les CGU modifiées, vous devez cesser d'utiliser le Service."
    },
    {
      title: "11. Dispositions générales",
      text: "11.1 Intégralité du contrat : Les présentes CGU, ainsi que la Politique de Confidentialité et tout autre document expressément mentionné dans les présentes, constituent l'intégralité de l'accord entre l'Utilisateur et ContentGenieAI concernant l'utilisation du Service et remplacent tous les accords antérieurs ou contemporains, écrits ou oraux, relatifs à l'objet des présentes.\n\n11.2 Divisibilité : Si une disposition des présentes CGU est jugée illégale, nulle ou inapplicable, en tout ou en partie, par un tribunal compétent, cette disposition sera modifiée et interprétée de manière à atteindre autant que possible les objectifs de la disposition originale, et toutes les autres dispositions des CGU resteront pleinement en vigueur.\n\n11.3 Renonciation : Le fait pour ContentGenieAI de ne pas exercer ou faire valoir un droit ou une disposition des présentes CGU ne constitue pas une renonciation à ce droit ou à cette disposition. Aucune renonciation par ContentGenieAI à une quelconque obligation de l'Utilisateur en vertu des présentes CGU ne sera considérée comme une renonciation continue ou une renonciation à toute autre obligation.\n\n11.4 Cession : L'Utilisateur ne peut céder ou transférer les présentes CGU, en tout ou en partie, sans le consentement écrit préalable de ContentGenieAI. ContentGenieAI peut céder ou transférer les présentes CGU, en tout ou en partie, sans restriction et sans notification préalable à l'Utilisateur.\n\n11.5 Notifications : Toutes les notifications requises ou autorisées en vertu des présentes CGU seront faites par écrit et seront considérées comme ayant été dûment délivrées lorsqu'elles seront envoyées par email à l'adresse fournie par l'Utilisateur lors de son inscription ou à l'adresse contact@contentgenieai.com pour les notifications destinées à ContentGenieAI.\n\n11.6 Survie : Les dispositions des présentes CGU qui, par leur nature, devraient survivre à la résiliation ou à l'expiration des CGU, survivront à une telle résiliation ou expiration, y compris, mais sans s'y limiter, les dispositions relatives à la propriété intellectuelle, aux garanties, à la limitation de responsabilité et à l'indemnisation."
    },
    {
      title: "12. Loi applicable et juridiction compétente",
      text: "12.1 Loi applicable : Les présentes CGU ainsi que les relations entre l'Utilisateur et ContentGenieAI sont soumises au droit britannique.\n\n12.2 Résolution amiable : En cas de litige relatif à l'interprétation, la validité ou l'exécution des présentes CGU, les Parties s'engagent à rechercher une solution amiable. À défaut d'accord amiable, chaque Partie sera libre de saisir la juridiction compétente.\n\n12.3 Médiation : En cas de litige de consommation, conformément aux règlements alternatifs des litiges du Royaume-Uni, l'Utilisateur a le droit de recourir gratuitement à un médiateur de la consommation en vue de la résolution amiable du litige qui l'oppose à ContentGenieAI. ContentGenieAI adhère au service de médiation fourni par le Centre for Effective Dispute Resolution (CEDR).\n\n12.4 Juridiction compétente : À défaut de résolution amiable, tout litige relatif à l'interprétation, la validité ou l'exécution des présentes CGU sera soumis aux tribunaux britanniques compétents, sauf disposition impérative contraire."
    },
    {
      title: "13. Contact",
      text: "Pour toute question, réclamation ou information concernant le Site ou les présentes CGU, vous pouvez nous contacter aux coordonnées suivantes :\n\nJastro LIMITED\nSuite 10 12 Durie Street, Leven, Fife, United Kingdom, KY8 4HE\nEmail : info@jastroltd.com\nTéléphone : (850) 783-4170\nCompany Number: 836841\nDate d'incorporation: 07/02/2025\n\nLe service client est disponible du lundi au vendredi, de 9h à 18h (heure du Royaume-Uni), hors jours fériés britanniques.\n\nDernière mise à jour des CGU : 25/03/2024"
    }
  ]
}; 