export const privacyContent = {
  title: "Politique de Confidentialité",
  lastUpdated: "1er mars 2024",
  content: [
    {
      title: "1. Introduction",
      text: "Cette Politique de Confidentialité décrit comment Jastro Limited ('nous', 'notre', 'nos') collecte, utilise et partage vos informations personnelles lorsque vous utilisez notre service AdIntelliVue ('le Service'), un service avancé d'analyse de données publicitaires avec des capacités d'IA conçu pour vous aider à optimiser vos campagnes marketing et votre performance publicitaire.\n\nEn utilisant le Service, vous consentez à la collecte et à l'utilisation des informations conformément à cette politique. Cette Politique de Confidentialité a été rédigée en conformité avec le UK GDPR, le Data Protection Act 2018 et les autres lois applicables en matière de protection des données."
    },
    {
      title: "2. Données collectées",
      text: "Nous collectons et traitons différentes catégories de données personnelles selon les finalités poursuivies :\n\n2.1 Données d'inscription : Lorsque vous créez un compte, nous collectons votre nom, prénom, adresse e-mail et mot de passe (stocké de manière cryptée).\n\n2.2 Données de profil : Informations que vous fournissez facultativement comme votre photo de profil, votre secteur d'activité, vos centres d'intérêt.\n\n2.3 Données de paiement : En cas d'achat, nous collectons les informations nécessaires au traitement de votre paiement (nous ne stockons pas les détails complets de votre carte bancaire, qui sont gérés par nos prestataires de paiement sécurisés).\n\n2.4 Données d'utilisation : Informations sur votre utilisation du service (contenu généré, historique d'utilisation, préférences de génération).\n\n2.5 Données techniques : Adresse IP, type de navigateur, appareil utilisé, pages visitées, temps passé sur le site.\n\n2.6 Données de communication : Lorsque vous nous contactez, nous conservons vos messages et nos réponses."
    },
    {
      title: "3. Finalités du traitement",
      text: "Nous traitons vos données personnelles pour les finalités suivantes :\n\n3.1 Fourniture de nos services : Permettre l'accès et l'utilisation de notre plateforme de formation en ligne, gérer votre compte et traiter vos paiements.\n\n3.2 Amélioration de nos services : Analyser l'utilisation de notre plateforme, résoudre les problèmes techniques, développer de nouvelles fonctionnalités.\n\n3.3 Personnalisation : Adapter notre service à vos préférences et besoins spécifiques.\n\n3.4 Communication : Vous contacter concernant votre compte, répondre à vos demandes d'assistance, vous envoyer des notifications importantes sur le service.\n\n3.5 Marketing : Vous informer sur nos offres, nouveautés et événements (si vous y avez consenti ou si nous avons un intérêt légitime à le faire, sous réserve de votre droit d'opposition).\n\n3.6 Sécurité : Détecter et prévenir les activités frauduleuses, protéger notre plateforme contre les utilisations abusives.\n\n3.7 Obligations légales : Respecter nos obligations légales et réglementaires, notamment en matière fiscale et comptable."
    },
    {
      title: "4. Bases légales du traitement",
      text: "Selon les finalités poursuivies, nous traitons vos données sur les bases légales suivantes :\n\n4.1 Exécution du contrat : Lorsque le traitement est nécessaire à l'exécution du contrat conclu avec vous (fourniture des services, gestion de votre compte, traitement des paiements).\n\n4.2 Consentement : Lorsque vous avez donné votre consentement explicite pour des finalités spécifiques (par exemple, pour recevoir nos communications marketing).\n\n4.3 Intérêts légitimes : Lorsque le traitement est nécessaire aux fins des intérêts légitimes poursuivis par Jastro Limited ou par un tiers, à moins que ne prévalent vos intérêts ou libertés et droits fondamentaux (amélioration des services, prévention de la fraude, marketing direct auprès de clients existants).\n\n4.4 Obligations légales : Lorsque le traitement est nécessaire au respect d'une obligation légale à laquelle nous sommes soumis (obligations comptables, fiscales ou réponses aux demandes des autorités compétentes)."
    },
    {
      title: "5. Destinataires des données",
      text: "Vos données personnelles peuvent être partagées avec les destinataires suivants :\n\n5.1 Notre personnel autorisé : Les membres de notre équipe qui ont besoin d'accéder à vos données pour fournir nos services et assurer le support client.\n\n5.2 Sous-traitants et prestataires de services : Sociétés qui nous fournissent des services et agissent en notre nom (hébergement, paiement, analyse de données, support client) dans le cadre de contrats incluant des obligations de confidentialité et de sécurité.\n\n5.3 Partenaires commerciaux : Uniquement avec votre consentement ou lorsque la loi le permet, notamment pour des services intégrés ou complémentaires.\n\n5.4 Autorités publiques : Dans les cas prévus par la loi, notamment pour répondre à des obligations légales, des procédures judiciaires ou des demandes gouvernementales légitimes.\n\n5.5 Acquéreurs potentiels : En cas de fusion, acquisition, restructuration ou vente d'actifs, vos données personnelles pourraient être transmises comme faisant partie des actifs transférés, sous réserve du maintien des engagements pris dans la présente politique."
    },
    {
      title: "6. Transferts internationaux de données",
      text: "Vos données personnelles peuvent être transférées et traitées dans des pays situés en dehors du Royaume-Uni ou de l'Espace Économique Européen (EEE). Dans ce cas, nous prenons des mesures appropriées pour assurer un niveau de protection adéquat de vos données, notamment en mettant en place des clauses contractuelles types approuvées par les autorités de protection des données.\n\nSi vous souhaitez obtenir une copie des garanties mises en place pour protéger vos données lors de ces transferts, vous pouvez nous contacter à l'adresse indiquée dans la section \"Contact\"."
    },
    {
      title: "7. Vos droits",
      text: "Conformément au UK GDPR et au RGPD, vous disposez des droits suivants concernant vos données à caractère personnel :\n\n7.1 Droit d'accès : Vous avez le droit d'obtenir la confirmation que des données vous concernant sont traitées et, le cas échéant, d'accéder à ces données ainsi qu'à plusieurs informations sur le traitement.\n\n7.2 Droit de rectification : Vous avez le droit d'obtenir la rectification de vos données si elles sont inexactes, ainsi que de les compléter si elles sont incomplètes.\n\n7.3 Droit à l'effacement : Dans certains cas, vous avez le droit d'obtenir l'effacement de vos données (par exemple, lorsque les données ne sont plus nécessaires au regard des finalités du traitement).\n\n7.4 Droit à la limitation du traitement : Dans certaines circonstances, vous avez le droit d'obtenir la limitation du traitement de vos données (par exemple, lorsque vous contestez l'exactitude des données).\n\n7.5 Droit à la portabilité : Vous avez le droit de recevoir les données que vous nous avez fournies dans un format structuré, couramment utilisé et lisible par machine, et de les transmettre à un autre responsable du traitement.\n\n7.6 Droit d'opposition : Vous avez le droit de vous opposer à tout moment, pour des raisons tenant à votre situation particulière, au traitement de vos données fondé sur notre intérêt légitime. Vous pouvez également vous opposer au traitement de vos données à des fins de prospection commerciale.\n\n7.7 Droit de retirer votre consentement : Lorsque le traitement est fondé sur votre consentement, vous avez le droit de le retirer à tout moment, sans que cela n'affecte la licéité du traitement effectué avant ce retrait.\n\n7.8 Droit de définir des directives relatives au sort de vos données après votre décès : Selon la législation applicable, vous pouvez définir des directives générales ou particulières relatives à la conservation, à l'effacement et à la communication de vos données après votre décès.\n\n7.9 Droit d'introduire une réclamation : Si vous estimez que vos droits ne sont pas respectés, vous avez le droit d'introduire une réclamation auprès de l'Information Commissioner's Office (ICO) au Royaume-Uni ou de toute autre autorité de contrôle compétente.\n\nPour exercer ces droits, vous pouvez nous contacter :\n- Par email à l'adresse : support@adintellivue.com\n- Par courrier postal à l'adresse : Jastro Limited, Suite 10 12 Durie Street, Leven, Fife, United Kingdom, KY8 4HE"
    },
    {
      title: "8. Cookies et technologies similaires",
      text: "8.1 Types de cookies : Nous utilisons différents types de cookies pour faire fonctionner notre Site :\n- Cookies strictement nécessaires : essentiels au fonctionnement du Site et permettant d'utiliser les fonctionnalités de base\n- Cookies de préférences : permettent de mémoriser vos choix et préférences\n- Cookies de statistiques : nous aident à comprendre comment les visiteurs interagissent avec le Site\n- Cookies marketing : utilisés pour suivre les visiteurs sur les sites web et afficher des publicités pertinentes\n\n8.2 Base juridique : Notre utilisation des cookies repose sur les bases juridiques suivantes :\n- Notre intérêt légitime pour les cookies strictement nécessaires\n- Votre consentement pour les autres types de cookies, conformément aux dispositions du Privacy and Electronic Communications Regulations 2003 (PECR) et du UK GDPR\n\n8.3 Gestion des cookies : Vous pouvez configurer votre navigateur pour refuser tous les cookies ou pour indiquer quand un cookie est envoyé. Toutefois, si vous n'acceptez pas les cookies, il est possible que certaines fonctionnalités de notre Site ne soient pas accessibles."
    },
    {
      title: "9. Durée de conservation des données",
      text: "Nous conservons vos données personnelles uniquement pendant la durée nécessaire à la réalisation des finalités pour lesquelles elles ont été collectées, sous réserve des obligations légales de conservation et des délais de prescription applicables.\n\n9.1 Données de compte : Conservées pendant toute la durée de votre relation contractuelle avec nous, puis archivées pendant la durée nécessaire à l'établissement, l'exercice ou la défense de droits en justice.\n\n9.2 Données de transaction : Conservées pendant la durée requise par les lois fiscales et comptables (généralement 6 ans au Royaume-Uni).\n\n9.3 Données de navigation et d'utilisation : Conservées pendant une période maximale de 13 mois.\n\n9.4 Données utilisées à des fins marketing : Conservées pendant 3 ans à compter de la fin de la relation commerciale ou du dernier contact pour les prospects.\n\nAu-delà de ces périodes, vos données sont soit supprimées, soit anonymisées de manière irréversible."
    },
    {
      title: "10. Sécurité des données",
      text: "Nous mettons en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos données personnelles contre la perte, l'accès non autorisé, la modification ou la divulgation, notamment :\n- Chiffrement des données sensibles\n- Contrôles d'accès stricts\n- Pare-feu et systèmes de détection d'intrusion\n- Audits de sécurité réguliers\n- Formation de notre personnel à la sécurité des données\n\nToutefois, aucun système de sécurité n'étant parfait, nous ne pouvons garantir une sécurité absolue de vos données."
    },
    {
      title: "11. Délégué à la Protection des Données",
      text: "Conformément aux exigences du UK GDPR et du RGPD, Jastro Limited a désigné un Délégué à la Protection des Données (DPO) chargé de veiller au respect des règles de protection des données au sein de notre organisation. Pour toute question relative à la présente Politique ou pour exercer vos droits, vous pouvez contacter notre DPO à l'adresse email suivante : support@adintellivue.com."
    },
    {
      title: "12. Loi applicable et juridiction compétente",
      text: "La présente Politique est régie par le droit britannique. En cas de litige relatif à l'interprétation ou à l'exécution de la présente Politique, les tribunaux britanniques seront seuls compétents, sauf disposition impérative contraire."
    },
    {
      title: "13. Modifications de la politique de confidentialité",
      text: "Nous nous réservons le droit de modifier la présente politique de confidentialité à tout moment. En cas de modification substantielle, nous vous en informerons par email ou par un avis visible sur notre Site. Nous vous encourageons à consulter régulièrement cette page pour prendre connaissance des éventuelles modifications.\n\nLa date de dernière mise à jour figure en haut de cette politique. Votre utilisation continue du Site après la publication des modifications constitue votre acceptation de la politique de confidentialité révisée."
    },
    {
      title: "14. Contact",
      text: "Le responsable du traitement de vos données personnelles est Jastro Limited, dont les coordonnées sont les suivantes :\n\nJastro Limited\nSuite 10 12 Durie Street, Leven, Fife, United Kingdom, KY8 4HE\nEmail : support@adintellivue.com\nTéléphone : (850) 783-4170"
    }
  ]
}; 