export const refundContent = {
  title: "Politique de Remboursement",
  content: [
    {
      title: "1. Principes généraux",
      text: "La présente politique de remboursement (ci-après la « Politique ») définit les conditions dans lesquelles les utilisateurs du service AdIntelliVue (ci-après le « Service ») peuvent demander et obtenir le remboursement de leurs achats. Cette Politique fait partie intégrante des Conditions Générales d'Utilisation (ci-après les « CGU ») du Service et est soumise aux mêmes définitions. En utilisant le Service et en procédant à des achats, l'Utilisateur reconnaît avoir lu, compris et accepté sans réserve la présente Politique."
    },
    {
      title: "2. Modalités spécifiques aux abonnements",
      text: "2.1 Facturation récurrente : Les abonnements souscrits sur la plateforme AdIntelliVue font l'objet d'une facturation récurrente selon la périodicité choisie lors de la souscription (mensuelle, trimestrielle ou annuelle). Le montant correspondant est automatiquement prélevé sur le moyen de paiement enregistré au début de chaque nouvelle période.\n\n2.2 Droit d'annulation : Vous disposez de la faculté d'annuler votre abonnement à tout moment via votre espace client personnel. Cette annulation prendra effet à l'échéance de la période en cours, sans possibilité de remboursement prorata temporis pour la période entamée.\n\n2.3 Notification de renouvellement : Pour tout abonnement avec reconduction tacite, vous serez informé par email, au plus tard un mois avant la date de reconduction, de la possibilité de ne pas reconduire l'abonnement. Cette information mentionnera le délai de préavis applicable à l'annulation.\n\n2.4 Modification des conditions : En cas de modification substantielle des conditions d'abonnement (notamment tarifaires) en cours de contrat, vous en serez informé avec un préavis minimum de trente (30) jours. Vous disposerez alors de la faculté de résilier votre abonnement sans pénalité jusqu'à la date d'entrée en vigueur des nouvelles conditions."
    },
    {
      title: "3. Gestion des tokens non utilisés",
      text: "3.1 Expiration des tokens : Les tokens non utilisés à l'échéance de votre période d'abonnement peuvent être soumis à expiration ou faire l'objet d'un report sur la période suivante, selon les conditions spécifiques du forfait souscrit. Ces conditions sont expressément mentionnées dans la description de l'offre au moment de la souscription.\n\n3.2 Absence de remboursement : En aucun cas les tokens non utilisés ne pourront faire l'objet d'un remboursement en numéraire, quelle que soit la cause de leur non-utilisation (résiliation volontaire d'abonnement, suspension ou fermeture de compte, force majeure, etc.).\n\n3.3 Non-transférabilité : Les tokens sont strictement personnels et rattachés au compte utilisateur pour lequel ils ont été acquis. Ils ne peuvent être cédés, transférés ou revendus à un tiers, sous peine de suspension immédiate du compte sans compensation."
    },
    {
      title: "4. Modalités de réclamation et de remboursement",
      text: "4.1 Réclamation : Toute demande de remboursement doit être adressée à notre service clientèle dans les plus brefs délais après la constatation du problème ou de l'erreur de facturation, par email à l'adresse support@adintellivue.com ou via le formulaire de contact dédié accessible dans votre espace client.\n\n4.2 Justificatifs requis : Toute réclamation relative à une erreur de facturation devra être accompagnée des justificatifs correspondants (facture, relevé bancaire montrant le double débit, etc.).\n\n4.3 Délai de traitement : Nous nous engageons à traiter toute demande de remboursement dans un délai maximal de quatorze (14) jours ouvrés à compter de la réception de tous les éléments nécessaires au traitement de la demande.\n\n4.4 Mode de remboursement : Le remboursement sera effectué selon le même mode de paiement que celui utilisé lors de l'achat initial, sauf impossibilité technique ou accord contraire. Dans ce dernier cas, un autre mode de remboursement pourra être proposé à l'Utilisateur.\n\n4.5 Frais bancaires : Jastro Limited ne remboursera pas les éventuels frais bancaires liés au paiement initial ou au remboursement qui seraient facturés à l'Utilisateur par son établissement financier."
    },
    {
      title: "5. Dysfonctionnements techniques",
      text: "5.1 Interruption significative du service : En cas de dysfonctionnement technique majeur imputable à AdIntelliVue et rendant impossible l'utilisation du service pendant une durée continue supérieure à vingt-quatre (24) heures, une compensation pourra être accordée sous forme de tokens supplémentaires.\n\n5.2 Calcul de la compensation : Le montant de cette compensation sera déterminé au prorata de la durée d'indisponibilité du service et du type d'abonnement souscrit, selon la formule suivante : (nombre de tokens mensuels / 30) × nombre de jours d'indisponibilité.\n\n5.3 Procédure de demande : Pour bénéficier de cette compensation, vous devez en faire la demande explicite auprès du service client dans un délai maximum de sept (7) jours suivant la résolution du dysfonctionnement, en précisant les dates et heures d'indisponibilité constatées.\n\n5.4 Exclusion de remboursement numéraire : En aucun cas un dysfonctionnement technique, quelle que soit sa durée ou sa gravité, ne pourra donner lieu à un remboursement en numéraire. La compensation sous forme de tokens supplémentaires constitue le seul et unique dédommagement possible.\n\n5.5 Cas de force majeure : Les dysfonctionnements résultant d'un cas de force majeure tel que défini par la loi applicable (notamment catastrophe naturelle, incendie, inondation, conflit social, panne électrique, attaque informatique massive) ne donnent droit à aucune compensation."
    },
    {
      title: "6. Conséquences de la fermeture de compte",
      text: "6.1 Fermeture volontaire : En cas de fermeture volontaire de votre compte utilisateur, les tokens restants sur celui-ci seront définitivement perdus à compter de la date effective de fermeture, sans possibilité de remboursement ou de transfert.\n\n6.2 Suspension ou résiliation pour manquement : En cas de suspension temporaire ou de résiliation définitive de votre compte pour violation des Conditions Générales d'Utilisation, AdIntelliVue se réserve le droit de supprimer l'intégralité des tokens restants sans compensation d'aucune sorte.\n\n6.3 Délai de grâce : Avant toute fermeture volontaire de compte, un message d'avertissement vous informera des conséquences de cette action sur vos tokens restants. Un délai de rétractation de sept (7) jours vous sera accordé pour annuler votre demande de fermeture.\n\n6.4 Réactivation de compte : En cas de réactivation d'un compte précédemment fermé volontairement, et sous réserve que cette réactivation intervienne dans un délai maximum de trente (30) jours suivant la fermeture, AdIntelliVue pourra, à sa seule discrétion et sans y être tenue, restaurer tout ou partie des tokens perdus."
    },
    {
      title: "7. Droit de rétractation",
      text: "7.1 Renonciation : Conformément à la législation britannique applicable aux contenus numériques, l'Utilisateur reconnaît et accepte expressément que la fourniture du Service commence immédiatement après la validation de son achat. En conséquence, l'Utilisateur renonce expressément à son droit de rétractation au moment de la confirmation de son achat.\n\n7.2 Effets de la renonciation : Cette renonciation signifie que l'Utilisateur ne pourra pas exercer son droit de rétractation concernant les Tokens achetés ou les abonnements souscrits, sous réserve des cas spécifiques mentionnés dans la présente Politique. Cette renonciation est clairement indiquée lors du processus d'achat et nécessite une action positive de l'Utilisateur pour confirmer son accord.\n\n7.3 Formulaire de rétractation : Nonobstant ce qui précède, dans l'hypothèse où le droit de rétractation serait applicable, l'Utilisateur peut se rétracter sans avoir à motiver sa décision, en adressant sa demande de manière claire et non équivoque par email à l'adresse support@adintellivue.com en précisant son identifiant utilisateur et la référence de la transaction concernée."
    },
    {
      title: "8. Circonstances exceptionnelles de remboursement",
      text: "8.1 Pouvoir discrétionnaire : Dans des circonstances exceptionnelles dûment justifiées et documentées, AdIntelliVue se réserve le droit, à sa seule et entière discrétion, d'examiner des demandes de remboursement particulières ne relevant pas des cas précédemment énumérés.\n\n8.2 Non-création de précédent : Toute dérogation exceptionnelle accordée à la présente politique ne saurait constituer un précédent invocable par d'autres utilisateurs ou dans d'autres circonstances, ni être interprétée comme une renonciation générale à notre politique de non-remboursement.\n\n8.3 Modalités d'examen : Les demandes relevant de circonstances exceptionnelles doivent être adressées par écrit à notre service client, accompagnées de tous les justificatifs pertinents. Un accusé de réception vous sera adressé sous 48 heures ouvrées, suivi d'une réponse motivée dans un délai maximum de trente (30) jours.\n\n8.4 Critères d'appréciation : L'examen des demandes exceptionnelles tiendra notamment compte de l'ancienneté du compte utilisateur, de l'historique des transactions, de la nature et de la gravité des circonstances invoquées, ainsi que de la bonne foi manifeste du demandeur."
    },
    {
      title: "9. Réclamations et résolution des litiges",
      text: "9.1 Service client : Pour toute question ou réclamation concernant un remboursement, l'Utilisateur peut contacter notre service client via le formulaire de contact disponible sur notre site, par téléphone au numéro indiqué dans les mentions légales, ou par email à l'adresse support@adintellivue.com.\n\n9.2 Délai de forclusion : Toute réclamation doit être formulée dans un délai de trente (30) jours calendaires à compter de la date de la transaction contestée ou du fait générateur du litige. Passé ce délai, aucune réclamation ne sera recevable.\n\n9.3 Règlement amiable des litiges : En cas de litige relatif à un remboursement, les parties s'efforceront de résoudre leur différend à l'amiable avant toute action judiciaire. L'Utilisateur est invité à contacter en priorité le service client de Jastro Limited à l'adresse support@adintellivue.com afin de rechercher une solution amiable.\n\n9.4 Juridiction compétente : À défaut de résolution amiable, tout litige relatif à la présente politique de remboursement sera soumis à la compétence exclusive des tribunaux britanniques, sauf disposition légale impérative contraire.\n\n9.5 Plateforme européenne de règlement en ligne des litiges : Pour les litiges transfrontaliers, les consommateurs résidant dans l'Union européenne peuvent également recourir à la plateforme européenne de règlement en ligne des litiges accessible à l'adresse : https://ec.europa.eu/consumers/odr/."
    },
    {
      title: "10. Modifications de la politique de remboursement",
      text: "10.1 Droit de modification : Jastro Limited se réserve le droit de modifier, compléter ou remplacer tout ou partie de la présente politique de remboursement à tout moment, notamment pour l'adapter aux évolutions législatives et réglementaires ou à des changements dans nos pratiques commerciales.\n\n10.2 Notification des modifications : Les modifications substantielles de la politique de remboursement vous seront notifiées par email et/ou par un avis visible sur notre plateforme au moins trente (30) jours avant leur entrée en vigueur. Pour les modifications mineures, seule la date de « dernière mise à jour » figurant en bas de la politique sera actualisée.\n\n10.3 Application temporelle : Les modifications de la politique de remboursement s'appliquent uniquement aux transactions effectuées après la date d'entrée en vigueur desdites modifications. Les transactions antérieures restent soumises à la version de la politique en vigueur au moment de leur réalisation.\n\n10.4 Opposition aux modifications : Si vous n'acceptez pas les modifications apportées à la politique de remboursement, vous avez la possibilité de ne pas effectuer de nouveaux achats. La poursuite de vos achats après l'entrée en vigueur des modifications constitue votre acceptation de ces dernières.\n\nDernière mise à jour : 25/03/2024"
    }
  ]
}; 