export const refundContent = {
  title: "Politique de remboursement",
  lastUpdated: "25/09/2024",
  content: [
    {
      title: "1. Principe général de non-remboursement",
      text: "1.1 Caractère définitif des achats : Les tokens acquis sur la plateforme AdPulseAI, que ce soit via un abonnement ou à l'unité (« à la carte »), ne sont pas remboursables. Conformément à l'article L. 221-28 du Code de la consommation, tout achat de tokens est considéré comme final et définitif, constituant l'acquisition d'un contenu numérique non fourni sur un support matériel.\n\n1.2 Acceptation préalable : En procédant à l'achat de tokens, vous reconnaissez expressément avoir pris connaissance de la présente politique de non-remboursement et y consentir sans réserve. Cette acceptation constitue une condition essentielle de la transaction et ne peut être ultérieurement remise en cause.\n\n1.3 Absence de garantie de résultat : AdPulseAI ne garantit aucun résultat spécifique quant à l'utilisation des tokens pour l'analyse de vos publicités Facebook. La qualité, la pertinence ou l'adéquation des analyses générées à vos besoins particuliers ne saurait justifier une demande de remboursement.",
      subsections: []
    },
    {
      title: "2. Exceptions au principe de non-remboursement",
      text: "2.1 Erreur technique de facturation : En cas d'erreur technique imputable à Addax Media et ayant entraîné une facturation erronée (double facturation, montant incorrect), le remboursement sera effectué intégralement par le même moyen de paiement que celui utilisé lors de l'achat, dans un délai maximal de 14 jours à compter de la constatation de l'erreur.\n\n2.2 Non-fourniture du service : Dans l'hypothèse où les tokens achetés ne seraient pas crédités sur votre compte utilisateur malgré un paiement dûment validé, Addax Media procédera, à votre choix, soit au crédit des tokens manquants, soit au remboursement intégral du montant correspondant.\n\n2.3 Période de rétractation légale : Conformément aux dispositions légales, le droit de rétractation ne s'applique pas à l'achat de tokens, qui constituent un contenu numérique non fourni sur un support matériel. Cependant, si vous n'avez pas expressément renoncé à votre droit de rétractation lors de l'achat ET que vous n'avez pas commencé à utiliser les tokens, vous disposez d'un délai de 14 jours à compter de la date d'achat pour exercer votre droit de rétractation.",
      subsections: []
    },
    {
      title: "3. Modalités spécifiques aux abonnements",
      text: "3.1 Facturation récurrente : Les abonnements souscrits sur la plateforme AdPulseAI font l'objet d'une facturation récurrente selon la périodicité choisie lors de la souscription (mensuelle, trimestrielle ou annuelle). Le montant correspondant est automatiquement prélevé sur le moyen de paiement enregistré au début de chaque nouvelle période.\n\n3.2 Droit d'annulation : Conformément à l'article L. 215-1 du Code de la consommation, vous disposez de la faculté d'annuler votre abonnement à tout moment via votre espace client personnel. Cette annulation prendra effet à l'échéance de la période en cours, sans possibilité de remboursement prorata temporis pour la période entamée.\n\n3.3 Notification de renouvellement : Pour tout abonnement avec reconduction tacite, vous serez informé par email, au plus tôt trois mois et au plus tard un mois avant la date de reconduction, de la possibilité de ne pas reconduire l'abonnement. Cette information mentionnera le délai de préavis applicable à l'annulation.\n\n3.4 Modification des conditions : En cas de modification substantielle des conditions d'abonnement (notamment tarifaires) en cours de contrat, vous en serez informé avec un préavis minimum de trente (30) jours. Vous disposerez alors de la faculté de résilier votre abonnement sans pénalité jusqu'à la date d'entrée en vigueur des nouvelles conditions.",
      subsections: []
    },
    {
      title: "4. Gestion des tokens non utilisés",
      text: "4.1 Expiration des tokens : Les tokens non utilisés à l'échéance de votre période d'abonnement peuvent être soumis à expiration ou faire l'objet d'un report sur la période suivante, selon les conditions spécifiques du forfait souscrit. Ces conditions sont expressément mentionnées dans la description de l'offre au moment de la souscription.\n\n4.2 Absence de remboursement : En aucun cas les tokens non utilisés ne pourront faire l'objet d'un remboursement en numéraire, quelle que soit la cause de leur non-utilisation (résiliation volontaire d'abonnement, suspension ou fermeture de compte, force majeure, etc.).\n\n4.3 Non-transférabilité : Les tokens sont strictement personnels et rattachés au compte utilisateur pour lequel ils ont été acquis. Ils ne peuvent être cédés, transférés ou revendus à un tiers, sous peine de suspension immédiate du compte sans compensation.",
      subsections: []
    },
    {
      title: "5. Rectification des erreurs de facturation",
      text: "5.1 Signalement des erreurs : En cas d'anomalie de facturation avérée (double facturation, montant erroné, prélèvement non autorisé), vous êtes tenu de la signaler dans les plus brefs délais et au plus tard dans un délai de trente (30) jours calendaires à compter de la date de la transaction litigieuse, par email à l'adresse facturation@adpulseai.com ou via le formulaire de contact dédié accessible dans votre espace client.\n\n5.2 Justificatifs requis : Toute réclamation relative à une erreur de facturation devra être accompagnée des justificatifs nécessaires (relevé bancaire, confirmation de paiement, etc.) permettant de constater l'anomalie alléguée.\n\n5.3 Modalités de régularisation : Après vérification et confirmation de l'erreur de facturation, AdPulseAI procédera, à sa discrétion, soit au remboursement du montant indûment facturé sur le moyen de paiement initialement utilisé, soit à l'octroi d'un crédit de tokens équivalent sur votre compte. Le délai de régularisation n'excédera pas trente (30) jours à compter de la reconnaissance de l'erreur par nos services.\n\n5.4 Exclusion : Les erreurs résultant d'informations erronées fournies par l'utilisateur lors de la procédure de paiement ne sont pas considérées comme des erreurs de facturation au sens du présent article.",
      subsections: []
    },
    {
      title: "6. Dysfonctionnements techniques",
      text: "6.1 Interruption significative du service : En cas de dysfonctionnement technique majeur imputable à AdPulseAI et rendant impossible l'utilisation du service pendant une durée continue supérieure à vingt-quatre (24) heures, une compensation pourra être accordée sous forme de tokens supplémentaires.\n\n6.2 Calcul de la compensation : Le montant de cette compensation sera déterminé au prorata de la durée d'indisponibilité du service et du type d'abonnement souscrit, selon la formule suivante : (nombre de tokens mensuels / 30) × nombre de jours d'indisponibilité.\n\n6.3 Procédure de demande : Pour bénéficier de cette compensation, vous devez en faire la demande explicite auprès du service client dans un délai maximum de sept (7) jours suivant la résolution du dysfonctionnement, en précisant les dates et heures d'indisponibilité constatées.\n\n6.4 Exclusion de remboursement numéraire : En aucun cas un dysfonctionnement technique, quelle que soit sa durée ou sa gravité, ne pourra donner lieu à un remboursement en numéraire. La compensation sous forme de tokens supplémentaires constitue le seul et unique dédommagement possible.\n\n6.5 Cas de force majeure : Les dysfonctionnements résultant d'un cas de force majeure tel que défini à l'article 1218 du Code civil français (notamment catastrophe naturelle, incendie, inondation, conflit social, panne électrique, attaque informatique massive) ne donnent droit à aucune compensation.",
      subsections: []
    },
    {
      title: "7. Conséquences de la fermeture de compte",
      text: "7.1 Fermeture volontaire : En cas de fermeture volontaire de votre compte utilisateur, les tokens restants sur celui-ci seront définitivement perdus à compter de la date effective de fermeture, sans possibilité de remboursement ou de transfert.\n\n7.2 Suspension ou résiliation pour manquement : En cas de suspension temporaire ou de résiliation définitive de votre compte pour violation des Conditions Générales d'Utilisation, AdPulseAI se réserve le droit de supprimer l'intégralité des tokens restants sans compensation d'aucune sorte.\n\n7.3 Délai de grâce : Avant toute fermeture volontaire de compte, un message d'avertissement vous informera des conséquences de cette action sur vos tokens restants. Un délai de rétractation de sept (7) jours vous sera accordé pour annuler votre demande de fermeture.\n\n7.4 Réactivation de compte : En cas de réactivation d'un compte précédemment fermé volontairement, et sous réserve que cette réactivation intervienne dans un délai maximum de trente (30) jours suivant la fermeture, AdPulseAI pourra, à sa seule discrétion et sans y être tenue, restaurer tout ou partie des tokens perdus.",
      subsections: []
    },
    {
      title: "8. Droit de rétractation et exceptions légales",
      text: "8.1 Principe d'exception au droit de rétractation : Conformément à l'article L. 221-28, 13° du Code de la consommation, le droit de rétractation légal de quatorze (14) jours ne s'applique pas à la fourniture de contenus numériques non fournis sur un support matériel lorsque l'exécution a commencé après accord préalable exprès du consommateur et renoncement exprès à son droit de rétractation.\n\n8.2 Renonciation expresse : En procédant à l'achat de tokens et en commençant à utiliser nos services, vous reconnaissez expressément renoncer à votre droit de rétractation. Cette renonciation est matérialisée par une case à cocher obligatoire lors du processus d'achat.\n\n8.3 Délai de réflexion contractuel : Nonobstant ce qui précède, AdPulseAI accorde contractuellement un délai de réflexion de vingt-quatre (24) heures à compter de l'achat pour les nouveaux utilisateurs effectuant leur premier achat de tokens, à condition qu'aucun token n'ait été consommé durant cette période. Cette faculté de rétractation contractuelle ne peut être exercée qu'une seule fois par utilisateur.\n\n8.4 Modalités d'exercice du délai de réflexion : Pour exercer cette faculté de rétractation contractuelle, vous devez nous adresser une demande non équivoque par email à l'adresse support@adpulse-ai.com en précisant votre identifiant utilisateur et la référence de la transaction concernée.",
      subsections: []
    },
    {
      title: "9. Circonstances exceptionnelles de remboursement",
      text: "9.1 Pouvoir discrétionnaire : Dans des circonstances exceptionnelles dûment justifiées et documentées, AdPulseAI se réserve le droit, à sa seule et entière discrétion, d'examiner des demandes de remboursement particulières ne relevant pas des cas précédemment énumérés.\n\n9.2 Non-création de précédent : Toute dérogation exceptionnelle accordée à la présente politique ne saurait constituer un précédent invocable par d'autres utilisateurs ou dans d'autres circonstances, ni être interprétée comme une renonciation générale à notre politique de non-remboursement.\n\n9.3 Modalités d'examen : Les demandes relevant de circonstances exceptionnelles doivent être adressées par écrit à notre service client, accompagnées de tous les justificatifs pertinents. Un accusé de réception vous sera adressé sous 48 heures ouvrées, suivi d'une réponse motivée dans un délai maximum de trente (30) jours.\n\n9.4 Critères d'appréciation : L'examen des demandes exceptionnelles tiendra notamment compte de l'ancienneté du compte utilisateur, de l'historique des transactions, de la nature et de la gravité des circonstances invoquées, ainsi que de la bonne foi manifeste du demandeur.",
      subsections: []
    },
    {
      title: "10. Procédure de réclamation et médiation",
      text: "10.1 Réclamation préalable : Pour toute contestation relative à la facturation ou à l'application de la présente politique, vous devez obligatoirement adresser une réclamation écrite préalable à notre service client via le formulaire dédié accessible dans votre espace personnel ou par email à l'adresse support@adpulse-ai.com.\n\n10.2 Délai de forclusion : Toute réclamation doit être formulée dans un délai de trente (30) jours calendaires à compter de la date de la transaction contestée ou du fait générateur du litige. Passé ce délai, aucune réclamation ne sera recevable.\n\n10.3 Contenu de la réclamation : Votre réclamation doit comporter a minima les éléments suivants : vos coordonnées complètes, votre identifiant utilisateur, la référence de la transaction concernée, la description précise de l'objet de votre réclamation et toute pièce justificative pertinente.\n\n10.4 Traitement des réclamations : Nous nous engageons à accuser réception de votre réclamation dans un délai de quarante-huit (48) heures ouvrées et à y apporter une réponse circonstanciée dans un délai maximum de trente (30) jours.\n\n10.5 Médiation de la consommation : En cas de litige non résolu par notre service client, et conformément aux articles L. 611-1 et suivants du Code de la consommation, vous disposez du droit de recourir gratuitement au service de médiation proposé par AdPulseAI. Le médiateur de la consommation ainsi désigné est Médiation-Net, que vous pouvez contacter à l'adresse suivante : Médiation-Net, 34 rue des Épinettes, 75017 Paris, France. Site web : www.mediation-net.com, email : contact@mediation-net.com.\n\n10.6 Conditions de recevabilité en médiation : Pour être recevable, votre demande de médiation doit être introduite dans un délai d'un an à compter de votre réclamation écrite auprès de nos services, et le litige ne doit pas avoir été précédemment examiné ou être en cours d'examen par un autre médiateur ou par un tribunal.",
      subsections: []
    },
    {
      title: "11. Modifications de la politique de remboursement",
      text: "11.1 Droit de modification : AdPulseAI se réserve le droit de modifier, compléter ou remplacer tout ou partie de la présente politique de remboursement à tout moment, notamment pour l'adapter aux évolutions législatives et réglementaires ou à des changements dans nos pratiques commerciales.\n\n11.2 Notification des modifications : Les modifications substantielles de la politique de remboursement vous seront notifiées par email et/ou par un avis visible sur notre plateforme au moins trente (30) jours avant leur entrée en vigueur. Pour les modifications mineures, seule la date de « dernière mise à jour » figurant en bas de la politique sera actualisée.\n\n11.3 Application temporelle : Les modifications de la politique de remboursement s'appliquent uniquement aux transactions effectuées après la date d'entrée en vigueur desdites modifications. Les transactions antérieures restent soumises à la version de la politique en vigueur au moment de leur réalisation.\n\n11.4 Opposition aux modifications : Si vous n'acceptez pas les modifications apportées à la politique de remboursement, vous avez la possibilité de ne pas effectuer de nouveaux achats. La poursuite de vos achats après l'entrée en vigueur des modifications constitue votre acceptation de ces dernières.\n\nDernière mise à jour : 25/09/2024",
      subsections: []
    }
  ]
}; 