export const termsContent = {
  title: "Conditions Générales d'Utilisation",
  lastUpdated: "25/09/2024",
  content: [
    {
      title: "1. Dispositions préliminaires et définitions",
      text: "Les présentes Conditions Générales d'Utilisation (ci-après dénommées « CGU ») constituent un accord juridiquement contraignant entre vous, personne physique ou morale (ci-après dénommé « l'Utilisateur » ou « vous ») et la société Addax Media Ltd, société à responsabilité limitée, enregistrée en Angleterre sous le numéro 16314045, dont le siège social est situé à Flat 5, 9 Langley Road, Watford, England, WD17 4PS (ci-après dénommée « Addax Media », « nous » ou « notre »). En accédant à notre plateforme, en l'utilisant ou en vous y inscrivant, vous reconnaissez avoir lu, compris et accepté sans réserve l'intégralité des présentes CGU. Si vous n'acceptez pas ces conditions, nous vous prions de ne pas utiliser notre service. Aux fins des présentes CGU, les termes suivants, lorsqu'ils sont utilisés avec une majuscule, auront la signification qui leur est attribuée ci-après : « Service » désigne la plateforme AdPulseAI, ses fonctionnalités et tous les services associés ; « Contenu » désigne tout texte, image, vidéo, audio ou autre matériel généré ou téléchargé sur la plateforme ; « Token » désigne l'unité de valeur utilisée pour accéder aux fonctionnalités de génération de contenu.",
      subsections: []
    },
    {
      title: "2. Objet et description du Service",
      text: "AdPulseAI est une plateforme d'analyse de données publicitaires Facebook alimentée par l'intelligence artificielle, accessible via le site internet adpulseai.com. Le Service permet aux Utilisateurs d'analyser et d'optimiser leurs campagnes publicitaires Facebook grâce à des algorithmes d'intelligence artificielle avancés, moyennant l'utilisation de Tokens. Addax Media se réserve le droit, à sa seule discrétion et sans notification préalable, de modifier, suspendre, restreindre ou interrompre, temporairement ou définitivement, tout ou partie du Service, y compris mais sans s'y limiter, les fonctionnalités disponibles, les interfaces utilisateur, les algorithmes d'analyse, la tarification et les modalités d'accès. Ces modifications peuvent être effectuées pour des raisons techniques, commerciales, légales ou pour tout autre motif jugé pertinent par Addax Media. L'Utilisateur reconnaît que Addax Media n'encourra aucune responsabilité envers lui ou tout tiers pour toute modification, suspension ou interruption du Service.",
      subsections: []
    },
    {
      title: "3. Conditions d'accès et d'inscription",
      text: "3.1 Capacité juridique : L'accès et l'utilisation du Service sont réservés aux personnes physiques âgées d'au moins 18 ans jouissant de leur pleine capacité juridique ou aux personnes morales régulièrement constituées. Si vous agissez pour le compte d'une personne morale, vous déclarez et garantissez être dûment habilité à agir au nom et pour le compte de cette entité et à l'engager aux termes des présentes CGU.\n\n3.2 Création de compte : Pour accéder à l'intégralité des fonctionnalités du Service, l'Utilisateur doit créer un compte en fournissant des informations exactes, complètes et à jour. L'Utilisateur s'engage à mettre à jour ces informations en cas de modification. Addax Media se réserve le droit de vérifier l'exactitude des informations fournies et de suspendre ou supprimer tout compte contenant des informations inexactes, incomplètes ou frauduleuses.\n\n3.3 Sécurité du compte : L'Utilisateur est seul responsable de la préservation de la confidentialité de ses identifiants de connexion et de toutes les activités qui se produisent sous son compte. L'Utilisateur s'engage à notifier immédiatement Addax Media de toute utilisation non autorisée de son compte ou de toute autre violation de sécurité. Addax Media ne pourra être tenue responsable des pertes ou dommages résultant du non-respect par l'Utilisateur de ces obligations de sécurité.",
      subsections: []
    },
    {
      title: "4. Modalités d'utilisation du Service",
      text: "4.1 Utilisation conforme : L'Utilisateur s'engage à utiliser le Service conformément aux présentes CGU, aux lois et réglementations applicables, ainsi qu'aux droits des tiers. Il est strictement interdit d'utiliser le Service à des fins illicites, frauduleuses, diffamatoires, obscènes, menaçantes, abusives ou autrement répréhensibles. L'Utilisateur s'engage notamment à ne pas : (i) violer les droits de propriété intellectuelle de tiers ; (ii) générer ou diffuser des contenus illégaux, préjudiciables, trompeurs, discriminatoires ou frauduleux ; (iii) transmettre des virus, chevaux de Troie, vers, bombes logiques ou tout autre code malveillant ; (iv) tenter d'accéder sans autorisation aux systèmes ou réseaux connectés au Service ; (v) interférer avec ou perturber l'intégrité ou les performances du Service.\n\n4.2 Contenu analytique : L'Utilisateur est entièrement responsable de l'utilisation qu'il fait des analyses et recommandations générées via le Service. Addax Media ne garantit pas l'exactitude, la pertinence, la qualité ou la légalité du Contenu analytique généré. L'Utilisateur s'engage à vérifier et, si nécessaire, à adapter les recommandations générées avant toute application à ses campagnes publicitaires. Addax Media décline expressément toute responsabilité quant aux conséquences directes ou indirectes de l'utilisation des analyses et recommandations générées par l'Utilisateur.\n\n4.3 Restrictions techniques : L'Utilisateur s'engage à ne pas contourner, désactiver ou interférer avec les fonctionnalités de sécurité du Service ou les fonctionnalités qui empêchent ou restreignent l'utilisation ou la copie de tout Contenu. Il s'engage également à ne pas utiliser de robots, spiders, scrapers ou autres moyens automatisés pour accéder au Service à des fins non autorisées par Addax Media.",
      subsections: []
    },
    {
      title: "5. Système de Tokens et tarification",
      text: "5.1 Principe de fonctionnement : Le Service fonctionne sur la base d'un système de Tokens. Chaque génération de contenu consomme un nombre prédéterminé de Tokens, variable selon le type et la longueur du contenu demandé. Les Tokens constituent une licence non exclusive, non transférable et révocable permettant d'accéder aux fonctionnalités de génération de contenu du Service.\n\n5.2 Acquisition de Tokens : Les Tokens peuvent être acquis soit via un abonnement périodique (bimensuel, mensuel, trimestriel ou annuel) donnant droit à un nombre défini de Tokens pour chaque période, soit par achat ponctuel (« à la carte »). Les tarifs applicables sont ceux en vigueur au moment de la souscription ou de l'achat, tels qu'indiqués sur le site. Addax Media se réserve le droit de modifier ses tarifs à tout moment, moyennant un préavis de trente (30) jours pour les abonnements en cours.\n\n5.3 Validité des Tokens : Les Tokens acquis via un abonnement sont valables uniquement pendant la période d'abonnement correspondante, sauf disposition contraire expressément mentionnée dans l'offre souscrite. Les Tokens non utilisés à l'expiration de la période d'abonnement peuvent être perdus ou reportés selon les conditions spécifiques de l'offre souscrite. Les Tokens acquis « à la carte » sont valables pour une durée de douze (12) mois à compter de leur date d'acquisition.\n\n5.4 Non-remboursement : Conformément à l'article L. 221-28 du Code de la consommation, les Tokens constituent des contenus numériques non fournis sur un support matériel. En conséquence, l'achat de Tokens est définitif et non remboursable, quelle que soit la circonstance, y compris en cas de non-utilisation, de résiliation d'abonnement ou de fermeture de compte.\n\n5.5 Modalités de paiement : Les paiements sont traités par des prestataires de services de paiement tiers. En fournissant vos informations de paiement, vous garantissez que vous êtes autorisé à utiliser le mode de paiement choisi et vous autorisez Addax Media à vous facturer via ce mode de paiement. Addax Media n'est pas responsable des erreurs ou des frais imposés par votre établissement financier ou votre émetteur de carte.",
      subsections: []
    },
    {
      title: "6. Abonnements et renouvellement",
      text: "6.1 Souscription : La souscription à un abonnement s'effectue en ligne via le site adpulseai.com. L'abonnement prend effet à compter de la confirmation du paiement et reste valable pour la durée souscrite (mensuelle, trimestrielle ou annuelle).\n\n6.2 Renouvellement automatique : Sauf résiliation par l'Utilisateur dans les conditions prévues à l'article 6.3, l'abonnement est automatiquement renouvelé à l'issue de chaque période pour une période identique. L'Utilisateur sera débité automatiquement du montant correspondant à son abonnement via le mode de paiement initialement fourni.\n\n6.3 Résiliation par l'Utilisateur : L'Utilisateur peut résilier son abonnement à tout moment via son espace client ou en contactant le service client. La résiliation prendra effet à l'échéance de la période en cours, sans remboursement prorata temporis. L'Utilisateur conservera l'accès au Service jusqu'à la fin de la période en cours.\n\n6.4 Résiliation par Addax Media : Addax Media se réserve le droit de résilier unilatéralement tout abonnement en cas de violation des présentes CGU, de non-paiement, ou pour tout autre motif légitime. Dans ce cas, la résiliation prendra effet immédiatement, sans préavis ni remboursement.\n\n6.5 Conséquences de la résiliation : À l'issue de la résiliation, l'Utilisateur perdra l'accès aux fonctionnalités premium du Service et aux Tokens non utilisés. Les Contenus déjà générés et téléchargés par l'Utilisateur avant la résiliation resteront sa propriété conformément à l'article 8 des présentes CGU.",
      subsections: []
    },
    {
      title: "7. Propriété intellectuelle",
      text: "7.1 Propriété d'Addax Media : Addax Media et/ou ses concédants de licence sont et demeurent propriétaires de tous les droits, titres et intérêts relatifs au Service, y compris mais sans s'y limiter, les logiciels, les algorithmes, l'interface utilisateur, les marques, logos, noms commerciaux, noms de domaine et autres signes distinctifs associés au Service, ainsi que la technologie sous-jacente et tous les droits de propriété intellectuelle y afférents. Les présentes CGU ne confèrent à l'Utilisateur aucun droit de propriété sur le Service ou ses composants.\n\n7.2 Licence limitée : Addax Media accorde à l'Utilisateur, pendant la durée de son abonnement ou dans la limite des Tokens disponibles, une licence non exclusive, non transférable, non sous-licenciable et révocable d'accès et d'utilisation du Service, strictement pour son usage personnel ou professionnel interne, conformément aux présentes CGU.\n\n7.3 Propriété du Contenu généré : Sous réserve du paiement effectif des Tokens correspondants, le Contenu généré via le Service devient la propriété de l'Utilisateur, qui en acquiert tous les droits d'utilisation, de reproduction, de représentation, d'adaptation et d'exploitation. Toutefois, Addax Media conserve le droit d'utiliser de manière anonymisée les données relatives aux requêtes et aux Contenus générés afin d'améliorer ses algorithmes et la qualité du Service.\n\n7.4 Feedback et suggestions : Si l'Utilisateur soumet des commentaires, suggestions ou autres retours concernant le Service (« Feedback »), il accorde à Addax Media une licence mondiale, perpétuelle, irrévocable, transférable, sous-licenciable, libre de redevance et non exclusive pour utiliser, reproduire, modifier, créer des œuvres dérivées, distribuer et exploiter commercialement ce Feedback de quelque manière que ce soit, sans compensation ni attribution.",
      subsections: []
    },
    {
      title: "8. Garanties et responsabilités",
      text: "8.1 Absence de garanties : Le Service est fourni « tel quel » et « selon disponibilité », sans garantie d'aucune sorte, expresse ou implicite. Addax Media ne garantit pas que le Service sera ininterrompu, sécurisé, exempt d'erreurs ou de virus, ni que les défauts seront corrigés. Addax Media ne garantit pas non plus que le Contenu généré répondra aux attentes ou aux besoins spécifiques de l'Utilisateur, ni qu'il sera exact, complet, à jour, légal ou de qualité satisfaisante.\n\n8.2 Limitation de responsabilité : Dans toute la mesure permise par la loi applicable, Addax Media décline toute responsabilité pour tout dommage direct, indirect, accessoire, spécial, consécutif ou punitif, y compris mais sans s'y limiter, les pertes de profits, de données, d'opportunités commerciales, de réputation ou autres pertes intangibles, résultant de : (i) l'accès à ou l'utilisation du Service ou l'impossibilité d'y accéder ou de l'utiliser ; (ii) tout comportement ou contenu d'un tiers sur le Service ; (iii) tout Contenu obtenu via le Service ; (iv) tout accès non autorisé, utilisation ou altération des transmissions ou contenus de l'Utilisateur.\n\n8.3 Plafond d'indemnisation : En tout état de cause, la responsabilité globale de Addax Media envers l'Utilisateur pour toutes réclamations liées au Service est limitée au montant effectivement payé par l'Utilisateur à Addax Media au cours des douze (12) mois précédant l'événement donnant lieu à responsabilité.\n\n8.4 Indemnisation par l'Utilisateur : L'Utilisateur accepte de défendre, indemniser et dégager de toute responsabilité Addax Media, ses dirigeants, administrateurs, employés et agents contre toute réclamation, dommage, obligation, perte, responsabilité, coût ou dette, et dépense (y compris, mais sans s'y limiter, les honoraires d'avocat) découlant de : (i) l'utilisation du Service par l'Utilisateur ; (ii) la violation par l'Utilisateur des présentes CGU ; (iii) la violation par l'Utilisateur des droits d'un tiers, y compris, mais sans s'y limiter, les droits de propriété intellectuelle ; ou (iv) tout Contenu généré, publié ou partagé par l'Utilisateur via le Service.\n\n8.5 Force majeure : Aucune des parties ne sera responsable envers l'autre pour tout retard ou manquement dans l'exécution de ses obligations résultant d'un cas de force majeure, tel que défini à l'article 1218 du Code civil français.",
      subsections: []
    },
    {
      title: "9. Données personnelles et confidentialité",
      text: "9.1 Traitement des données personnelles : Addax Media collecte et traite les données personnelles des Utilisateurs conformément à sa Politique de Confidentialité. Cette politique détaille les catégories de données collectées, les finalités du traitement, les destinataires des données, les durées de conservation, ainsi que les droits des Utilisateurs et les modalités d'exercice de ces droits.\n\n9.2 Sous-traitants : Addax Media peut faire appel à des sous-traitants pour l'exécution de certaines prestations nécessaires au fonctionnement du Service. Ces sous-traitants sont soumis à des obligations strictes de confidentialité et de sécurité concernant les données personnelles auxquelles ils peuvent avoir accès.\n\n9.3 Transferts internationaux : Les données personnelles des Utilisateurs peuvent être transférées vers des pays situés en dehors de l'Union Européenne. Dans ce cas, Addax Media s'assure que ces transferts sont effectués vers des pays offrant un niveau de protection adéquat ou sont encadrés par des garanties appropriées conformément au Règlement Général sur la Protection des Données (RGPD).\n\n9.4 Confidentialité des contenus : Addax Media s'engage à préserver la confidentialité des Contenus générés par les Utilisateurs et à ne pas les divulguer à des tiers sans autorisation, sauf obligation légale ou judiciaire. Toutefois, l'Utilisateur reconnaît que Addax Media peut utiliser de manière anonymisée les données relatives aux requêtes et aux Contenus générés afin d'améliorer ses algorithmes et la qualité du Service.",
      subsections: []
    },
    {
      title: "10. Modifications des CGU",
      text: "10.1 Droit de modification : Addax Media se réserve le droit, à sa seule discrétion, de modifier, compléter ou remplacer tout ou partie des présentes CGU à tout moment. Les modifications peuvent être effectuées pour des raisons légales, pour refléter des changements dans le Service ou pour toute autre raison jugée nécessaire par Addax Media.\n\n10.2 Notification des modifications : Addax Media notifiera les Utilisateurs des modifications substantielles apportées aux CGU par email et/ou par un avis visible sur le Service. Pour les modifications mineures, Addax Media pourra se contenter de mettre à jour la date de « dernière mise à jour » figurant en tête des CGU.\n\n10.3 Entrée en vigueur : Les modifications des CGU entrent en vigueur dès leur publication sur le Service, sauf indication contraire. La continuation de l'utilisation du Service après la publication des CGU modifiées constitue l'acceptation de ces modifications par l'Utilisateur.\n\n10.4 Droit de refus : Si l'Utilisateur n'accepte pas les CGU modifiées, il doit cesser d'utiliser le Service et, le cas échéant, résilier son abonnement conformément à l'article 6.3 des présentes CGU.",
      subsections: []
    },
    {
      title: "11. Dispositions diverses",
      text: "11.1 Intégralité de l'accord : Les présentes CGU, ainsi que la Politique de Confidentialité et toute condition particulière applicable, constituent l'intégralité de l'accord entre l'Utilisateur et Addax Media concernant l'utilisation du Service et remplacent tous les accords antérieurs ou contemporains, écrits ou oraux, relatifs à l'objet des présentes.\n\n11.2 Divisibilité : Si une disposition des présentes CGU est jugée illégale, nulle ou inapplicable, en tout ou en partie, par un tribunal compétent, cette disposition sera modifiée et interprétée de manière à atteindre au mieux les objectifs de la disposition originale dans les limites permises par la loi, et les autres dispositions des CGU resteront pleinement en vigueur.\n\n11.3 Renonciation : Le fait pour Addax Media de ne pas exercer ou faire valoir un droit ou une disposition des présentes CGU ne constitue pas une renonciation à ce droit ou à cette disposition. Aucune renonciation par Addax Media à une quelconque obligation de l'Utilisateur en vertu des présentes CGU ne sera considérée comme une renonciation continue ou une renonciation à toute autre obligation.\n\n11.4 Cession : L'Utilisateur ne peut céder ou transférer les présentes CGU, en tout ou en partie, sans le consentement écrit préalable de Addax Media. Addax Media peut céder ou transférer les présentes CGU, en tout ou en partie, sans restriction et sans notification préalable à l'Utilisateur.\n\n11.5 Notifications : Toutes les notifications requises ou autorisées en vertu des présentes CGU seront effectuées par écrit et seront considérées comme dûment délivrées lorsqu'elles seront envoyées par email à l'adresse fournie par l'Utilisateur lors de son inscription ou à l'adresse support@adpulse-ai.com pour les notifications destinées à Addax Media.\n\n11.6 Survie : Les dispositions des présentes CGU qui, par leur nature, devraient survivre à la résiliation ou à l'expiration des CGU, survivront à une telle résiliation ou expiration, y compris, mais sans s'y limiter, les dispositions relatives à la propriété intellectuelle, aux garanties et responsabilités, à l'indemnisation et au règlement des litiges.",
      subsections: []
    },
    {
      title: "12. Droit applicable et juridiction compétente",
      text: "12.1 Droit applicable : Les présentes CGU sont régies et interprétées conformément au droit français, sans égard aux principes de conflits de lois.\n\n12.2 Règlement amiable des litiges : En cas de litige relatif à l'interprétation, l'exécution ou la résiliation des présentes CGU, les parties s'efforceront de résoudre leur différend à l'amiable. L'Utilisateur est invité à contacter en priorité le service client de Addax Media à l'adresse support@adpulse-ai.com afin de rechercher une solution amiable.\n\n12.3 Médiation : Conformément aux articles L. 611-1 et suivants du Code de la consommation, l'Utilisateur consommateur a le droit de recourir gratuitement à un médiateur de la consommation en vue de la résolution amiable d'un litige l'opposant à Addax Media. Addax Media adhère au service du médiateur Médiation-Net, que l'Utilisateur peut contacter à l'adresse suivante : Médiation-Net, 34 rue des Épinettes, 75017 Paris, France. Site web : www.mediation-net.com, email : contact@mediation-net.com.\n\n12.4 Juridiction compétente : À défaut de résolution amiable, tout litige relatif à la validité, l'interprétation ou l'exécution des présentes CGU sera soumis à la compétence exclusive des tribunaux français, sauf disposition légale impérative contraire. Pour les Utilisateurs agissant en qualité de commerçants, tout litige sera soumis à la compétence exclusive du Tribunal de Commerce de Paris.\n\n12.5 Action collective : Dans toute la mesure permise par la loi applicable, l'Utilisateur renonce expressément à tout droit de participer à une action collective ou à un recours collectif contre Addax Media concernant l'utilisation du Service ou les présentes CGU.",
      subsections: []
    },
    {
      title: "13. Contact et service client",
      text: "Pour toute question concernant les présentes CGU ou le Service, l'Utilisateur peut contacter Addax Media aux coordonnées suivantes :\n\nAddax Media Ltd\nFlat 5, 9 Langley Road\nWatford, England, WD17 4PS\nEmail : support@adpulse-ai.com\nTéléphone : (803) 886-0993\n\nLe service client est disponible du lundi au vendredi, de 9h à 18h (heure de Paris), hors jours fériés.\n\nDernière mise à jour des CGU : 25/09/2024",
      subsections: []
    }
  ]
}; 