const companyInfo = {
  name: "Hirola Media Ltd",
  number: "16312592",
  address: "137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ"
};

export const termsContent = {
  title: "Conditions Générales d'Utilisation",
  content: [
    {
      title: "1. Introduction",
      text: `Les présentes Conditions Générales d'Utilisation (ci-après les "CGU") régissent l'utilisation du site FlirtSage AI (ci-après le "Site") et des services (ci-après le "Service") fournis par Hirola Media Ltd, société enregistrée en Angleterre sous le numéro 16312592, dont le siège social est situé au 137 Fletcher Way, Hemel Hempstead, England, HP2 5RZ (ci-après "Hirola Media", "nous" ou "notre").`
    },
    {
      title: "1.1 Dispositions préliminaires et définitions",
      text: `En accédant au Site et en utilisant le Service, vous acceptez d'être lié par les présentes CGU, créant ainsi un contrat juridiquement contraignant entre vous et Hirola Media.\n\nSi vous n'acceptez pas les présentes CGU, vous ne devez pas utiliser le Site ou le Service.\n\nAux fins des présentes CGU, les définitions suivantes s'appliquent :\n\n- "Service" désigne la plateforme FlirtSage AI, accessible via le site flirtsage-ai.com, permettant aux utilisateurs de recevoir des conseils personnalisés en séduction via une intelligence artificielle.\n\n- "Contenu" désigne tous les textes, images, vidéos, sons, et autres matériels fournis par l'Utilisateur ou générés par le Service.\n\n- "Token" désigne l'unité de crédit permettant d'utiliser les différentes fonctionnalités du Service.\n\n- "Utilisateur" ou "vous" désigne toute personne qui accède au Site et utilise le Service.`
    },
    {
      title: "2. Objet et description du Service",
      text: "FlirtSage AI est une plateforme de coaching en séduction propulsée par l'intelligence artificielle, accessible via le site internet FlirtSage AI. Le Service permet aux Utilisateurs d'obtenir des conseils et un coaching personnalisé en matière de séduction moyennant l'utilisation de Tokens. Hirola Media se réserve le droit, à sa seule discrétion et sans notification préalable, de modifier, suspendre, restreindre ou interrompre, temporairement ou définitivement, tout ou partie du Service, y compris mais sans s'y limiter, les fonctionnalités disponibles, les interfaces utilisateur, les algorithmes de génération, la tarification et les modalités d'accès. Ces modifications peuvent être effectuées pour des raisons techniques, commerciales, légales ou pour tout autre motif jugé pertinent par Hirola Media. L'Utilisateur reconnaît que Hirola Media n'encourra aucune responsabilité envers lui ou tout tiers pour toute modification, suspension ou interruption du Service."
    },
    {
      title: "3. Compte Utilisateur",
      text: "3.1 Création de compte : Pour accéder aux fonctionnalités complètes du Service, vous devez créer un compte utilisateur en fournissant des informations exactes, complètes et à jour. Vous devez avoir au moins 18 ans ou la majorité légale dans votre juridiction, selon laquelle est la plus élevée, pour créer un compte.\n\n3.2 Informations personnelles : Vous êtes responsable de la mise à jour de vos informations personnelles afin qu'elles restent exactes et complètes. Vous vous engagez à informer Hirola Media de tout changement concernant ces informations en cas de modification. Hirola Media se réserve le droit de vérifier l'exactitude des informations fournies et de suspendre ou supprimer tout compte contenant des informations inexactes, incomplètes ou frauduleuses.\n\n3.3 Sécurité du compte : Vous êtes seul responsable de la confidentialité de vos identifiants de connexion (adresse e-mail et mot de passe) et de toutes les activités qui se déroulent sur votre compte. Vous vous engagez à choisir un mot de passe suffisamment robuste, à ne pas le divulguer à des tiers et à vous déconnecter à la fin de chaque session. L'Utilisateur s'engage à notifier immédiatement Hirola Media de toute utilisation non autorisée de son compte ou de toute autre violation de sécurité. Hirola Media ne pourra être tenue responsable des pertes ou dommages résultant du non-respect par l'Utilisateur de ces obligations de sécurité."
    },
    {
      title: "4. Utilisation du Service",
      text: "4.1 Utilisation autorisée : En utilisant le Service, vous vous engagez à respecter toutes les lois et réglementations applicables. Il est notamment interdit d'utiliser le Service pour créer, publier, transmettre ou stocker du contenu : illégal, frauduleux, trompeur ou mensonger ; diffamatoire, obscène, pornographique ou contraire aux bonnes mœurs ; violant les droits de propriété intellectuelle de tiers ; constituant du harcèlement, des menaces ou de l'intimidation ; encourageant la discrimination, le racisme, la haine ou la violence contre un individu ou un groupe ; contenant des virus, des chevaux de Troie ou tout autre code malveillant.\n\n4.2 Responsabilité du Contenu : L'Utilisateur est pleinement responsable du fait du Contenu généré via le Service. Hirola Media ne garantit pas l'exactitude, la pertinence, la qualité ou la légalité du Contenu généré. L'Utilisateur s'engage à vérifier et, si nécessaire, à modifier le Contenu généré avant toute utilisation ou publication. Hirola Media décline expressément toute responsabilité quant aux conséquences directes ou indirectes de l'utilisation du Contenu généré par l'Utilisateur.\n\n4.3 Restrictions techniques : L'Utilisateur s'engage à ne pas : tenter de contourner, désactiver ou interférer avec les fonctionnalités de sécurité du Service ; utiliser des robots, des scrapers ou d'autres moyens automatisés pour accéder au Service ; interférer avec ou perturber l'intégrité ou les performances du Service ; créer plusieurs comptes pour contourner les limitations d'utilisation ; revendre, louer, prêter ou transférer son accès au Service à des tiers ; utiliser le Service à des fins non autorisées par Hirola Media."
    },
    {
      title: "5. Tokens et Paiements",
      text: "5.1 Système de Tokens : L'accès aux fonctionnalités de génération de contenu du Service nécessite l'utilisation de Tokens. Les Tokens peuvent être acquis via un abonnement récurrent ou à l'unité (« à la carte »). Le nombre de Tokens requis pour générer du contenu varie en fonction du type et de la longueur du contenu demandé.\n\n5.2 Tarifs : Les tarifs applicables aux différentes formules d'abonnement et aux achats à l'unité sont ceux en vigueur au moment de l'achat, tels qu'indiqués sur le site. Hirola Media se réserve le droit de modifier ses tarifs à tout moment, moyennant un préavis de trente (30) jours pour les abonnements en cours.\n\n5.3 Validité des Tokens : Les Tokens acquis via un abonnement sont valables pendant la durée de l'abonnement. Les Tokens non utilisés à la fin de la période d'abonnement peuvent être perdus ou reportés sur la période suivante, selon les conditions spécifiques de l'offre souscrite. Les Tokens achetés à l'unité sont valables pour une durée de douze (12) mois à compter de leur date d'achat, sauf indication contraire.\n\n5.4 Non-remboursement : Les Tokens achetés ne sont pas remboursables, même s'ils n'ont pas été utilisés. Pour plus de détails, veuillez consulter notre Politique de Remboursement.\n\n5.5 Modalités de paiement : Nous acceptons différents modes de paiement, notamment les cartes de crédit, les virements bancaires et certains portefeuilles électroniques, selon les pays. En fournissant vos informations de paiement, vous garantissez que vous êtes autorisé à utiliser le mode de paiement choisi et vous autorisez Hirola Media à vous facturer via ce mode de paiement. Hirola Media n'est pas responsable des erreurs ou des frais imposés par votre établissement financier ou votre émetteur de carte."
    },
    {
      title: "6. Abonnements",
      text: "6.1 Souscription : La souscription à un abonnement s'effectue en ligne via le site flirtsage-ai.com. L'abonnement prend effet à compter de la confirmation du paiement et reste valable pour la durée souscrite (mensuelle, trimestrielle ou annuelle).\n\n6.2 Renouvellement automatique : Sauf indication contraire lors de la souscription, les abonnements sont automatiquement renouvelés à l'échéance pour une période identique à celle initialement souscrite. Vous serez débité automatiquement du montant de l'abonnement à chaque date de renouvellement, sauf si vous résiliez votre abonnement avant cette date.\n\n6.3 Résiliation par l'Utilisateur : Vous pouvez résilier votre abonnement à tout moment via votre espace client. La résiliation prendra effet à la fin de la période en cours.\n\n6.4 Résiliation par Hirola Media : Hirola Media se réserve le droit de résilier unilatéralement tout abonnement en cas de violation des présentes CGU, de non-paiement, ou pour tout autre motif légitime. Dans ce cas, la résiliation prendra effet immédiatement ou à la date indiquée dans la notification de résiliation."
    },
    {
      title: "7. Propriété intellectuelle",
      text: `7.1 Titularité des droits sur le Service : Hirola Media est titulaire de tous les droits de propriété intellectuelle relatifs au Service FlirtSage AI. Le Site, le Service et leur contenu (textes, images, logos, marques, logiciels, bases de données, etc.) sont protégés par le droit d'auteur, le droit des marques, le droit des bases de données et tout autre droit de propriété intellectuelle. Aucune disposition des présentes CGU ne peut être interprétée comme opérant un transfert de droits de propriété intellectuelle au bénéfice de l'Utilisateur.\n\n7.2 Licence d'utilisation : Hirola Media concède à l'Utilisateur, pendant la durée de son abonnement ou de son utilisation du Service, une licence personnelle, non exclusive, non transférable et non sous-licenciable d'accès et d'utilisation du Service, strictement limitée à l'usage autorisé par les présentes CGU.\n\n7.3 Droits sur le Contenu généré : Les Contenus générés par le Service à la demande de l'Utilisateur sont mis à disposition de l'Utilisateur qui peut les utiliser pour ses besoins personnels ou professionnels. Toutefois, Hirola Media conserve tous les droits de propriété intellectuelle relatifs aux technologies, algorithmes et méthodes utilisés pour générer ces Contenus.\n\n7.4 Feedback des Utilisateurs : En fournissant des suggestions, idées, commentaires ou autres feedbacks concernant le Service (ci-après le "Feedback"), l'Utilisateur accorde à Hirola Media une licence mondiale, perpétuelle, irrévocable, gratuite et non exclusive pour utiliser, reproduire, modifier, adapter, publier, traduire, créer des œuvres dérivées, distribuer et exploiter ce Feedback sans restriction, y compris à des fins commerciales, sans que l'Utilisateur ne puisse prétendre à une quelconque rémunération.`
    },
    {
      title: "8. Garanties et responsabilité",
      text: "8.1 Absence de garantie : Le Service est fourni « tel quel » et « selon disponibilité », sans garantie d'aucune sorte, expresse ou implicite. Hirola Media ne garantit pas que le Service sera ininterrompu, sécurisé, exempt d'erreurs ou de virus, ni que les défauts seront corrigés. Hirola Media ne garantit pas non plus que le Contenu généré répondra aux attentes ou aux besoins spécifiques de l'Utilisateur, ni qu'il sera exact, complet, à jour, légal ou de qualité satisfaisante.\n\n8.2 Limitation de responsabilité : Dans toute la mesure permise par la loi applicable, Hirola Media décline toute responsabilité pour tout dommage direct, indirect, accessoire, spécial, consécutif ou punitif, y compris mais sans s'y limiter, les pertes de profits, de données, d'opportunités commerciales, de réputation ou autres pertes intangibles, résultant de : (a) l'utilisation ou l'impossibilité d'utiliser le Service ; (b) tout Contenu généré via le Service ; (c) toute conduite ou tout contenu d'un tiers sur le Service ; (d) tout accès non autorisé, utilisation ou altération de vos transmissions ou contenus.\n\n8.3 Plafond de responsabilité : Nonobstant toute disposition contraire dans les présentes CGU et quelle que soit la cause de l'action ou la théorie de cause, la responsabilité globale de Hirola Media envers l'Utilisateur pour toutes réclamations liées au Service est limitée au montant effectivement payé par l'Utilisateur à Hirola Media au cours des douze (12) mois précédant l'événement donnant lieu à responsabilité.\n\n8.4 Indemnisation par l'Utilisateur : L'Utilisateur accepte de défendre, indemniser et dégager de toute responsabilité Hirola Media, ses dirigeants, administrateurs, employés et agents contre toute réclamation, dommage, obligation, perte, responsabilité, coût ou dette, et dépense (y compris, mais sans s'y limiter, les honoraires d'avocat) résultant de : (a) son utilisation du Service ; (b) sa violation des présentes CGU ; (c) sa violation des droits d'un tiers, y compris, mais sans s'y limiter, les droits de propriété intellectuelle ; ou (d) tout Contenu généré ou publié par lui."
    },
    {
      title: "9. Protection des données",
      text: "9.1 Traitement des données personnelles : Hirola Media collecte et traite les données personnelles des Utilisateurs conformément à sa Politique de Confidentialité. Cette politique détaille les catégories de données collectées, les finalités du traitement, les destinataires des données, les mesures de sécurité mises en œuvre, ainsi que les droits dont disposent les Utilisateurs et les modalités d'exercice de ces droits.\n\n9.2 Sous-traitants : Hirola Media peut faire appel à des sous-traitants pour l'exécution de certaines prestations nécessaires au fonctionnement du Service. Ces sous-traitants sont soumis à des obligations strictes de confidentialité et de sécurité concernant les données personnelles qu'ils pourraient être amenés à traiter.\n\n9.3 Transferts internationaux : Certaines données personnelles peuvent être transférées vers des serveurs ou des sous-traitants situés hors de l'Union Européenne. Dans ce cas, Hirola Media s'assure que ces transferts sont effectués vers des pays offrant un niveau de protection adéquat ou sont encadrés par des garanties appropriées conformément au Règlement Général sur la Protection des Données (RGPD).\n\n9.4 Confidentialité des contenus : Hirola Media s'engage à préserver la confidentialité des Contenus générés par les Utilisateurs et à ne pas les divulguer à des tiers sans autorisation, sauf obligation légale ou judiciaire. Toutefois, l'Utilisateur reconnaît que Hirola Media peut utiliser de manière anonymisée les données relatives aux requêtes et aux Contenus générés afin d'améliorer ses algorithmes et la qualité du Service."
    },
    {
      title: "10. Modification des CGU",
      text: "10.1 Droit de modification : Hirola Media se réserve le droit, à sa seule discrétion, de modifier, compléter ou remplacer tout ou partie des présentes CGU à tout moment. Les modifications peuvent être effectuées pour des raisons légales, pour refléter des changements dans le Service ou pour toute autre raison jugée nécessaire par Hirola Media.\n\n10.2 Notification des modifications : Hirola Media notifiera les Utilisateurs des modifications substantielles apportées aux CGU par email et/ou par un avis visible sur le Service. Pour les modifications mineures, Hirola Media pourra se contenter de mettre à jour la date de « dernière mise à jour » figurant en tête des CGU.\n\n10.3 Entrée en vigueur : Les modifications des CGU entrent en vigueur dès leur publication sur le Service, sauf indication contraire. En continuant à utiliser le Service après la publication des modifications, l'Utilisateur accepte d'être lié par les CGU modifiées.\n\n10.4 Droit d'opposition : Si l'Utilisateur n'accepte pas les CGU modifiées, il doit cesser d'utiliser le Service et supprimer son compte. L'utilisation continue du Service après l'entrée en vigueur des modifications vaut acceptation de ces modifications."
    },
    {
      title: "11. Dispositions diverses",
      text: "11.1 Intégralité de l'accord : Les présentes CGU, ainsi que la Politique de Confidentialité et la Politique de Remboursement, constituent l'intégralité de l'accord entre l'Utilisateur et Hirola Media concernant l'utilisation du Service et remplacent tous les accords antérieurs ou contemporains, écrits ou oraux, relatifs à l'objet des présentes.\n\n11.2 Divisibilité : Si une disposition des présentes CGU est jugée illégale, nulle ou inapplicable pour quelque raison que ce soit, cette disposition sera limitée ou éliminée des présentes CGU dans la mesure minimale nécessaire, et les autres dispositions resteront pleinement en vigueur.\n\n11.3 Renonciation : Le fait pour Hirola Media de ne pas exercer ou faire valoir un droit ou une disposition des présentes CGU ne constitue pas une renonciation à ce droit ou à cette disposition. Aucune renonciation par Hirola Media à une quelconque obligation de l'Utilisateur en vertu des présentes CGU ne sera considérée comme une renonciation continue ou une renonciation à toute autre obligation.\n\n11.4 Cession : L'Utilisateur ne peut céder ou transférer les présentes CGU, en tout ou en partie, sans le consentement écrit préalable de Hirola Media. Hirola Media peut céder ou transférer les présentes CGU, en tout ou en partie, sans restriction et sans notification préalable à l'Utilisateur.\n\n11.5 Notifications : Toutes les notifications requises ou autorisées en vertu des présentes CGU seront adressées par email à l'adresse électronique fournie par l'Utilisateur lors de son inscription ou à l'adresse support@flirtsageai pour les notifications destinées à Hirola Media.\n\n11.6 Survie : Les dispositions des présentes CGU qui, par leur nature, devraient survivre à la résiliation ou à l'expiration des CGU, survivront à une telle résiliation ou expiration, y compris, mais sans s'y limiter, les dispositions relatives à la propriété intellectuelle, aux garanties, à la limitation de responsabilité et à l'indemnisation."
    },
    {
      title: "21. Droit applicable et juridiction compétente",
      text: "21.1 Droit applicable : Les présentes CGU sont régies par le droit britannique (UK). Elles sont rédigées en langue française. Dans le cas où elles seraient traduites en une ou plusieurs langues, seul le texte français ferait foi en cas de litige.\n\n21.2 Règlement amiable des litiges : En cas de litige relatif à l'interprétation ou à l'exécution des présentes CGU, les parties s'efforceront de trouver une solution amiable avant toute action judiciaire.\n\n21.3 Juridiction compétente : À défaut de résolution amiable, tout litige relatif aux présentes CGU sera soumis à la compétence exclusive des tribunaux britanniques, sauf disposition légale impérative contraire. Pour les utilisateurs agissant en qualité de commerçants, tout litige sera soumis à la compétence exclusive des tribunaux de Londres."
    },
    {
      title: "25. Contact et service client",
      text: "Pour toute question concernant les présentes CGU ou le Service, l'Utilisateur peut contacter Hirola Media à l'adresse email suivante : support@flirtsageai.\n\nDernière mise à jour : 25/03/2024"
    }
  ]
}; 