export const legalContent = {
  title: "Informations Légales",
  content: [
    {
      title: "1. Éditeur du Site",
      text: "Ce site web (ci-après \"le Site\") est édité par Jastro Limited, une société enregistrée au Royaume-Uni sous le numéro 836841, dont le siège social est situé à Suite 10 12 Durie Street, Leven, Fife, Royaume-Uni, KY8 4HE.\n\nDate de constitution: 07/02/2025\nTéléphone: (850) 783-4170\nEmail: support@fitnessbrainai.com"
    },
    {
      title: "2. Directeur de la Publication",
      text: "Le Directeur de la Publication du Site est le représentant légal de Jastro Limited.\n\nContact: support@fitnessbrainai.com\nTéléphone: (850) 783-4170"
    },
    {
      title: "3. Hébergement",
      text: "Le Site est hébergé par Vercel Inc., 340 S Lemon Ave #4133, Walnut, CA 91789, États-Unis.\n\nSite web de l'hébergeur: https://vercel.com\n\nPour toute demande concernant l'hébergement, veuillez contacter: support@fitnessbrainai.com"
    },
    {
      title: "4. Propriété Intellectuelle",
      text: "4.1 Propriété des Droits: Tous les éléments constituant le Site et le Service FitnessBrainAI (y compris les textes, graphiques, logiciels, photographies, images, vidéos, sons, plans, logos, marques, noms de domaine et tout autre élément distinctif) sont protégés par les lois et réglementations britanniques et internationales relatives à la propriété intellectuelle. Ces éléments restent la propriété exclusive de Jastro Limited et/ou de ses concédants de licence.\n\n4.2 Reproduction Non Autorisée Interdite: Toute reproduction, représentation, modification, publication, adaptation, exploitation de tout ou partie des éléments du Site, quel que soit le moyen ou le procédé utilisé, est strictement interdite sans autorisation écrite préalable de Jastro Limited. Toute exploitation non autorisée du Site ou de l'un de ses éléments sera considérée comme constitutive d'une contrefaçon et poursuivie conformément aux dispositions légales applicables.\n\n4.3 Marques et Noms Commerciaux: Les marques et noms commerciaux figurant sur le Site sont des marques déposées de Jastro Limited. Toute reproduction ou utilisation de ces marques sans autorisation écrite préalable de Jastro Limited est interdite.\n\n4.4 Liens vers le Site: La création d'un lien hypertexte vers le Site ne nécessite pas d'autorisation écrite préalable de Jastro Limited. Toutefois, Jastro Limited se réserve le droit de demander la suppression d'un lien si elle considère que le site source ne respecte pas ses valeurs ou nuit à son image."
    },
    {
      title: "5. Protection des Données Personnelles",
      text: "5.1 Responsable du Traitement: Jastro Limited, en tant que responsable du traitement au sens du UK GDPR et du Data Protection Act 2018, s'engage à protéger la vie privée des utilisateurs du Site et à assurer la confidentialité des informations personnelles fournies.\n\n5.2 Délégué à la Protection des Données: Jastro Limited a nommé un Délégué à la Protection des Données que vous pouvez contacter pour toute question concernant le traitement de vos données personnelles:\n\nPar email: support@fitnessbrainai.com\nPar courrier: Jastro Limited - Délégué à la Protection des Données, Suite 10 12 Durie Street, Leven, Fife, Royaume-Uni, KY8 4HE\n\n5.3 Droits des Personnes Concernées: En vertu de la législation applicable en matière de protection des données, vous disposez de droits concernant vos données personnelles, notamment le droit d'accès, de rectification, d'effacement, de limitation du traitement, de portabilité des données, d'opposition, et le droit de définir des directives concernant le sort de vos données après votre décès.\n\n5.4 Politique de Confidentialité: Pour des informations détaillées sur la collecte, l'utilisation et la protection de vos données personnelles, veuillez consulter notre Politique de Confidentialité disponible à l'adresse suivante: https://fitnessbrainai.com/privacy"
    },
    {
      title: "6. Cookies et Technologies Similaires",
      text: "6.1 Définition: Un cookie est un petit fichier texte placé sur votre appareil (ordinateur, tablette, smartphone) lorsque vous visitez notre Site ou utilisez notre Service. Les cookies nous permettent de reconnaître votre navigateur et de collecter certaines informations sur votre navigation.\n\n6.2 Types de Cookies Utilisés: Notre Site utilise différents types de cookies:\n- Cookies strictement nécessaires au fonctionnement du Site\n- Cookies de fonctionnalité pour mémoriser vos préférences\n- Cookies d'analyse pour comprendre comment vous utilisez notre Site\n- Cookies de ciblage/publicité pour vous offrir un contenu personnalisé\n\n6.3 Base Juridique: Les cookies strictement nécessaires au fonctionnement du Site sont placés sur la base de notre intérêt légitime. Les autres types de cookies ne sont placés qu'après avoir obtenu votre consentement préalable, que vous pouvez retirer à tout moment.\n\n6.4 Gestion des Cookies: Vous pouvez à tout moment configurer votre navigateur pour accepter, refuser ou supprimer tout ou partie des cookies. Vous pouvez également utiliser notre panneau de gestion des cookies accessible via le lien 'Paramètres des Cookies' présent au bas de chaque page de notre Site.\n\n6.5 Politique de Cookies: Pour des informations détaillées sur les cookies que nous utilisons, leurs finalités, durées de conservation et tiers y ayant accès, veuillez consulter notre Politique de Cookies disponible à l'adresse suivante: https://fitnessbrainai.com/cookies"
    },
    {
      title: "7. Limitation de Responsabilité",
      text: "7.1 Exactitude des Informations: Jastro Limited s'efforce d'assurer l'exactitude et la mise à jour des informations diffusées sur le Site au mieux de ses capacités. Toutefois, Jastro Limited ne peut garantir l'exactitude, la précision, l'exhaustivité ou l'adéquation des informations mises à disposition sur le Site pour des fins particulières. Par conséquent, Jastro Limited décline toute responsabilité pour toute inexactitude, imprécision ou omission concernant les informations disponibles sur le Site.\n\n7.2 Disponibilité du Site: Jastro Limited s'efforce de maintenir le Site accessible 24 heures sur 24 et 7 jours sur 7. Toutefois, Jastro Limited ne peut être tenue responsable de l'indisponibilité du Site, pour quelque raison que ce soit, y compris la maintenance nécessaire au bon fonctionnement du Site ou un cas de force majeure.\n\n7.3 Sécurité Informatique: L'utilisateur du Site reconnaît être conscient des caractéristiques et des limites d'Internet, notamment ses performances techniques, les temps de réponse pour consulter, interroger ou transférer des données, et les risques de sécurité liés aux communications. Jastro Limited ne peut être tenue responsable des dommages directs ou indirects, matériels ou immatériels, résultant notamment de l'utilisation du Site ou de l'impossibilité d'y accéder, d'un dysfonctionnement, d'une interruption ou d'un virus informatique.\n\n7.4 Limitation Générale: Dans toute la mesure permise par la loi applicable, la responsabilité de Jastro Limited est limitée aux dommages directs, à l'exclusion de tout dommage indirect de quelque nature que ce soit."
    },
    {
      title: "8. Liens Hypertextes vers des Sites Tiers",
      text: "8.1 Liens Externes: Le Site peut contenir des liens hypertextes redirigeant vers des sites web publiés et/ou gérés par des tiers. Jastro Limited ne pouvant exercer aucun contrôle sur ces sites tiers, Jastro Limited ne peut être tenue responsable de l'accès à ces sites et sources externes, de leur contenu, publicités, produits, services ou tout autre élément disponible sur ou à partir de ces sites ou sources externes.\n\n8.2 Absence de Responsabilité: Jastro Limited décline toute responsabilité quant au contenu, à la légalité, à l'exactitude ou à la disponibilité des informations, produits, services ou tout autre élément présent sur ces sites tiers. L'insertion de ces liens n'implique pas que Jastro Limited approuve les éléments contenus sur ces sites. Il appartient à l'utilisateur de prendre toutes les précautions nécessaires pour s'assurer que le site tiers sélectionné ne contient pas de virus informatiques ou d'éléments susceptibles d'endommager son équipement informatique ou ses données.\n\n8.3 Signalement de Contenu Illicite: Si vous constatez qu'un site vers lequel Jastro Limited a créé un lien permet d'accéder à un contenu illicite, vous êtes invité à le signaler immédiatement à Jastro Limited à l'adresse suivante: support@fitnessbrainai.com. Jastro Limited s'engage à supprimer rapidement tout lien vers un contenu manifestement illicite dès qu'elle en aura connaissance."
    },
    {
      title: "9. Loi Applicable et Juridiction Compétente",
      text: "9.1 Loi Applicable: Ces informations légales sont régies par le droit anglais. Elles sont rédigées en français. En cas de traduction dans une ou plusieurs autres langues, seul le texte français prévaudra en cas de litige.\n\n9.2 Résolution Amiable: En cas de litige concernant l'interprétation ou l'exécution de ces informations légales, les parties s'efforceront de trouver une solution amiable avant toute action judiciaire.\n\n9.3 Juridiction Compétente: À défaut de résolution amiable, tout litige relatif à ces informations légales sera soumis à la compétence exclusive des tribunaux anglais, sauf disposition légale impérative contraire."
    },
    {
      title: "10. Médiation et Résolution des Litiges",
      text: "10.1 Service de Médiation: Jastro Limited propose à ses clients un service de médiation pour la résolution amiable des litiges. Pour accéder à ce service, veuillez contacter notre service client à: support@fitnessbrainai.com.\n\n10.2 Plateforme de Résolution des Litiges en Ligne: Pour les litiges transfrontaliers, les consommateurs résidant dans l'Union européenne peuvent également utiliser la plateforme européenne de Résolution des Litiges en Ligne disponible à l'adresse suivante: https://ec.europa.eu/consumers/odr/"
    },
    {
      title: "11. Modifications des Informations Légales",
      text: "11.1 Droit de Modification: Jastro Limited se réserve le droit, à sa seule discrétion, de modifier, compléter ou remplacer ces informations légales à tout moment. Les utilisateurs du Site sont donc invités à les consulter régulièrement.\n\n11.2 Date d'Effet: Les modifications des informations légales prennent effet dès leur publication sur le Site. L'utilisation continue du Site après la publication des informations légales modifiées constitue l'acceptation de ces modifications.\n\nDernière mise à jour: 25/03/2024"
    }
  ]
}; 