export const termsContent = {
  title: "Conditions Générales d'Utilisation",
  lastUpdated: "5 février 2024",
  content: [
    {
      title: "1. Dispositions Préliminaires et Définitions",
      text: "Ces Conditions Générales d'Utilisation (ci-après désignées 'CGU') constituent un accord juridiquement contraignant entre vous, en tant que personne physique ou morale (ci-après désigné 'Utilisateur' ou 'vous'), et Jastro Limited, une société à responsabilité limitée enregistrée au Royaume-Uni sous le numéro 836841, ayant son siège social à Suite 10 12 Durie Street, Leven, Fife, Royaume-Uni, KY8 4HE (ci-après désignée 'Jastro', 'nous' ou 'notre'). En accédant, utilisant ou vous inscrivant sur notre plateforme, vous reconnaissez avoir lu, compris et accepté sans réserve ces CGU. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser notre service. Aux fins des présentes CGU, les termes suivants, lorsqu'ils sont utilisés avec une majuscule, auront la signification qui leur est attribuée ci-dessous : 'Service' désigne la plateforme FitnessBrainAI, ses fonctionnalités et tous les services associés ; 'Contenu' désigne tout texte, image, vidéo, audio ou autre matériel généré ou téléchargé sur la plateforme."
    },
    {
      title: "2. Objet et Description du Service",
      text: "FitnessBrainAI est une plateforme de coaching fitness et nutrition propulsée par l'IA, accessible via le site web fitnessbrainai.com. Le Service permet aux Utilisateurs d'obtenir des programmes d'entraînement personnalisés et des conseils nutritionnels adaptés à leurs objectifs et à leur condition physique.\n\nIMPORTANT - AVERTISSEMENT MÉDICAL : FitnessBrainAI n'est pas un service médical et ne remplace pas les conseils de professionnels de santé qualifiés. Avant de commencer tout programme d'entraînement ou de modifier votre alimentation, nous vous recommandons vivement de consulter votre médecin traitant ou un professionnel de santé qualifié, particulièrement si vous avez des problèmes de santé préexistants ou des conditions médicales spécifiques. Les conseils et recommandations fournis via notre plateforme sont génériques et ne tiennent pas compte de votre situation médicale personnelle. Jastro décline toute responsabilité en cas de blessure ou de problèmes de santé résultant de l'utilisation de notre Service.\n\nJastro se réserve le droit, à sa seule discrétion et sans préavis, de modifier, suspendre, restreindre ou interrompre, temporairement ou définitivement, tout ou partie du Service, y compris, mais sans s'y limiter, les fonctionnalités disponibles, les interfaces utilisateur, les algorithmes de génération, les tarifs et les méthodes d'accès. Ces modifications peuvent être effectuées pour des raisons techniques, commerciales, juridiques ou toute autre raison jugée pertinente par Jastro. L'Utilisateur reconnaît que Jastro ne sera pas responsable envers lui ou envers tout tiers pour toute modification, suspension ou interruption du Service."
    },
    {
      title: "3. Conditions d'Accès et d'Inscription",
      text: "3.1 Capacité Juridique : L'accès et l'utilisation du Service sont réservés aux personnes âgées de 18 ans ou plus ayant la pleine capacité juridique ou aux personnes morales dûment constituées. Si vous agissez pour le compte d'une personne morale, vous déclarez et garantissez que vous êtes dûment autorisé à agir au nom de cette entité et à la lier par les présentes CGU.\n\n3.2 Création de Compte : Pour accéder à toutes les fonctionnalités du Service, l'Utilisateur doit créer un compte en fournissant des informations exactes, complètes et à jour. L'Utilisateur s'engage à mettre à jour ces informations en cas de changement. Jastro se réserve le droit de vérifier l'exactitude des informations fournies et de suspendre ou supprimer tout compte contenant des informations inexactes, incomplètes ou frauduleuses.\n\n3.3 Sécurité du Compte : L'Utilisateur est seul responsable du maintien de la confidentialité de ses identifiants de connexion et de toutes les activités qui se produisent sous son compte. L'Utilisateur s'engage à notifier immédiatement Jastro de toute utilisation non autorisée de son compte ou de toute autre violation de sécurité. Jastro ne sera pas responsable des pertes ou dommages résultant du non-respect par l'Utilisateur de ces obligations de sécurité."
    },
    {
      title: "4. Conditions d'Utilisation du Service",
      text: "4.1 Utilisation Conforme : L'Utilisateur s'engage à utiliser le Service conformément aux présentes CGU, aux lois et réglementations applicables et aux droits des tiers. Il est strictement interdit d'utiliser le Service à des fins illégales, frauduleuses, diffamatoires, obscènes, menaçantes, abusives ou autrement répréhensibles. L'Utilisateur s'engage spécifiquement à ne pas : (i) violer les droits de propriété intellectuelle de tiers ; (ii) générer ou diffuser du contenu illégal, nuisible, trompeur, discriminatoire ou frauduleux ; (iii) transmettre des virus, chevaux de Troie, vers, bombes logiques ou autres codes malveillants ; (iv) tenter d'accéder sans autorisation à des systèmes ou réseaux connectés au Service ; (v) interférer avec ou perturber l'intégrité ou les performances du Service.\n\n4.2 Contenu Généré : L'Utilisateur est entièrement responsable de son utilisation du Contenu généré par le Service. Jastro ne garantit pas l'exactitude, la pertinence, la qualité ou la légalité du Contenu généré. L'Utilisateur s'engage à vérifier et, si nécessaire, à modifier le Contenu généré avant toute utilisation ou publication. Jastro décline expressément toute responsabilité pour les conséquences directes ou indirectes de l'utilisation par l'Utilisateur du Contenu généré.\n\n4.3 Restrictions Techniques : L'Utilisateur s'engage à ne pas contourner, désactiver ou interférer avec les fonctionnalités de sécurité du Service ou les fonctionnalités qui empêchent ou restreignent l'utilisation ou la copie de tout Contenu. Il s'engage également à ne pas utiliser de robots, d'araignées, de robots d'extraction ou d'autres moyens automatisés pour accéder au Service à des fins non autorisées par Jastro."
    },
    {
      title: "5. Abonnement et Tarification",
      text: "5.1 Tarification : Le Service est fourni sur la base d'un abonnement. Les frais applicables sont ceux en vigueur au moment de l'abonnement, tels qu'indiqués sur le site web. Jastro se réserve le droit de modifier ses tarifs à tout moment, sous réserve d'un préavis de trente (30) jours pour les abonnements en cours.\n\n5.2 Abonnement : L'abonnement au Service s'effectue en ligne via le site web fitnessbrainai.com. L'abonnement prend effet à la confirmation du paiement et reste valable pour la période souscrite (mensuelle, trimestrielle ou annuelle).\n\n5.3 Renouvellement Automatique : Sauf annulation par l'Utilisateur dans les conditions prévues à l'article 5.4, l'abonnement est automatiquement renouvelé à la fin de chaque période pour une période identique. L'Utilisateur sera automatiquement débité du montant correspondant à son abonnement via le mode de paiement initialement fourni.\n\n5.4 Annulation par l'Utilisateur : L'Utilisateur peut annuler son abonnement à tout moment via son espace client ou en contactant le service client. L'annulation prendra effet à la fin de la période en cours, sans remboursement au prorata. L'Utilisateur conservera l'accès au Service jusqu'à la fin de la période en cours.\n\n5.5 Annulation par Jastro : Jastro se réserve le droit de résilier unilatéralement tout abonnement en cas de violation des présentes CGU, de non-paiement ou de toute autre raison légitime. Dans ce cas, la résiliation prendra effet immédiatement, sans préavis ni remboursement.\n\n5.6 Modes de Paiement : Les paiements sont traités par des prestataires de services de paiement tiers. En fournissant vos informations de paiement, vous garantissez que vous êtes autorisé à utiliser le mode de paiement choisi et autorisez Jastro à vous facturer par ce mode de paiement. Jastro n'est pas responsable des erreurs ou des frais imposés par votre institution financière ou émetteur de carte."
    },
    {
      title: "6. Propriété Intellectuelle",
      text: "6.1 Propriété de Jastro : Jastro et/ou ses concédants de licence restent propriétaires de tous les droits, titres et intérêts sur le Service, y compris, mais sans s'y limiter, les logiciels, algorithmes, interface utilisateur, marques, logos, noms commerciaux, noms de domaine et autres signes distinctifs associés au Service, ainsi que la technologie sous-jacente et tous les droits de propriété intellectuelle connexes. Ces CGU n'accordent à l'Utilisateur aucun droit de propriété sur le Service ou ses composants.\n\n6.2 Licence Limitée : Jastro accorde à l'Utilisateur, pendant la durée de son abonnement, une licence non exclusive, non transférable, non sous-licenciable et révocable pour accéder et utiliser le Service, strictement pour son usage personnel ou interne à son entreprise, conformément aux présentes CGU.\n\n6.3 Contenu Généré : Sous réserve du paiement effectif des frais correspondants, le Contenu généré par le Service devient la propriété de l'Utilisateur, qui acquiert tous les droits d'utilisation, de reproduction, de représentation, d'adaptation et d'exploitation. Toutefois, Jastro se réserve le droit d'utiliser des données anonymisées liées aux requêtes et au Contenu généré pour améliorer ses algorithmes et la qualité du Service.\n\n6.4 Retours d'Information : Si l'Utilisateur soumet des commentaires, suggestions ou autres retours concernant le Service ('Retours'), il accorde à Jastro une licence mondiale, perpétuelle, irrévocable, transférable, sous-licenciable, libre de redevances et non exclusive pour utiliser, reproduire, modifier, créer des œuvres dérivées, distribuer et exploiter commercialement ces Retours de quelque manière que ce soit, sans compensation ni attribution."
    },
    {
      title: "7. Garanties et Responsabilités",
      text: "7.1 Absence de Garanties : Le Service est fourni 'tel quel' et 'selon disponibilité', sans aucune garantie de quelque nature que ce soit, expresse ou implicite. Jastro ne garantit pas que le Service sera ininterrompu, sécurisé, sans erreur ou sans virus, ou que les défauts seront corrigés. Jastro ne garantit pas non plus que le Contenu généré répondra aux attentes ou besoins spécifiques de l'Utilisateur, ou qu'il sera exact, complet, à jour, légal ou de qualité satisfaisante.\n\n7.2 Limitation de Responsabilité : Dans toute la mesure permise par la loi applicable, Jastro décline toute responsabilité pour tout dommage direct, indirect, accessoire, spécial, consécutif ou punitif, y compris, mais sans s'y limiter, la perte de profits, de données, d'opportunités commerciales, de réputation ou d'autres pertes immatérielles, résultant de : (i) l'accès ou l'utilisation du Service ou l'impossibilité d'y accéder ou de l'utiliser ; (ii) tout comportement ou contenu de tiers sur le Service ; (iii) tout Contenu obtenu via le Service ; (iv) tout accès, utilisation ou altération non autorisé des transmissions ou du contenu de l'Utilisateur.\n\n7.3 Plafond d'Indemnisation : En tout état de cause, la responsabilité totale de Jastro envers l'Utilisateur pour toutes les réclamations liées au Service est limitée au montant effectivement payé par l'Utilisateur à Jastro au cours des douze (12) mois précédant l'événement donnant lieu à la responsabilité.\n\n7.4 Indemnisation par l'Utilisateur : L'Utilisateur s'engage à défendre, indemniser et tenir indemne Jastro, ses dirigeants, administrateurs, employés et agents de toute réclamation, dommage, obligation, perte, responsabilité, coût ou dette, et dépense (y compris, mais sans s'y limiter, les honoraires d'avocat) découlant de : (i) l'utilisation du Service par l'Utilisateur ; (ii) la violation des présentes CGU par l'Utilisateur ; (iii) la violation par l'Utilisateur des droits de tiers, y compris, mais sans s'y limiter, les droits de propriété intellectuelle ; ou (iv) tout Contenu généré, publié ou partagé par l'Utilisateur via le Service.\n\n7.5 Force Majeure : Aucune des parties ne sera responsable envers l'autre pour tout retard ou manquement à exécuter ses obligations résultant d'un cas de force majeure, tel que défini par le droit anglais."
    },
    {
      title: "8. Données Personnelles et Confidentialité",
      text: "8.1 Traitement des Données : Jastro collecte et traite les données personnelles des Utilisateurs conformément à sa Politique de Confidentialité. Cette politique détaille les catégories de données collectées, les finalités du traitement, les destinataires des données, les durées de conservation, ainsi que les droits des Utilisateurs et la façon de les exercer.\n\n8.2 Sous-traitants : Jastro peut faire appel à des sous-traitants pour réaliser certaines prestations nécessaires au fonctionnement du Service. Ces sous-traitants sont soumis à des obligations strictes de confidentialité et de sécurité concernant les données personnelles auxquelles ils pourraient avoir accès.\n\n8.3 Transferts Internationaux : Les données personnelles des Utilisateurs peuvent être transférées vers des pays situés en dehors de l'Union européenne. Dans de tels cas, Jastro s'assure que ces transferts sont effectués vers des pays offrant un niveau de protection adéquat ou sont encadrés par des garanties appropriées conformément au Règlement Général sur la Protection des Données (RGPD).\n\n8.4 Confidentialité du Contenu : Jastro s'engage à maintenir la confidentialité du Contenu généré par les Utilisateurs et à ne pas le divulguer à des tiers sans autorisation, sauf si la loi ou une décision de justice l'exige. Toutefois, l'Utilisateur reconnaît que Jastro peut utiliser des données anonymisées liées aux requêtes et au Contenu généré pour améliorer ses algorithmes et la qualité du Service."
    },
    {
      title: "9. Modifications des CGU",
      text: "9.1 Droit de Modification : Jastro se réserve le droit, à sa seule discrétion, de modifier, compléter ou remplacer toute partie des présentes CGU à tout moment. Les modifications peuvent être effectuées pour des raisons juridiques, pour refléter des changements dans le Service, ou pour toute autre raison jugée nécessaire par Jastro.\n\n9.2 Notification des Modifications : Jastro informera les Utilisateurs des modifications substantielles des CGU par email et/ou par un avis visible sur le Service. Pour les modifications mineures, Jastro pourra simplement mettre à jour la date de 'dernière mise à jour' en haut des CGU.\n\n9.3 Date d'Effet : Les modifications des CGU prennent effet dès leur publication sur le Service, sauf indication contraire. L'utilisation continue du Service après la publication des CGU modifiées constitue l'acceptation de ces modifications par l'Utilisateur.\n\n9.4 Droit de Refus : Si l'Utilisateur n'accepte pas les CGU modifiées, il doit cesser d'utiliser le Service et, le cas échéant, annuler son abonnement conformément à l'article 5.4 des présentes CGU."
    },
    {
      title: "10. Dispositions Diverses",
      text: "10.1 Intégralité de l'Accord : Ces CGU, ainsi que la Politique de Confidentialité et toutes conditions particulières applicables, constituent l'intégralité de l'accord entre l'Utilisateur et Jastro concernant l'utilisation du Service et remplacent tous les accords antérieurs ou contemporains, écrits ou oraux, relatifs à l'objet des présentes.\n\n10.2 Divisibilité : Si une disposition des présentes CGU est jugée illégale, nulle ou inapplicable, en tout ou en partie, par un tribunal compétent, cette disposition sera modifiée et interprétée de manière à réaliser au mieux les objectifs de la disposition originale dans les limites permises par la loi, et les autres dispositions des CGU resteront pleinement en vigueur.\n\n10.3 Renonciation : Le fait pour Jastro de ne pas exercer ou faire valoir un droit ou une disposition des présentes CGU ne constitue pas une renonciation à ce droit ou à cette disposition. Toute renonciation par Jastro à une obligation de l'Utilisateur en vertu des présentes CGU ne sera pas considérée comme une renonciation continue ou une renonciation à toute autre obligation.\n\n10.4 Cession : L'Utilisateur ne peut pas céder ou transférer ces CGU, en tout ou en partie, sans le consentement écrit préalable de Jastro. Jastro peut céder ou transférer ces CGU, en tout ou en partie, sans restriction et sans préavis à l'Utilisateur.\n\n10.5 Notifications : Toutes les notifications requises ou autorisées en vertu des présentes CGU doivent être faites par écrit et seront considérées comme dûment délivrées lorsqu'elles seront envoyées par email à l'adresse fournie par l'Utilisateur lors de son inscription ou à support@fitnessbrainai.com pour les notifications à Jastro.\n\n10.6 Survie : Les dispositions des présentes CGU qui, par leur nature, devraient survivre à la résiliation ou à l'expiration des CGU, survivront à cette résiliation ou expiration, y compris, mais sans s'y limiter, les dispositions relatives à la propriété intellectuelle, aux garanties et responsabilités, à l'indemnisation et à la résolution des litiges."
    },
    {
      title: "11. Loi applicable et juridiction compétente",
      text: "11.1 Loi applicable : Les présentes CGU ainsi que les relations entre l'Utilisateur et Neuralearns sont soumises au droit britannique.\n\n11.2 Résolution amiable : En cas de litige relatif à l'interprétation, la validité ou l'exécution des présentes CGU, les Parties s'engagent à rechercher une solution amiable. À défaut d'accord amiable, chaque Partie sera libre de saisir la juridiction compétente.\n\n11.3 Médiation : En cas de litige de consommation, conformément aux règlements alternatifs des litiges du Royaume-Uni, l'Utilisateur a le droit de recourir gratuitement à un médiateur de la consommation en vue de la résolution amiable du litige qui l'oppose à Neuralearns. Neuralearns adhère au service de médiation fourni par le Centre for Effective Dispute Resolution (CEDR).\n\n11.4 Juridiction compétente : À défaut de résolution amiable, tout litige relatif à l'interprétation, la validité ou l'exécution des présentes CGU sera soumis aux tribunaux britanniques compétents, sauf disposition impérative contraire."
    },
    {
      title: "12. Contact et Service Client",
      text: "Pour toute question concernant ces CGU ou le Service en général, veuillez nous contacter à :\n\nJastro Limited\nSuite 10 12 Durie Street, Leven, Fife, Royaume-Uni, KY8 4HE\nEmail: support@fitnessbrainai.com\nTéléphone: (850) 783-4170\nNuméro d'entreprise: 836841\nDate de constitution: 07/02/2025\n\nLe service client est disponible du lundi au vendredi, de 9h à 18h (heure du Royaume-Uni), à l'exception des jours fériés britanniques.\n\nDernière mise à jour: 25/03/2024"
    }
  ]
}; 